// SPDX-License-Identifier: AGPL-3.0-or-later
// Shared plumbing for the fault-injection suite: bake a hermetic
// scratch profile (desktop.toml + the CliSetup-grade ~/.sovereign/
// config.toml the supervisor gate requires), spawn a desktop instance
// with chosen env, and await bridge stickies.
//
// Unlike the main real suite, fault specs sometimes own their app
// instance (crash-loop, missing-model need boot-time conditions), so
// spawning is a library here, not only a global-setup concern.
import { spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const CRATE_ROOT = path.resolve(__dirname, "../../../..");
export const REPO_ROOT = path.resolve(CRATE_ROOT, "../../..");
export const ARTIFACTS = path.join(CRATE_ROOT, "test-artifacts");
const APP_BIN = path.join(REPO_ROOT, "target/debug/sovereign-desktop");
const CLI_BIN = path.join(REPO_ROOT, "target/debug/sovereign-cli");

export const CHAT_MODEL = path.join(REPO_ROOT, "sovereign/models/Qwen3.5-2B.Q6_K.gguf");
export const EMBED_MODEL = path.join(
  REPO_ROOT,
  "sovereign/models/Qwen3-Embedding-0.6B-Q8_0.gguf",
);

export interface ProfileOpts {
  /** Override the chat model path (missing-model spec points this at
   *  a nonexistent file). */
  chatModel?: string;
  /** Write the CliSetup config.toml (required for supervisor mode —
   *  a desktop.toml-only profile boots `Local { DesktopLegacy }` and
   *  the supervisor gate skips it). */
  cliSetupConfig?: boolean;
  /** Daemon client port for the CliSetup config. The SHARED supervised
   *  instance uses a non-default port (9751) so :9741 stays free for
   *  boot-fault instances — otherwise their bootstrap probes would see
   *  the shared child and silently flip to Attach mode, skipping the
   *  very code paths under test. */
  daemonPort?: number;
}

/** Bake a fresh profile under `dir` and return its HOME path. */
export function bakeProfile(dir: string, opts: ProfileOpts = {}): string {
  fs.rmSync(dir, { recursive: true, force: true });
  const home = path.join(dir, "home");
  const chatModel = opts.chatModel ?? CHAT_MODEL;
  const cfgDir = path.join(home, ".config/sovereign");
  fs.mkdirSync(cfgDir, { recursive: true });
  fs.mkdirSync(path.join(home, ".local/share"), { recursive: true });
  fs.mkdirSync(path.join(home, ".cache"), { recursive: true });
  const sovDir = path.join(home, ".sovereign");
  fs.mkdirSync(sovDir, { recursive: true });
  fs.symlinkSync(path.join(REPO_ROOT, "sovereign/models"), path.join(sovDir, "models"));

  fs.writeFileSync(
    path.join(cfgDir, "desktop.toml"),
    [
      `# Generated by tests/e2e/real/faults/spawn.ts`,
      `model_path = ${JSON.stringify(chatModel)}`,
      `primary_model_path = ${JSON.stringify(chatModel)}`,
      `embed_model_path = ${JSON.stringify(EMBED_MODEL)}`,
      `setup_complete = true`,
      `auto_collaborate = false`,
      ``,
    ].join("\n"),
  );

  if (opts.cliSetupConfig ?? true) {
    fs.writeFileSync(
      path.join(sovDir, "config.toml"),
      [
        `# Generated by tests/e2e/real/faults/spawn.ts — CliSetup-grade`,
        `# config so bootstrap resolves Local{CliSetup} and the`,
        `# supervisor gate engages. The supervised daemon child reads`,
        `# THIS file under the scratch HOME.`,
        `[models]`,
        `primary = ${JSON.stringify(chatModel)}`,
        `fast = ${JSON.stringify(chatModel)}`,
        `embed = ${JSON.stringify(EMBED_MODEL)}`,
        `context_size = 8192`,
        ``,
        `[daemon]`,
        `client_port = ${opts.daemonPort ?? 9741}`,
        ``,
      ].join("\n"),
    );
  }
  return home;
}

export interface DesktopInstance {
  pid: number;
  bridge: string;
  logPath: string;
  stop(): Promise<void>;
}

export interface SpawnOpts {
  profileDir: string;
  bridgePort: number;
  logName: string;
  supervisor?: boolean;
  /** Override the supervised child binary (crash-loop spec points
   *  this at a script that exits 1). */
  cliPath?: string;
  profile?: ProfileOpts;
}

export async function spawnDesktop(opts: SpawnOpts): Promise<DesktopInstance> {
  const home = bakeProfile(opts.profileDir, opts.profile);
  const logPath = path.join(ARTIFACTS, opts.logName);
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    HOME: home,
    XDG_CONFIG_HOME: path.join(home, ".config"),
    XDG_DATA_HOME: path.join(home, ".local/share"),
    XDG_CACHE_HOME: path.join(home, ".cache"),
    SOVEREIGN_COMMAND_BRIDGE: "1",
    SOVEREIGN_COMMAND_BRIDGE_PORT: String(opts.bridgePort),
    RUST_LOG:
      process.env.RUST_LOG ??
      "sovereign_desktop=info,sovereign_inference=info,sovereign_core=info",
  };
  if (opts.supervisor) {
    env.SOVEREIGN_USE_SUPERVISOR = "1";
    env.SOVEREIGN_CLI_PATH = opts.cliPath ?? CLI_BIN;
  }
  const log = fs.openSync(logPath, "w");
  const child = spawn(APP_BIN, [], {
    env,
    cwd: os.homedir(),
    stdio: ["ignore", log, log],
    detached: true,
  });
  child.unref();
  if (!child.pid) throw new Error(`spawnDesktop: failed (${opts.logName})`);

  const instance: DesktopInstance = {
    pid: child.pid,
    bridge: `http://127.0.0.1:${opts.bridgePort}`,
    logPath,
    stop: async () => {
      try {
        process.kill(child.pid!, "SIGTERM");
      } catch {
        return;
      }
      const deadline = Date.now() + 10_000;
      while (Date.now() < deadline) {
        try {
          process.kill(child.pid!, 0);
        } catch {
          return;
        }
        await new Promise((r) => setTimeout(r, 250));
      }
      try {
        process.kill(child.pid!, "SIGKILL");
      } catch {
        /* gone */
      }
    },
  };
  return instance;
}

export async function bridgeInvoke<T = unknown>(
  bridge: string,
  cmd: string,
  args: Record<string, unknown> = {},
): Promise<T> {
  const res = await fetch(`${bridge}/invoke`, {
    method: "POST",
    headers: { "content-type": "application/json", "x-sovereign-spec": "faults" },
    body: JSON.stringify({ cmd, args }),
  });
  const body = (await res.json()) as { ok: boolean; result?: T; error?: unknown };
  if (!body.ok) throw new Error(`invoke ${cmd}: ${JSON.stringify(body.error)}`);
  return body.result as T;
}

/** Await the bridge coming up, then a sticky event replay (e.g.
 *  backend-ready / setup-required / supervisor-state). Returns the
 *  replayed payload. */
export async function awaitSticky(
  bridge: string,
  event: string,
  timeoutMs: number,
): Promise<unknown> {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    try {
      const res = await fetch(`${bridge}/listen`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ event }),
        signal: AbortSignal.timeout(3000),
      });
      const body = (await res.json()) as { replayed?: boolean; replay?: unknown };
      if (body.replayed) return body.replay;
    } catch {
      /* bridge not up yet */
    }
    if (Date.now() > deadline) {
      throw new Error(`awaitSticky(${event}) timed out after ${timeoutMs}ms`);
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
}

/** Rows from the bridge's replay ring. */
export async function eventsRecent(
  bridge: string,
  sinceSeq = 0,
): Promise<Array<{ seq: number; event: string; payload: unknown }>> {
  const res = await fetch(`${bridge}/events/recent?since_seq=${sinceSeq}`);
  const body = (await res.json()) as { rows: Array<{ seq: number; event: string; payload: unknown }> };
  return body.rows;
}

export function portInUse(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    import("node:net").then(({ default: net }) => {
      const sock = net.connect({ port, host: "127.0.0.1" });
      const done = (used: boolean) => {
        sock.destroy();
        resolve(used);
      };
      sock.once("connect", () => done(true));
      sock.once("error", () => done(false));
      sock.setTimeout(1500, () => done(false));
    });
  });
}
