/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const dial_guest: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h01d0515847759c9e: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha05c7eb64c764fc4: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5011b813b999ddef: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5db3dcd938df7c65: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hf6d4bc7d0c318c8e: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h22b605a841f71cab: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h4947fcabcec40d8b: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__haa2864242c139a5d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hf136cc368050d5c2: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
