[package]
name = "sovereign-cli"
version.workspace = true
edition.workspace = true

[dependencies]
sovereign-core = { workspace = true }
sovereign-inference = { workspace = true }
sovereign-store = { workspace = true }
sovereign-tools = { workspace = true, features = ["treesitter"] }
sovereign-mesh = { workspace = true }
sovereign-atos = { workspace = true }
commonwealth-state = { path = "../../../commonwealth/crates/commonwealth-state" }
commonwealth-core  = { path = "../../../commonwealth/crates/commonwealth-core" }
corpus-engine = { workspace = true, features = ["treesitter"] }
async-trait = { workspace = true }
axum = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }
uuid = { workspace = true }
arc-swap = { workspace = true }
dirs = "5"
hostname = { workspace = true }
oicp-types = { path = "../../../oicp-types" }

[dev-dependencies]
tempfile = "3"
