// SPDX-License-Identifier: AGPL-3.0-or-later
//! `svrn project init` file scaffolding: deterministic generation (and
//! idempotent merge) of SOVEREIGN.md, AGENTS.md, the opencode + Claude
//! configs, the inject-notes hook script, and `.gitignore`. Pure string
//! builders driven by `super::cmd_init` — they take the already-detected
//! language list, so nothing here touches `DetectedLanguage` (which stays
//! with the detection glue in `super`). Split out 2026-07-13; pure move.

use super::*;

// ─── File generation ─────────────────────────────────────────

pub(super) fn generate_sovereign_md(
    corpus_id: &str,
    port: u16,
    langs: &[&str],
    has_scip: bool,
) -> String {
    let call_graph_section = if has_scip {
        "## Call graph

`find_callers` and `find_callees` use the SCIP graph.
New symbols have no graph entries until the next git commit
(the post-commit hook keeps this current automatically).
To refresh manually: `svrn project refresh`"
    } else {
        "## Call graph

Call graph tools are not available (no SCIP exporter found).
Install a SCIP exporter and run `svrn project refresh` to enable."
    };

    format!(
        r#"<!-- Generated by sovereign project init. Safe to commit. -->
# Sovereign Code Intelligence

MCP server: http://localhost:{port}/mcp
Corpus: {corpus_id}
Languages: {langs}

## Two ways to reach the tools

**MCP (preferred when the daemon is running).** Clients like Claude Code
auto-discover the full tool set via `tools/list` against the server above.
Structured, fast, native.

**CLI fallback.** The same 24 tools are callable as shell commands:

```
sovereign tools list                           # manifest, grouped by Effect × Scope
sovereign tools describe <id>                  # full descriptor + parameters + output keys + examples
sovereign tools call <id> [--key=value ...]    # invoke, plain text or --format json output
```

`svrn tools call symbol_lookup --name=Foo` runs the same
`Tool::execute()` as the MCP path — pick whichever is in front of you. Use
the CLI when the daemon isn't up, when scripting, or to see `--help`.

## Tools

| Tool | When to use | Notes |
|---|---|---|
| `symbol_lookup` | Know the exact name | Always correct |
| `code_search` | Know the concept, not the name | Approximate — verify with symbol_lookup |
| `recent_changes` | Session start / orientation | Always correct |
| `find_callers` | What calls this function? | SCIP-resolved, catches trait dispatch |
| `find_callees` | What does this function call? | SCIP-resolved |
| `blast_radius` | Transitive impact of a change | BFS up to depth 5 |
| `project_context` | Project conventions, architecture | FTS5 over markdown docs |
| `write_note` | Record decisions, invariants, todos | Persists across sessions |
| `read_notes` | Recall prior decisions | FTS or filter by symbol/file/kind |
| `delete_note` | Remove stale notes | By ID |
| `session_reflection` | End of significant task — record tool feedback | Feeds `svrn reflect` |
| `test_status` | Last test run result | |
| `run_tests` | Trigger a test run | |
| `get_run_output` | Test run stdout/stderr | |
| `lint_status` | Last lint result | |
| `get_lint_output` | Lint stdout/stderr | |

## Session start — do these first

1. Read `SYSTEM_OVERVIEW.md` at the repo root — do this every session. It is the authoritative map of what exists and how the pieces connect.
2. `recent_changes(hours: 24)` — see which subsystems are active
3. `project_context("<your task>")` — pull relevant conventions and docs
4. `read_notes(query: "<task area>")` — surface prior decisions

## Precision rules — do not skip

**DO NOT read an entire file to find a type definition.**
Call `symbol_lookup("TypeName")` first. It returns the exact definition
with file path and line numbers in one call. Fall back to Read only when
you need the surrounding context after locating the symbol.

**DO NOT grep for callers.**
Call `find_callers("function_name")` — compiler-resolved (SCIP), catches
trait dispatch that grep misses entirely.

**DO NOT guess at fields or constructor arguments.**
Even during greenfield work, call `symbol_lookup` before assuming a type's
shape. The writing is new; the patterns you're matching are not.

## Decision matrix

| Situation | Tool |
|---|---|
| "What files exist in this module?" | Glob + Read |
| "Show me the Foo struct" | `symbol_lookup("Foo")` |
| "What calls reindex_file?" | `find_callers("reindex_file")` |
| "What does ingest() call?" | `find_callees("ingest")` |
| "How does checkpoint resume work?" | `code_search` → `symbol_lookup` on results |
| "What changed recently?" | `recent_changes(hours: 24)` |
| "What are the conventions for X?" | `project_context("X")` |
| "What decisions were made about Y?" | `read_notes(query: "Y")` |
| "How many things depend on this?" | `blast_radius("symbol_name")` |

## Mandatory pre-flight checks

**Before adding a method to a trait:**
`find_callers("TraitName")` — finds ALL implementors. Every impl must
be updated or the build breaks. Do this before writing a single line.

**Before modifying a function signature:**
`find_callers("function_name")` — 20 callers needs a different strategy
than 2. Know the impact before touching the signature.

**Before any non-trivial change to an existing function:**
`blast_radius("function_name", max_depth: 2)` — see the transitive
callers, split by production vs test, grouped by module.

**Before using a type from another crate:**
`symbol_lookup("TypeName")` — confirm it exists, see its fields.
Faster and more reliable than grepping Cargo.toml.

## Writing notes

Use `write_note` to leave durable context for future sessions.
Write at the moment of the decision, not at the end.

- **`decision`** — chose one approach over alternatives; include the reason
- **`invariant`** — a constraint that must never be violated
- **`todo`** — follow-up work outside the current session's scope
- **`attempt`** — an approach that was tried and failed; prevents repetition

## Session reflection — at task end

Use `session_reflection` when a significant task is complete (refactor lands, bug fixed, feature shipped). Be specific.

```
session_reflection(
  task_summary: "Refactored EmbedFn across 12 call sites",
  tool_name: "blast_radius",
  tools_that_helped: ["blast_radius", "lint_status"],
  manual_work_that_should_be_a_tool: "Had to grep for macro invocations blast_radius missed",
  wished_i_had_known: "EmbedFn is wrapped in a macro — blast_radius does not surface macro call sites"
)
```

**Before using `blast_radius` or `project_context` on a large task**, check for known limitations first:
`read_notes(kinds=["reflection"], query="<tool_name>")` — limitations disappear from results
once the developer retires them via `svrn reflect --retire`.

When you see `[sovereign] N tool calls this session. Consider calling session_reflection…`
appended to a tool response, it is a nudge — write one when the work feels significant.

## Developer: reviewing reflections

`svrn reflect` reads the accumulated backlog from any directory — it finds the active
database automatically via `~/.sovereign/active_notes_db`.

```bash
sovereign reflect                          # 30-day summary: signals, what helped, open todos
sovereign reflect --since 7d              # narrow the window
sovereign reflect --tool blast_radius     # focus on one tool
sovereign reflect --raw                   # full prose, ungrouped
sovereign reflect --todos                 # open todo notes
sovereign reflect --history               # include retired reflections
```

**Retiring a fixed limitation** — once resolved, retire the reflection so agents stop seeing
it as an active warning:

```bash
sovereign reflect --retire --tool blast_radius --reason "macro scan added in PR #88"
sovereign reflect --retire --id <uuid>    --reason "no longer relevant"  # add --yes to skip prompt
```

Retired reflections are hidden from agents but preserved in `--history` for audit.

## Compilation and test feedback

**DO NOT run `cargo build`, `cargo check`, or `cargo test` via Bash**
in this project. Running these directly contends with the background
watcher for the Cargo file lock — one blocks the other and you idle.

The watcher runs cargo check continuously on file changes. The result
is usually already cached by the time you finish an edit.

**"Does this compile?"** → `lint_status`
| Status | Meaning | Action |
|---|---|---|
| `fresh_passing` | Clean | Keep going |
| `fresh_failing` | Errors in response | Fix them |
| `stale` | Watcher queued | Call again in ~15s |
| `running` | In progress | Call again in ~15s |
| `never_run` | Watcher not configured | Fall back to Bash |

**"Do tests pass?"** → `test_status`
| Status | Meaning | Action |
|---|---|---|
| `fresh_passing` | All pass | Safe to proceed |
| `fresh_failing` | Failures in response | Fix them |
| `stale` | Files changed since last run | `run_tests`, then poll |
| `running` | In progress | Poll every ~30s |
| `never_run` | Watcher not configured | Fall back to Bash |

Call `get_lint_output` / `get_run_output` **only** when
`output_truncated: true`. The errors are already in the status response.
Never poll in a tight loop — use a 15-30s gap between checks.

## Server lifecycle

`svrn project serve` hot-reloads SCIP every 30 seconds. Post-commit
hooks keep both the symbol index and call graph current automatically.
If something seems stale, check `~/.sovereign/hooks.log` and run
`svrn project install-hooks` if the hook predates recent changes.

{call_graph_section}

## Project-specific invariants

Add invariants below this line. These are read by the coding agent
at session start and treated as authoritative guidance from the
architect.

---
"#,
        langs = langs.join(", "),
    )
}

/// Generate `.opencode/opencode.json` — registers the sovereign MCP server and,
/// when Commonwealth is configured, a custom OpenAI-compatible provider backed
/// by the OICP mesh. Models are populated from live OICP capabilities when
/// available; falls back to a single `"auto"` entry otherwise.
pub(super) fn generate_opencode_config(
    port: u16,
    commonwealth_url: Option<&str>,
    commonwealth_models: &[String],
) -> String {
    // `mcp` is a FLAT map of name → McpLocalConfig | McpRemoteConfig
    // (opencode SDK `Config.mcp`); the only valid `type` discriminators
    // are "local" and "remote". Verified against opencode 1.14.48.
    let mut config = serde_json::json!({
        "mcp": {
            "sovereign": {
                "type": "remote",
                "url": format!("http://localhost:{port}/mcp")
            }
        }
    });

    if let Some(url) = commonwealth_url {
        let base = format!("{}/v1", url.trim_end_matches('/').replace(":9742", ":9741"));

        let mut models = serde_json::Map::new();
        for id in commonwealth_models {
            models.insert(id.clone(), serde_json::json!({ "name": id }));
        }
        if models.is_empty() {
            // Commonwealth not reachable at init time; "auto" routes at runtime.
            models.insert(
                "auto".into(),
                serde_json::json!({ "name": "Commonwealth (auto-routed)" }),
            );
        }

        config["provider"] = serde_json::json!({
            "commonwealth": {
                "npm": "@ai-sdk/openai-compatible",
                "name": "Commonwealth Mesh",
                "options": { "baseURL": base },
                "models": models
            }
        });
    }

    serde_json::to_string_pretty(&config).unwrap_or_default()
}

/// Merge a generated opencode config into an existing one without clobbering
/// other MCP servers or user settings. Only adds the `sovereign` server entry.
pub(super) fn merge_opencode_config(existing: &str, generated: &str) -> String {
    let mut base: serde_json::Value =
        serde_json::from_str(existing).unwrap_or(serde_json::json!({}));
    let new: serde_json::Value = match serde_json::from_str(generated) {
        Ok(v) => v,
        Err(_) => return generated.to_string(),
    };

    if let Some(new_servers) = new.get("mcp").and_then(|m| m.as_object()) {
        let mcp = base
            .as_object_mut()
            .unwrap()
            .entry("mcp")
            .or_insert_with(|| serde_json::json!({}));
        if let Some(map) = mcp.as_object_mut() {
            // Evict our pre-2026-07-28 `mcp.servers.sovereign` entry.
            // opencode reads `mcp` as a flat name → server map, so a
            // `servers` key parses as a typeless server and fails the
            // whole config's schema — writing the right key while
            // leaving the old one behind still leaves the user broken.
            let drop_servers = map
                .get_mut("servers")
                .and_then(|s| s.as_object_mut())
                .map(|s| {
                    s.remove("sovereign");
                    s.is_empty()
                })
                .unwrap_or(false);
            if drop_servers {
                map.remove("servers");
            }
            for (k, v) in new_servers {
                map.insert(k.clone(), v.clone());
            }
        }
    }

    // Merge provider.commonwealth — add or update, preserve other providers.
    if let Some(cw_provider) = new.get("provider").and_then(|p| p.get("commonwealth")) {
        let provider = base
            .as_object_mut()
            .unwrap()
            .entry("provider")
            .or_insert_with(|| serde_json::json!({}));
        if let Some(map) = provider.as_object_mut() {
            map.insert("commonwealth".into(), cw_provider.clone());
        }
    }

    serde_json::to_string_pretty(&base).unwrap_or_else(|_| generated.to_string())
}

/// Generate a starter AGENTS.md for projects that don't have one.
/// Opencode (and other agents that read AGENTS.md) use this as their
/// system-level instructions for the codebase.
pub(super) fn generate_agents_md(
    corpus_id: &str,
    port: u16,
    has_scip: bool,
    commonwealth_url: Option<&str>,
) -> String {
    let scip_section = if has_scip {
        "\n## Pre-flight before editing\n\
         \n\
         - **Before changing a function signature**: `find_callers(\"fn\")` first — counts every call site.\n\
         - **Before adding a method to a trait**: `find_callers(\"TraitName\")` to find all implementors.\n\
         - **Before a non-trivial refactor**: `blast_radius(\"symbol\", max_depth: 2)`.\n"
    } else {
        "\n## Pre-flight before editing\n\
         \n\
         Call graph tools are not available (SCIP not enabled). Use `code_search` to find usage patterns.\n"
    };

    let inference_section = if let Some(url) = commonwealth_url {
        let base = url.trim_end_matches('/').replace(":9742", ":9741");
        format!(
            "\n## Inference\n\
             \n\
             Commonwealth mesh provider is configured at `{base}`.\n\
             Use model `commonwealth/<model-id>` in opencode to route through the mesh.\n\
             Run `GET {base}/v1/models` to list currently available models.\n"
        )
    } else {
        String::new()
    };

    format!(
        "# Agent instructions — {corpus_id}\n\
         \n\
         ## Code intelligence (MCP preferred; CLI fallback)\n\
         \n\
         A sovereign MCP server at `http://localhost:{port}/mcp` exposes compiler-resolved\n\
         tools for this codebase. **Use MCP tools before reading files.**\n\
         \n\
         When MCP isn't available (daemon stopped, scripting, ad-hoc shell use), the\n\
         same tools are reachable as `svrn tools {{list|describe|call}} ...` —\n\
         plain-text output, `--help` on every subcommand. `svrn tools list`\n\
         prints the live catalog grouped by Effect × Scope. Same `Tool::execute()`\n\
         underneath either path.\n\
         \n\
         | Tool | Purpose |\n\
         |---|---|\n\
         | `symbol_lookup` | Exact struct/trait/fn definition — use instead of reading files |\n\
         | `find_callers` | All call sites, compiler-resolved (catches trait dispatch) |\n\
         | `find_callees` | What a function calls |\n\
         | `blast_radius` | Transitive impact of changing a symbol |\n\
         | `code_search` | Semantic search across the codebase |\n\
         | `recent_changes` | Files changed in the last N hours |\n\
         | `project_context` | Architecture and conventions for a topic |\n\
         | `read_notes` | Decisions and invariants from prior sessions |\n\
         | `write_note` | Record a decision, invariant, todo, or failed attempt |\n\
         | `lint_status` | Check for compile errors (do not run `cargo check` via shell) |\n\
         | `test_status` | Check test results (do not run `cargo test` via shell) |\n\
         \n\
         ## Required session start\n\
         \n\
         1. `read_notes(query: \"active\")` — surface active invariants and todos\n\
         2. `project_context(\"<task area>\")` — pull relevant conventions\n\
         3. `recent_changes(hours: 24)` — see what's been touched\n\
         {scip_section}\n\
         ## Build and test feedback\n\
         \n\
         The sovereign watcher runs continuously in the background. **Do not run `cargo check`,\n\
         `cargo build`, `cargo test`, or `cargo clippy` directly** — they contend with the watcher\n\
         for the Cargo file lock and stall both processes.\n\
         \n\
         - Check compile status: `lint_status` — response includes `age_seconds`, `watched_scope`,\n\
           and `watcher_active` so you can confirm the result covers your changes.\n\
         - Check test status: `test_status` — if stale, call `run_tests` then poll.\n\
         - Only fall back to `cargo` commands when `lint_status` returns `watcher_active: false`.\n\
         \n\
         ## Session discipline\n\
         \n\
         - Call `write_note(kind: \"invariant\")` when you discover a constraint that must never be violated.\n\
         - Call `write_note(kind: \"decision\")` when you choose one approach over alternatives.\n\
         - Call `session_reflection` at the end of any significant task.\n\
         {inference_section}"
    )
}

/// Generate the inject-notes.sh hook script content for the given port.
///
/// The hook is ATOS-aware: when `$SOVEREIGN_FEATURE_ID` is set in the driver
/// environment (see `svrn atos start-milestone`), the MCP call includes
/// `scope=["global","feature"]` plus that feature_id so the agent sees both
/// global invariants and the in-flight feature's decisions. Outside an ATOS
/// session the hook scopes to globals only — feature-specific chatter from
/// in-flight work does not leak into unrelated Claude sessions.
pub(super) fn generate_inject_notes_script(port: u16) -> String {
    format!(
        r#"#!/bin/sh
# sovereign inject-notes — UserPromptSubmit hook for Claude Code.
# Fetches active invariants and decisions from the sovereign MCP server and
# prints them as context before every Claude response.
# Fails silently when the server is not running so offline work is unaffected.

PORT="${{SOVEREIGN_PORT:-{port}}}"

# ATOS scope-aware payload. When $SOVEREIGN_FEATURE_ID is set (by
# `svrn atos start-milestone`), the query pulls global notes plus
# the active feature's notes. Otherwise only globals are injected.
if [ -n "${{SOVEREIGN_FEATURE_ID:-}}" ]; then
  PAYLOAD=$(printf '{{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{{"name":"read_notes","arguments":{{"kinds":["invariant","decision"],"scope":["global","feature"],"feature_id":"%s","limit":20}}}}}}' "$SOVEREIGN_FEATURE_ID")
else
  PAYLOAD='{{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{{"name":"read_notes","arguments":{{"kinds":["invariant","decision"],"scope":["global"],"limit":20}}}}}}'
fi

RESPONSE=$(curl -sf --max-time 2 \
  -X POST "http://localhost:${{PORT}}/mcp" \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" \
  2>/dev/null) || exit 0

[ -z "$RESPONSE" ] && exit 0

printf '%s' "$RESPONSE" | python3 -c "
import sys, os, json

try:
    outer = json.load(sys.stdin)
    inner_text = outer['result']['content'][0]['text']
    inner = json.loads(inner_text)
    notes = inner.get('notes', [])
    if not notes:
        sys.exit(0)
    fid = os.environ.get('SOVEREIGN_FEATURE_ID', '')
    header = '## Active sovereign notes (injected by hook)'
    if fid:
        header = header + ' (feature=' + fid + ')'
    print(header)
    print()
    for n in notes:
        kind = n.get('kind', 'note')
        scope = n.get('scope', 'global')
        content = n.get('content', '').strip()
        tag = kind if scope == 'global' else kind + '/' + scope
        print('[' + tag + '] ' + content)
        print()
except Exception:
    sys.exit(0)
" 2>/dev/null
"#
    )
}

pub(super) fn generate_claude_settings(
    port: u16,
    corpus_id: &str,
    has_git: bool,
    has_scip: bool,
) -> String {
    let scip_instruction = if has_scip {
        "MANDATORY PRE-FLIGHT — before modifying any existing function: \
         call find_callers to count dependents; call blast_radius for \
         transitive impact. Before adding a method to a trait: call \
         find_callers on the trait name to find every implementor — \
         all must be updated or the build breaks. Before implementing \
         a new function: call find_callees on a similar function to \
         see the established pattern."
    } else {
        "Call graph tools are not available (no SCIP exporter). \
         Use code_search to find usage patterns."
    };

    let git_instruction = if has_git {
        " This is a git repository. recent_changes reflects \
         filesystem modification time, not git history."
    } else {
        ""
    };

    let system_prompt = format!(
        "You have access to Sovereign code intelligence for \
         the {corpus_id} codebase via MCP. \
         Read .sovereign/SOVEREIGN.md for the full tool reference \
         and project-specific invariants. When MCP isn't available \
         (daemon stopped, scripting, non-MCP client), the same tools \
         are reachable as `svrn tools {{list|describe|call}}` — \
         see `.sovereign/SOVEREIGN.md` for the CLI section.\n\n\
         SESSION START — run these three calls before anything else:\n\
         1. recent_changes(hours: 24) — see which subsystems are active\n\
         2. project_context(\"<user task>\") — pull relevant conventions\n\
         3. read_notes(query: \"<task area>\") — recall prior decisions\n\n\
         PRECISION RULES — never skip:\n\
         - DO NOT read an entire file to find a type definition. \
           Call symbol_lookup(\"TypeName\") first. Only use Read when \
           you need the surrounding context after locating the symbol.\n\
         - DO NOT grep for callers. Call find_callers — it is \
           compiler-resolved (SCIP) and catches trait dispatch that \
           grep misses entirely.\n\
         - DO NOT guess at field names or constructor arguments. \
           Call symbol_lookup even during greenfield work.\n\n\
         {scip_instruction}\n\n\
         BUILD & TEST FEEDBACK — never run cargo via Bash in watched \
         projects; it contends for the Cargo lock and stalls both:\n\
         - 'Does this compile?' → lint_status (instant, pre-computed)\n\
           fresh_passing=clean; fresh_failing=errors in response; \
           stale=watcher queued, check again in ~15s; \
           running=check again in ~15s; \
           never_run=watcher not configured, THEN use Bash.\n\
         - 'Do tests pass?' → test_status (instant, pre-computed)\n\
           fresh_passing=safe; fresh_failing=failures in response; \
           stale=call run_tests then poll every ~30s; \
           running=poll every ~30s; \
           never_run=watcher not configured, THEN use Bash.\n\
         - Call get_lint_output / get_run_output only when \
           output_truncated is true. Never poll in a tight loop.\n\n\
         WRITING NOTES — use write_note at the moment of the decision:\n\
         - kind=decision: chose approach X over Y; include the reason\n\
         - kind=invariant: constraint that must never be violated\n\
         - kind=todo: follow-up outside this session's scope\n\
         - kind=attempt: tried and failed; prevents repetition\n\n\
         SESSION REFLECTION — at the end of a significant task call session_reflection: \
         record which tools helped, what you had to do manually that a tool should have \
         handled, and what you wished you had known earlier. Be specific. \
         Before using blast_radius or project_context on a large task: \
         read_notes(kinds=[\"reflection\"], query=\"<tool_name>\") to check for known \
         limitations recorded by previous sessions.\n\n\
         {git_instruction}"
    );

    serde_json::to_string_pretty(&serde_json::json!({
        "mcpServers": {
            "sovereign": {
                "type": "http",
                "url": format!("http://localhost:{port}/mcp")
            }
        },
        "systemPrompt": system_prompt,
        "hooks": {
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": "sh .claude/hooks/inject-notes.sh"
                        }
                    ]
                }
            ]
        }
    }))
    .unwrap_or_default()
}

/// Merge generated settings into existing .claude/settings.json without
/// clobbering user settings. Adds the sovereign MCP entry and prepends
/// the system prompt.
pub(super) fn merge_claude_settings(existing: &str, generated: &str) -> String {
    let mut base: serde_json::Value =
        serde_json::from_str(existing).unwrap_or(serde_json::json!({}));
    let new: serde_json::Value = match serde_json::from_str(generated) {
        Ok(v) => v,
        Err(_) => return generated.to_string(),
    };

    // Merge mcpServers — add sovereign without removing others.
    if let Some(new_servers) = new.get("mcpServers").and_then(|v| v.as_object()) {
        let base_servers = base
            .as_object_mut()
            .unwrap()
            .entry("mcpServers")
            .or_insert_with(|| serde_json::json!({}));
        if let Some(base_map) = base_servers.as_object_mut() {
            for (k, v) in new_servers {
                base_map.insert(k.clone(), v.clone());
            }
        }
    }

    // Update the systemPrompt. If the existing prompt contains
    // non-Sovereign content, preserve it after the Sovereign block.
    if let Some(new_prompt) = new.get("systemPrompt").and_then(|v| v.as_str()) {
        if let Some(existing_prompt) = base.get("systemPrompt").and_then(|v| v.as_str()) {
            if existing_prompt.contains("Sovereign code intelligence") {
                // Replace the existing Sovereign block with the latest version.
                // If there's user content after the "---" separator, keep it.
                let user_section = existing_prompt
                    .split("\n\n---\n\n")
                    .skip(1)
                    .collect::<Vec<_>>()
                    .join("\n\n---\n\n");
                if user_section.is_empty() {
                    base["systemPrompt"] = serde_json::json!(new_prompt);
                } else {
                    base["systemPrompt"] =
                        serde_json::json!(format!("{new_prompt}\n\n---\n\n{user_section}"));
                }
            } else {
                // No Sovereign content yet — prepend.
                base["systemPrompt"] =
                    serde_json::json!(format!("{new_prompt}\n\n---\n\n{existing_prompt}"));
            }
        } else {
            base["systemPrompt"] = serde_json::json!(new_prompt);
        }
    }

    // Merge hooks — add the sovereign UserPromptSubmit hook without removing
    // other hooks the user may have configured. We identify our hook by its
    // command string and skip re-adding it if already present.
    if let Some(new_hooks) = new.get("hooks").and_then(|v| v.as_object()) {
        let base_hooks = base
            .as_object_mut()
            .unwrap()
            .entry("hooks")
            .or_insert_with(|| serde_json::json!({}));
        if let (Some(base_hooks_map), Some(new_ups)) = (
            base_hooks.as_object_mut(),
            new_hooks.get("UserPromptSubmit").and_then(|v| v.as_array()),
        ) {
            let existing_ups = base_hooks_map
                .entry("UserPromptSubmit")
                .or_insert_with(|| serde_json::json!([]));
            if let Some(arr) = existing_ups.as_array_mut() {
                for new_entry in new_ups {
                    // Check if the exact command is already present.
                    let new_cmd = new_entry
                        .get("hooks")
                        .and_then(|h| h.as_array())
                        .and_then(|h| h.first())
                        .and_then(|h| h.get("command"))
                        .and_then(|c| c.as_str())
                        .unwrap_or("");
                    let already_present = arr.iter().any(|e| {
                        e.get("hooks")
                            .and_then(|h| h.as_array())
                            .and_then(|h| h.first())
                            .and_then(|h| h.get("command"))
                            .and_then(|c| c.as_str())
                            .map(|c| c == new_cmd)
                            .unwrap_or(false)
                    });
                    if !already_present {
                        arr.push(new_entry.clone());
                    }
                }
            }
        }
    }

    serde_json::to_string_pretty(&base).unwrap_or_else(|_| generated.to_string())
}

// ─── .gitignore ──────────────────────────────────────────────

pub(super) fn update_gitignore(root: &Path) -> std::io::Result<()> {
    let gitignore_path = root.join(".gitignore");
    let entries_to_add = [".sovereign/project.json", ".sovereign/scip/"];

    let existing = if gitignore_path.exists() {
        std::fs::read_to_string(&gitignore_path)?
    } else {
        String::new()
    };

    let mut additions = Vec::new();
    for entry in entries_to_add {
        if !existing.lines().any(|line| line.trim() == entry) {
            additions.push(entry);
        }
    }

    if additions.is_empty() {
        return Ok(());
    }

    let mut content = existing;
    if !content.is_empty() && !content.ends_with('\n') {
        content.push('\n');
    }

    if !content.is_empty() {
        content.push_str("\n# Sovereign code intelligence\n");
    } else {
        content.push_str("# Sovereign code intelligence\n");
    }
    for entry in additions {
        content.push_str(entry);
        content.push('\n');
    }

    std::fs::write(&gitignore_path, content)
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── opencode config generation ──────────────────────────────

    #[test]
    fn opencode_config_no_commonwealth() {
        let s = generate_opencode_config(9741, None, &[]);
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert_eq!(v["mcp"]["sovereign"]["url"], "http://localhost:9741/mcp");
        assert_eq!(v["mcp"]["sovereign"]["type"], "remote");
        assert!(
            v["mcp"]["servers"].is_null(),
            "must not reintroduce the nested `mcp.servers` shape opencode rejects"
        );
        assert!(v.get("provider").is_none());
    }

    /// The generator emitted `mcp.servers.sovereign` with `type: "http"`
    /// until 2026-07-28. Both are invalid: `mcp` is a flat name → server
    /// map and the discriminators are "local"/"remote". A merge must
    /// evict the old entry, not sit beside it.
    #[test]
    fn merge_opencode_evicts_legacy_servers_shape() {
        let existing = r#"{"mcp":{"servers":{"sovereign":{"type":"http","url":"http://localhost:9741/mcp"}}}}"#;
        let generated = generate_opencode_config(9741, None, &[]);
        let merged = merge_opencode_config(existing, &generated);
        let v: serde_json::Value = serde_json::from_str(&merged).unwrap();
        assert_eq!(v["mcp"]["sovereign"]["type"], "remote");
        assert!(
            v["mcp"]["servers"].is_null(),
            "the legacy `mcp.servers` object must be gone, not merely shadowed"
        );
    }

    /// Eviction is surgical: a peer's entry parked under the same bad
    /// key is not ours to delete.
    #[test]
    fn merge_opencode_keeps_foreign_entries_under_legacy_key() {
        let existing = r#"{"mcp":{"servers":{"sovereign":{"type":"http","url":"http://localhost:9741/mcp"},"github":{"type":"http","url":"https://example.com/mcp"}}}}"#;
        let generated = generate_opencode_config(9741, None, &[]);
        let merged = merge_opencode_config(existing, &generated);
        let v: serde_json::Value = serde_json::from_str(&merged).unwrap();
        assert_eq!(v["mcp"]["sovereign"]["type"], "remote");
        assert!(v["mcp"]["servers"]["sovereign"].is_null());
        assert_eq!(
            v["mcp"]["servers"]["github"]["url"],
            "https://example.com/mcp"
        );
    }

    #[test]
    fn opencode_config_commonwealth_no_models_uses_auto_fallback() {
        let s = generate_opencode_config(9741, Some("http://localhost:9741"), &[]);
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert_eq!(
            v["provider"]["commonwealth"]["options"]["baseURL"],
            "http://localhost:9741/v1"
        );
        assert!(v["provider"]["commonwealth"]["models"]["auto"].is_object());
    }

    #[test]
    fn opencode_config_commonwealth_real_models() {
        let models = vec!["Qwen3-9B".into(), "Qwen3-27B".into()];
        let s = generate_opencode_config(9741, Some("http://localhost:9741"), &models);
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        let m = &v["provider"]["commonwealth"]["models"];
        assert!(m["Qwen3-9B"].is_object());
        assert!(m["Qwen3-27B"].is_object());
        assert!(
            m.get("auto").is_none(),
            "auto should not appear when real models are known"
        );
    }

    #[test]
    fn opencode_config_normalizes_internal_port() {
        // Port 9742 (internal mesh) should be rewritten to 9741 (public API)
        let s = generate_opencode_config(9741, Some("http://localhost:9742"), &[]);
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert_eq!(
            v["provider"]["commonwealth"]["options"]["baseURL"],
            "http://localhost:9741/v1"
        );
    }

    #[test]
    fn merge_opencode_adds_commonwealth_provider() {
        let existing = r#"{"mcp":{"servers":{"sovereign":{"type":"http","url":"http://localhost:9741/mcp"}}}}"#;
        let generated = generate_opencode_config(9741, Some("http://localhost:9741"), &[]);
        let merged = merge_opencode_config(existing, &generated);
        let v: serde_json::Value = serde_json::from_str(&merged).unwrap();
        assert!(v["provider"]["commonwealth"]["options"]["baseURL"].is_string());
    }

    #[test]
    fn merge_opencode_preserves_other_providers() {
        let existing = r#"{"mcp":{},"provider":{"openai":{"name":"OpenAI","options":{"baseURL":"https://api.openai.com/v1"}}}}"#;
        let generated = generate_opencode_config(9741, Some("http://localhost:9741"), &[]);
        let merged = merge_opencode_config(existing, &generated);
        let v: serde_json::Value = serde_json::from_str(&merged).unwrap();
        assert!(
            v["provider"]["openai"].is_object(),
            "pre-existing provider must survive"
        );
        assert!(
            v["provider"]["commonwealth"].is_object(),
            "commonwealth must be added"
        );
    }

    #[test]
    fn merge_opencode_no_commonwealth_in_generated_leaves_existing_provider_intact() {
        let existing = r#"{"mcp":{},"provider":{"commonwealth":{"name":"old"}}}"#;
        // generate without commonwealth URL → no provider key in generated
        let generated = generate_opencode_config(9741, None, &[]);
        let merged = merge_opencode_config(existing, &generated);
        let v: serde_json::Value = serde_json::from_str(&merged).unwrap();
        // existing commonwealth entry should be preserved unchanged
        assert_eq!(v["provider"]["commonwealth"]["name"], "old");
    }

    #[test]
    fn agents_md_includes_inference_section_when_commonwealth_configured() {
        let md = generate_agents_md("myproject", 9741, true, Some("http://localhost:9741"));
        assert!(md.contains("Commonwealth mesh provider"));
        assert!(md.contains("commonwealth/<model-id>"));
    }

    #[test]
    fn agents_md_no_inference_section_without_commonwealth() {
        let md = generate_agents_md("myproject", 9741, true, None);
        assert!(!md.contains("Commonwealth mesh provider"));
    }
}
