//! Threaded-turn chunker for chat-transcript content.
//!
//! Reads the turn-block format emitted by `AnthropicExportExtractor`:
//!
//! ```text
//! ### [2025-09-04 18:01] user
//!
//! What was our burn rate last month?
//!
//! ### [2025-09-04 18:02] assistant
//!
//! Based on the bank statement you shared, burn was $312k.
//! ```
//!
//! Groups each `user` turn with the immediately-following `assistant`
//! reply into one chunk. A dangling `user` turn (no reply) or a
//! leading `assistant` turn (no preceding user — rare in claude.ai
//! exports) becomes a standalone chunk.
//!
//! ## Attribution
//!
//! Conversation history and inner-work journaling are corpora where
//! "who wrote this span?" is load-bearing — searching for "what did
//! *I* decide about X" must not return spans authored by the model,
//! and vice versa. The chunker therefore emits a parallel
//! `AttributedChunk` surface alongside the plain `TextChunk`:
//!
//! - `Chunker::chunk` returns `Vec<TextChunk>` for pipeline
//!   compatibility (embedding, FTS index, default retrieval).
//! - `chunk_attributed` returns `Vec<AttributedChunk>`, where each
//!   chunk carries `spans: Vec<TurnSpan>` listing the byte ranges
//!   inside the chunk content that came from each author.
//!
//! Downstream code that cares about authorship (atlas extraction,
//! filtered retrieval, bench scoring) consumes `chunk_attributed`;
//! everything else stays on the plain surface.
//!
//! ### Attribution enum scope
//!
//! Today the variants are `User` and `Assistant`. The enum reserves
//! `Unattributed` and `Pasted` for the inner-work journaling ingest
//! (a separate extractor): journals contain free-form prose (no
//! marker), and sometimes spans the user has pasted in from a model
//! elsewhere — authorship is the user, underlying generation is the
//! model, retrieval may want to weight that differently. Defining
//! the variants here keeps a single `Attribution` type across both
//! corpora so retrieval and bench code does not branch on corpus
//! type.

use regex::Regex;
use std::sync::OnceLock;

use super::{floor_char_boundary, Chunker, TextChunk};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Attribution {
    User,
    Assistant,
    /// Free-form prose with no explicit sender — reserved for the
    /// inner-work journaling ingest. Not emitted by this chunker.
    Unattributed,
    /// Text the user pasted from a model elsewhere; claimed author
    /// is the user, generated by a model. Reserved for inner-work
    /// journaling ingest. Not emitted by this chunker.
    Pasted,
}

impl Attribution {
    pub fn slug(self) -> &'static str {
        match self {
            Attribution::User => "user",
            Attribution::Assistant => "assistant",
            Attribution::Unattributed => "unattributed",
            Attribution::Pasted => "pasted",
        }
    }
}

#[derive(Debug, Clone)]
pub struct TurnSpan {
    pub attribution: Attribution,
    /// `YYYY-MM-DD HH:MM` shape if the source had a timestamp, else
    /// `None`. Inner-work journaling spans without timestamps will
    /// pass `None`.
    pub timestamp: Option<String>,
    /// Byte offsets inside the parent chunk's `content` string. Half-
    /// open: `[start, end)`. Always falls on UTF-8 char boundaries
    /// because the chunker only ever concatenates whole turn blocks.
    pub byte_range: (usize, usize),
}

#[derive(Debug, Clone)]
pub struct AttributedChunk {
    pub content: String,
    pub index: usize,
    pub spans: Vec<TurnSpan>,
}

pub struct ThreadedTurnsChunker;

/// Soft cap on the byte length of a single chunk emitted by this
/// chunker. Mirrors the default paragraph-chunker cap (1500 chars
/// ≈ ~400 tokens at English-prose densities) so paired-turn output
/// lands inside the embed slot's `max_input_tokens = 1024` budget
/// even when a user has pasted a large code block or document into
/// one turn.
///
/// Without this cap, oversized chunks throttled batch embedding to
/// 1.2 seqs/sec (vs. 29-33 seqs/sec on wikipedia paragraphs) during
/// the first end-to-end import of a real claude.ai export.
/// `_BAK-2026-05-18` in `~/.sovereign/conversations/` is the
/// reproducer; the conversations-anthropic ingest moved at
/// ~4 chunks/sec until this cap landed.
///
/// 1500 chars is a soft target — the splitter tries to break on a
/// blank line first (preserves paragraph shape), then any newline,
/// then falls back to a raw char boundary. The 1.4× safety margin
/// (`MAX_HARD_CHARS`) catches the rare case where no whitespace
/// exists in the chunk's tail (e.g. a base64 blob), keeping the
/// embed slot from truncating mid-multibyte.
const MAX_CHUNK_CHARS: usize = 1500;

/// Absolute ceiling — when the splitter can't find a soft boundary
/// inside the [MAX_CHUNK_CHARS, MAX_HARD_CHARS] window, it forces a
/// break at a UTF-8 char boundary at `MAX_HARD_CHARS`.
const MAX_HARD_CHARS: usize = 2100;

/// Inter-chunk overlap (in chars) for split sub-chunks. Bridges a
/// fact that straddled the soft boundary — the same posture
/// `ParagraphChunker` takes with its 100-char default. Sub-chunks
/// derived from one turn pair carry the same `Attribution` spans,
/// clipped to each sub-chunk's byte range.
const SPLIT_OVERLAP_CHARS: usize = 80;

impl ThreadedTurnsChunker {
    pub fn new() -> Self {
        Self
    }

    /// Chunk with per-span attribution. Each returned chunk has a
    /// `spans` vector — typically two entries (user + assistant), or
    /// one for a dangling turn.
    pub fn chunk_attributed(&self, text: &str) -> Vec<AttributedChunk> {
        let turns = parse_turns(text);
        if turns.is_empty() {
            let trimmed = text.trim();
            if trimmed.is_empty() {
                return Vec::new();
            }
            // Degrade: whole-text chunk with no attribution markers.
            // Caller using this chunker on non-conversation content
            // gets a single Unattributed span so authorship surfaces
            // are still type-coherent.
            let content = trimmed.to_string();
            let end = content.len();
            return vec![AttributedChunk {
                content,
                index: 0,
                spans: vec![TurnSpan {
                    attribution: Attribution::Unattributed,
                    timestamp: None,
                    byte_range: (0, end),
                }],
            }];
        }

        let mut chunks: Vec<AttributedChunk> = Vec::new();
        let mut idx = 0usize;
        let mut i = 0usize;
        while i < turns.len() {
            let curr = &turns[i];
            let next = turns.get(i + 1);
            let mut content = String::new();
            let mut spans: Vec<TurnSpan> = Vec::new();

            let append = |content: &mut String, spans: &mut Vec<TurnSpan>, t: &ParsedTurn| {
                if !content.is_empty() {
                    content.push_str("\n\n");
                }
                let start = content.len();
                content.push_str(&t.block);
                let end = content.len();
                spans.push(TurnSpan {
                    attribution: t.attribution,
                    timestamp: t.timestamp.clone(),
                    byte_range: (start, end),
                });
            };

            let step = if curr.attribution == Attribution::User
                && next.map(|n| n.attribution) == Some(Attribution::Assistant)
            {
                append(&mut content, &mut spans, curr);
                append(&mut content, &mut spans, next.unwrap());
                2
            } else {
                append(&mut content, &mut spans, curr);
                1
            };

            // Size cap: oversized chunks (e.g. user pasted a 30K-byte
            // code dump as one turn) throttle the embed pipeline
            // because the slot tokenises the whole input before
            // truncating at `max_input_tokens`. Split into sub-chunks
            // bounded by `MAX_CHUNK_CHARS`, preserving per-span
            // attribution by clipping each sub-chunk's spans to its
            // byte range.
            for sub in split_oversized(content, spans) {
                chunks.push(AttributedChunk {
                    content: sub.content,
                    index: idx,
                    spans: sub.spans,
                });
                idx += 1;
            }
            i += step;
        }
        chunks
    }
}

/// Helper: split a paired-turn chunk into one-or-more chunks each
/// ≤ `MAX_CHUNK_CHARS` (soft) / `MAX_HARD_CHARS` (hard). Returns the
/// content unchanged when the input is already small enough.
struct SplitChunk {
    content: String,
    spans: Vec<TurnSpan>,
}

fn split_oversized(content: String, spans: Vec<TurnSpan>) -> Vec<SplitChunk> {
    if content.len() <= MAX_CHUNK_CHARS {
        return vec![SplitChunk { content, spans }];
    }
    let mut out: Vec<SplitChunk> = Vec::new();
    let mut pos = 0usize;
    while pos < content.len() {
        let remaining = content.len() - pos;
        if remaining <= MAX_CHUNK_CHARS {
            let sub_content = content[pos..].to_string();
            let sub_spans = clip_spans(&spans, pos, content.len());
            out.push(SplitChunk {
                content: sub_content,
                spans: sub_spans,
            });
            break;
        }
        // Soft target: try to break on a blank line near MAX_CHUNK_CHARS.
        // Snap to a UTF-8 char boundary BEFORE any slicing — a naked
        // `pos + MAX_CHUNK_CHARS` can land inside an em-dash (3-byte
        // `—`) or any multi-byte glyph, and the subsequent `&content
        // [..soft_target]` slice panics. Real-world repro on an
        // anthropic export: byte 2979 fell inside `—` (2977..2980).
        let raw_soft = pos + MAX_CHUNK_CHARS;
        let soft_target = floor_char_boundary(&content, raw_soft);
        let mut end = next_soft_boundary(&content, soft_target).unwrap_or_else(|| {
            // Same boundary discipline on the hard fallback —
            // both targets are derived from byte arithmetic.
            let raw_hard = (soft_target + (MAX_HARD_CHARS - MAX_CHUNK_CHARS)).min(content.len());
            floor_char_boundary(&content, raw_hard)
        });
        // Don't loop forever if the splitter returned an end ≤ pos
        // (degenerate input — pos has no \n or boundary).
        if end <= pos {
            end = floor_char_boundary(
                &content,
                (soft_target + (MAX_HARD_CHARS - MAX_CHUNK_CHARS)).min(content.len()),
            );
        }
        let sub_content = content[pos..end].to_string();
        let sub_spans = clip_spans(&spans, pos, end);
        out.push(SplitChunk {
            content: sub_content,
            spans: sub_spans,
        });
        // Advance past the boundary, leaving a small overlap so a fact
        // straddling the cut survives in the next sub-chunk too.
        // Snap the rewound `next_pos` to a char boundary too — the
        // overlap is measured in bytes, so subtracting blindly can
        // again land mid-char.
        let raw_next = end.saturating_sub(SPLIT_OVERLAP_CHARS);
        let next_pos = floor_char_boundary(&content, raw_next);
        if next_pos <= pos {
            // Overlap window pulled us back to or before pos — force
            // forward progress at the hard boundary.
            pos = end;
        } else {
            pos = next_pos;
        }
    }
    out
}

/// Locate the next preferred break point at or after `target`,
/// preferring (a) a `"\n\n"` paragraph boundary, (b) a single
/// `'\n'`. Caps the search at `MAX_HARD_CHARS - SOFT` chars past
/// `target` so we don't drag the soft cap arbitrarily far.
///
/// Callers must pass a `target` that is already on a UTF-8 char
/// boundary; this function slices `&s[target..hard]` directly.
fn next_soft_boundary(s: &str, target: usize) -> Option<usize> {
    let raw_hard = (target + (MAX_HARD_CHARS - MAX_CHUNK_CHARS)).min(s.len());
    let hard = floor_char_boundary(s, raw_hard);
    if target >= hard {
        return None;
    }
    let slice = &s[target..hard];
    if let Some(rel) = slice.find("\n\n") {
        return Some(target + rel + 2);
    }
    if let Some(rel) = slice.find('\n') {
        return Some(target + rel + 1);
    }
    None
}

/// Project the parent chunk's spans onto a sub-chunk's byte range.
/// A span survives if it overlaps `[sub_start, sub_end)`; its byte
/// range is clipped to the overlap and rebased to sub-chunk
/// coordinates (`0..sub_end-sub_start`).
fn clip_spans(parent_spans: &[TurnSpan], sub_start: usize, sub_end: usize) -> Vec<TurnSpan> {
    let mut out: Vec<TurnSpan> = Vec::new();
    for s in parent_spans {
        let (a, b) = s.byte_range;
        let lo = a.max(sub_start);
        let hi = b.min(sub_end);
        if lo >= hi {
            continue;
        }
        out.push(TurnSpan {
            attribution: s.attribution,
            timestamp: s.timestamp.clone(),
            byte_range: (lo - sub_start, hi - sub_start),
        });
    }
    out
}

impl Default for ThreadedTurnsChunker {
    fn default() -> Self {
        Self::new()
    }
}

impl Chunker for ThreadedTurnsChunker {
    fn chunk(&self, text: &str) -> Vec<TextChunk> {
        self.chunk_attributed(text)
            .into_iter()
            .map(|c| TextChunk {
                content: c.content,
                index: c.index,
            })
            .collect()
    }
}

fn turn_header_regex() -> &'static Regex {
    static CELL: OnceLock<Regex> = OnceLock::new();
    // Matches `### [YYYY-MM-DD HH:MM] sender` or
    // `### [unknown-time] sender`. Captures: 1 = timestamp content
    // inside the brackets; 2 = sender slug.
    CELL.get_or_init(|| Regex::new(r"(?m)^###\s+\[([^\]]+)\]\s+(user|assistant)\s*$").unwrap())
}

#[derive(Debug)]
struct ParsedTurn {
    attribution: Attribution,
    timestamp: Option<String>,
    block: String,
}

fn parse_turns(text: &str) -> Vec<ParsedTurn> {
    let re = turn_header_regex();
    let captures: Vec<(usize, String, String)> = re
        .captures_iter(text)
        .map(|c| {
            let start = c.get(0).unwrap().start();
            let ts_raw = c.get(1).unwrap().as_str().to_string();
            let sender = c.get(2).unwrap().as_str().to_string();
            (start, ts_raw, sender)
        })
        .collect();

    if captures.is_empty() {
        return Vec::new();
    }

    let mut turns: Vec<ParsedTurn> = Vec::with_capacity(captures.len());
    for (i, (start, ts_raw, sender)) in captures.iter().enumerate() {
        let block_end = captures
            .get(i + 1)
            .map(|(s, _, _)| *s)
            .unwrap_or(text.len());
        let block = text[*start..block_end].trim_end().to_string();
        let attribution = match sender.as_str() {
            "user" => Attribution::User,
            "assistant" => Attribution::Assistant,
            _ => continue,
        };
        let timestamp = if ts_raw == "unknown-time" {
            None
        } else {
            Some(ts_raw.clone())
        };
        turns.push(ParsedTurn {
            attribution,
            timestamp,
            block,
        });
    }
    turns
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "### [2025-09-04 18:01] user\n\nWhat was our burn rate?\n\n### [2025-09-04 18:02] assistant\n\nAbout $312k last month.\n\n### [2025-09-04 18:10] user\n\nAnd runway?\n\n### [2025-09-04 18:11] assistant\n\n~14 months.";

    #[test]
    fn splits_into_two_pairs() {
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        assert_eq!(chunks.len(), 2);
    }

    #[test]
    fn first_pair_contains_question_and_answer() {
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        let first = &chunks[0].content;
        assert!(first.contains("burn rate"));
        assert!(first.contains("$312k"));
        assert!(first.contains("### [2025-09-04 18:01] user"));
        assert!(first.contains("### [2025-09-04 18:02] assistant"));
    }

    #[test]
    fn preserves_turn_headers_in_chunk_content() {
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        for chunk in &chunks {
            assert!(
                chunk.content.contains("### ["),
                "header missing from chunk: {}",
                chunk.content
            );
        }
    }

    #[test]
    fn dangling_user_emitted_alone() {
        let input = "### [2025-09-04 18:01] user\n\nQuestion with no reply.";
        let chunks = ThreadedTurnsChunker::new().chunk(input);
        assert_eq!(chunks.len(), 1);
        assert!(chunks[0].content.contains("Question with no reply"));
    }

    #[test]
    fn assistant_without_preceding_user_emitted_alone() {
        let input = "### [2025-09-04 18:01] assistant\n\nUnsolicited opener.\n\n### [2025-09-04 18:02] user\n\nQ\n\n### [2025-09-04 18:03] assistant\n\nA";
        let chunks = ThreadedTurnsChunker::new().chunk(input);
        assert_eq!(chunks.len(), 2);
        assert!(chunks[0].content.contains("Unsolicited"));
        assert!(chunks[1].content.contains("Q"));
        assert!(chunks[1].content.contains("A"));
    }

    #[test]
    fn empty_input_yields_no_chunks() {
        let chunks = ThreadedTurnsChunker::new().chunk("");
        assert!(chunks.is_empty());
    }

    #[test]
    fn text_without_turn_headers_degrades_to_single_chunk() {
        let chunks = ThreadedTurnsChunker::new().chunk("Just some prose with no turn markers.");
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].content, "Just some prose with no turn markers.");
    }

    #[test]
    fn indices_increment_sequentially() {
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        for (i, c) in chunks.iter().enumerate() {
            assert_eq!(c.index, i);
        }
    }

    // ─── Attribution-surface tests ─────────────────────────────────

    #[test]
    fn attributed_pair_has_two_spans_user_then_assistant() {
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(SAMPLE);
        assert_eq!(chunks.len(), 2);
        assert_eq!(chunks[0].spans.len(), 2);
        assert_eq!(chunks[0].spans[0].attribution, Attribution::User);
        assert_eq!(chunks[0].spans[1].attribution, Attribution::Assistant);
    }

    #[test]
    fn span_byte_ranges_slice_back_to_correct_authorship() {
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(SAMPLE);
        let first = &chunks[0];
        let user_span = &first.spans[0];
        let assistant_span = &first.spans[1];
        let user_text = &first.content[user_span.byte_range.0..user_span.byte_range.1];
        let asst_text = &first.content[assistant_span.byte_range.0..assistant_span.byte_range.1];
        assert!(user_text.contains("burn rate"));
        assert!(
            !user_text.contains("$312k"),
            "user span leaked assistant text: {}",
            user_text
        );
        assert!(asst_text.contains("$312k"));
        assert!(
            !asst_text.contains("burn rate"),
            "assistant span leaked user text: {}",
            asst_text
        );
    }

    #[test]
    fn span_timestamps_parsed() {
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(SAMPLE);
        let first = &chunks[0];
        assert_eq!(
            first.spans[0].timestamp.as_deref(),
            Some("2025-09-04 18:01")
        );
        assert_eq!(
            first.spans[1].timestamp.as_deref(),
            Some("2025-09-04 18:02")
        );
    }

    #[test]
    fn unknown_time_yields_none_timestamp() {
        let input = "### [unknown-time] user\n\nQ\n\n### [unknown-time] assistant\n\nA";
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(input);
        assert_eq!(chunks[0].spans[0].timestamp, None);
        assert_eq!(chunks[0].spans[1].timestamp, None);
    }

    #[test]
    fn dangling_user_span_marked_user() {
        let input = "### [2025-09-04 18:01] user\n\nNo reply here.";
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(input);
        assert_eq!(chunks[0].spans.len(), 1);
        assert_eq!(chunks[0].spans[0].attribution, Attribution::User);
    }

    #[test]
    fn non_marker_text_falls_back_to_unattributed_span() {
        let chunks =
            ThreadedTurnsChunker::new().chunk_attributed("Free prose with no turn markers.");
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].spans.len(), 1);
        assert_eq!(chunks[0].spans[0].attribution, Attribution::Unattributed);
    }

    #[test]
    fn attribution_slug_round_trips() {
        assert_eq!(Attribution::User.slug(), "user");
        assert_eq!(Attribution::Assistant.slug(), "assistant");
        assert_eq!(Attribution::Unattributed.slug(), "unattributed");
        assert_eq!(Attribution::Pasted.slug(), "pasted");
    }

    #[test]
    fn end_to_end_extractor_to_chunker_with_attribution() {
        use crate::error::Result;
        use crate::extractors::anthropic_export::AnthropicExportExtractor;
        use crate::extractors::Extractor;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("conversations.json");
        let raw = r#"[{
            "uuid": "c1", "name": "Test", "summary": "", "created_at": "2025-09-04T18:00:00Z",
            "chat_messages": [
              {"sender": "human", "created_at": "2025-09-04T18:01:00Z", "content":[{"type":"text","text":"Q1"}]},
              {"sender": "assistant", "created_at": "2025-09-04T18:02:00Z", "content":[{"type":"text","text":"A1"}]},
              {"sender": "human", "created_at": "2025-09-04T18:10:00Z", "content":[{"type":"text","text":"Q2"}]},
              {"sender": "assistant", "created_at": "2025-09-04T18:11:00Z", "content":[{"type":"text","text":"A2"}]}
            ]
        }]"#;
        std::fs::write(&path, raw).unwrap();

        let docs: Vec<_> = AnthropicExportExtractor::new()
            .extract(&path)
            .unwrap()
            .collect::<Result<Vec<_>>>()
            .unwrap();
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(&docs[0].content);
        assert_eq!(chunks.len(), 2);
        for chunk in &chunks {
            assert_eq!(chunk.spans.len(), 2);
            assert_eq!(chunk.spans[0].attribution, Attribution::User);
            assert_eq!(chunk.spans[1].attribution, Attribution::Assistant);
            assert!(chunk.spans[0].timestamp.is_some());
            assert!(chunk.spans[1].timestamp.is_some());
        }
    }

    // ─── Size-cap tests ───────────────────────────────────────────
    //
    // Pin the throughput-protecting cap. Pre-cap, a real claude.ai
    // export with one ~30K-byte user paste throttled embed batches
    // to 1.2 seqs/sec because every chunk was tokenised fully
    // before the slot truncated it. These tests guard the cap and
    // its attribution-preserving span clipping.

    #[test]
    fn oversized_paired_turn_splits_into_multiple_chunks() {
        // ~5 KB user prose + ~5 KB assistant prose forces a paired
        // chunk well past the 1500-char soft cap.
        let user_body = "A line of conversation. ".repeat(220);
        let assistant_body = "A line of reply. ".repeat(300);
        let input = format!(
            "### [2025-09-04 18:01] user\n\n{user_body}\n\n### [2025-09-04 18:02] assistant\n\n{assistant_body}"
        );
        let chunks = ThreadedTurnsChunker::new().chunk(&input);
        assert!(
            chunks.len() > 1,
            "oversized paired turn must split into multiple chunks (got {})",
            chunks.len()
        );
        for c in &chunks {
            assert!(
                c.content.len() <= MAX_HARD_CHARS,
                "split chunk overshot hard cap ({} > {}): {:?}",
                c.content.len(),
                MAX_HARD_CHARS,
                &c.content[..c.content.len().min(120)],
            );
        }
    }

    #[test]
    fn small_paired_turn_is_not_split() {
        // SAMPLE is well under the cap — splitter must be a no-op.
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        assert_eq!(chunks.len(), 2, "small pairs should not split");
    }

    #[test]
    fn split_subchunks_preserve_attribution_spans() {
        let user_body = "User says: ".to_string() + &"foo bar baz ".repeat(200);
        let assistant_body = "Reply: ".to_string() + &"qux quux corge ".repeat(200);
        let input = format!(
            "### [2025-09-04 18:01] user\n\n{user_body}\n\n### [2025-09-04 18:02] assistant\n\n{assistant_body}"
        );
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(&input);
        assert!(chunks.len() > 1);
        for chunk in &chunks {
            // Each sub-chunk must carry at least one span — span
            // clipping is the load-bearing detail that keeps
            // attribution coherent across the split.
            assert!(
                !chunk.spans.is_empty(),
                "sub-chunk lost all attribution spans: {:?}",
                &chunk.content[..chunk.content.len().min(120)]
            );
            // Every span's byte range must be in-bounds of the
            // sub-chunk's content.
            for s in &chunk.spans {
                let (a, b) = s.byte_range;
                assert!(a <= b, "span byte_range inverted: {a:?}..{b:?}");
                assert!(
                    b <= chunk.content.len(),
                    "span byte_range overshoots sub-chunk content (end {} > len {})",
                    b,
                    chunk.content.len(),
                );
            }
        }
    }

    #[test]
    fn split_indices_remain_sequential() {
        let big = "lorem ipsum dolor sit amet ".repeat(400);
        let input = format!(
            "### [2025-09-04 18:01] user\n\n{big}\n\n### [2025-09-04 18:02] assistant\n\nshort reply"
        );
        let chunks = ThreadedTurnsChunker::new().chunk(&input);
        for (i, c) in chunks.iter().enumerate() {
            assert_eq!(c.index, i);
        }
    }

    #[test]
    fn split_handles_oversize_without_newlines() {
        // A blob with no newlines (worst case for the soft boundary
        // pass) must still split cleanly via the hard char-boundary.
        let blob = "x".repeat(6000);
        let input = format!(
            "### [2025-09-04 18:01] user\n\n{blob}\n\n### [2025-09-04 18:02] assistant\n\ny"
        );
        let chunks = ThreadedTurnsChunker::new().chunk(&input);
        assert!(chunks.len() > 1);
        for c in &chunks {
            assert!(c.content.len() <= MAX_HARD_CHARS);
        }
    }

    /// Pinned regression: the first real anthropic-export ingest
    /// panicked with `byte index 2979 is not a char boundary; it is
    /// inside '—' (bytes 2977..2980)`. Root cause was
    /// `pos + MAX_CHUNK_CHARS` landing inside the em-dash on the
    /// second loop iteration, then a `&content[target..hard]` slice
    /// panicking via `slice_error_fail`. Every position the splitter
    /// derives from byte arithmetic must now snap to a UTF-8 char
    /// boundary first (`floor_char_boundary`); this test enforces
    /// that by stuffing the input with em-dashes so the soft target
    /// + overlap rewind both stand a good chance of landing
    /// mid-glyph.
    #[test]
    fn split_handles_multibyte_glyph_on_soft_target() {
        // Body crafted so the byte position ~MAX_CHUNK_CHARS into
        // each turn lands inside a multi-byte char.
        let multibyte_run = "Let's dig in — there's an em-dash every line.\n".repeat(80);
        let extra = "—".repeat(400); // pure 3-byte chars
        let input = format!(
            "### [2026-03-28 20:20] user\n\n{multibyte_run}{extra}\n\n### [2026-03-28 20:21] assistant\n\nReply with more — and more —.\n"
        );
        // Pre-fix this panicked with `slice_error_fail` inside the
        // chunker; post-fix it must complete + every chunk must
        // round-trip as valid UTF-8.
        let chunks = ThreadedTurnsChunker::new().chunk(&input);
        assert!(
            chunks.len() > 1,
            "input must split: got {} chunks",
            chunks.len()
        );
        for c in &chunks {
            assert!(c.content.is_char_boundary(0));
            assert!(c.content.is_char_boundary(c.content.len()));
            assert!(
                c.content.len() <= MAX_HARD_CHARS,
                "chunk overshot hard cap: {} > {}",
                c.content.len(),
                MAX_HARD_CHARS
            );
            // is_char_boundary returns true on every valid UTF-8
            // index — confirm by re-parsing the &str.
            let _ = c.content.as_str();
        }
    }

    /// Stronger fuzz: a wall of em-dashes with no newlines forces
    /// the soft-boundary search to fail every time, exercising the
    /// hard-boundary fallback in a path full of multi-byte chars.
    #[test]
    fn split_handles_pure_multibyte_blob() {
        let blob = "—".repeat(3000); // 9000 bytes of 3-byte glyphs
        let input = format!(
            "### [2025-09-04 18:01] user\n\n{blob}\n\n### [2025-09-04 18:02] assistant\n\nack"
        );
        let chunks = ThreadedTurnsChunker::new().chunk(&input);
        assert!(chunks.len() > 1);
        for c in &chunks {
            assert!(c.content.len() <= MAX_HARD_CHARS);
            // All chars survived round-trip.
            for ch in c.content.chars() {
                let _ = ch;
            }
        }
    }
}
