//! Threaded-turn chunker for chat-transcript content.
//!
//! Reads the turn-block format emitted by `AnthropicExportExtractor`:
//!
//! ```text
//! ### [2025-09-04 18:01] user
//!
//! What was our burn rate last month?
//!
//! ### [2025-09-04 18:02] assistant
//!
//! Based on the bank statement you shared, burn was $312k.
//! ```
//!
//! Groups each `user` turn with the immediately-following `assistant`
//! reply into one chunk. A dangling `user` turn (no reply) or a
//! leading `assistant` turn (no preceding user — rare in claude.ai
//! exports) becomes a standalone chunk.
//!
//! ## Attribution
//!
//! Conversation history and inner-work journaling are corpora where
//! "who wrote this span?" is load-bearing — searching for "what did
//! *I* decide about X" must not return spans authored by the model,
//! and vice versa. The chunker therefore emits a parallel
//! `AttributedChunk` surface alongside the plain `TextChunk`:
//!
//! - `Chunker::chunk` returns `Vec<TextChunk>` for pipeline
//!   compatibility (embedding, FTS index, default retrieval).
//! - `chunk_attributed` returns `Vec<AttributedChunk>`, where each
//!   chunk carries `spans: Vec<TurnSpan>` listing the byte ranges
//!   inside the chunk content that came from each author.
//!
//! Downstream code that cares about authorship (atlas extraction,
//! filtered retrieval, bench scoring) consumes `chunk_attributed`;
//! everything else stays on the plain surface.
//!
//! ### Attribution enum scope
//!
//! Today the variants are `User` and `Assistant`. The enum reserves
//! `Unattributed` and `Pasted` for the inner-work journaling ingest
//! (a separate extractor): journals contain free-form prose (no
//! marker), and sometimes spans the user has pasted in from a model
//! elsewhere — authorship is the user, underlying generation is the
//! model, retrieval may want to weight that differently. Defining
//! the variants here keeps a single `Attribution` type across both
//! corpora so retrieval and bench code does not branch on corpus
//! type.

use regex::Regex;
use std::sync::OnceLock;

use super::{Chunker, TextChunk};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Attribution {
    User,
    Assistant,
    /// Free-form prose with no explicit sender — reserved for the
    /// inner-work journaling ingest. Not emitted by this chunker.
    Unattributed,
    /// Text the user pasted from a model elsewhere; claimed author
    /// is the user, generated by a model. Reserved for inner-work
    /// journaling ingest. Not emitted by this chunker.
    Pasted,
}

impl Attribution {
    pub fn slug(self) -> &'static str {
        match self {
            Attribution::User => "user",
            Attribution::Assistant => "assistant",
            Attribution::Unattributed => "unattributed",
            Attribution::Pasted => "pasted",
        }
    }
}

#[derive(Debug, Clone)]
pub struct TurnSpan {
    pub attribution: Attribution,
    /// `YYYY-MM-DD HH:MM` shape if the source had a timestamp, else
    /// `None`. Inner-work journaling spans without timestamps will
    /// pass `None`.
    pub timestamp: Option<String>,
    /// Byte offsets inside the parent chunk's `content` string. Half-
    /// open: `[start, end)`. Always falls on UTF-8 char boundaries
    /// because the chunker only ever concatenates whole turn blocks.
    pub byte_range: (usize, usize),
}

#[derive(Debug, Clone)]
pub struct AttributedChunk {
    pub content: String,
    pub index: usize,
    pub spans: Vec<TurnSpan>,
}

pub struct ThreadedTurnsChunker;

impl ThreadedTurnsChunker {
    pub fn new() -> Self {
        Self
    }

    /// Chunk with per-span attribution. Each returned chunk has a
    /// `spans` vector — typically two entries (user + assistant), or
    /// one for a dangling turn.
    pub fn chunk_attributed(&self, text: &str) -> Vec<AttributedChunk> {
        let turns = parse_turns(text);
        if turns.is_empty() {
            let trimmed = text.trim();
            if trimmed.is_empty() {
                return Vec::new();
            }
            // Degrade: whole-text chunk with no attribution markers.
            // Caller using this chunker on non-conversation content
            // gets a single Unattributed span so authorship surfaces
            // are still type-coherent.
            let content = trimmed.to_string();
            let end = content.len();
            return vec![AttributedChunk {
                content,
                index: 0,
                spans: vec![TurnSpan {
                    attribution: Attribution::Unattributed,
                    timestamp: None,
                    byte_range: (0, end),
                }],
            }];
        }

        let mut chunks: Vec<AttributedChunk> = Vec::new();
        let mut idx = 0usize;
        let mut i = 0usize;
        while i < turns.len() {
            let curr = &turns[i];
            let next = turns.get(i + 1);
            let step;
            let mut content = String::new();
            let mut spans: Vec<TurnSpan> = Vec::new();

            let append = |content: &mut String, spans: &mut Vec<TurnSpan>, t: &ParsedTurn| {
                if !content.is_empty() {
                    content.push_str("\n\n");
                }
                let start = content.len();
                content.push_str(&t.block);
                let end = content.len();
                spans.push(TurnSpan {
                    attribution: t.attribution,
                    timestamp: t.timestamp.clone(),
                    byte_range: (start, end),
                });
            };

            if curr.attribution == Attribution::User
                && next.map(|n| n.attribution) == Some(Attribution::Assistant)
            {
                append(&mut content, &mut spans, curr);
                append(&mut content, &mut spans, next.unwrap());
                step = 2;
            } else {
                append(&mut content, &mut spans, curr);
                step = 1;
            }

            chunks.push(AttributedChunk {
                content,
                index: idx,
                spans,
            });
            idx += 1;
            i += step;
        }
        chunks
    }
}

impl Default for ThreadedTurnsChunker {
    fn default() -> Self {
        Self::new()
    }
}

impl Chunker for ThreadedTurnsChunker {
    fn chunk(&self, text: &str) -> Vec<TextChunk> {
        self.chunk_attributed(text)
            .into_iter()
            .map(|c| TextChunk {
                content: c.content,
                index: c.index,
            })
            .collect()
    }
}

fn turn_header_regex() -> &'static Regex {
    static CELL: OnceLock<Regex> = OnceLock::new();
    // Matches `### [YYYY-MM-DD HH:MM] sender` or
    // `### [unknown-time] sender`. Captures: 1 = timestamp content
    // inside the brackets; 2 = sender slug.
    CELL.get_or_init(|| {
        Regex::new(r"(?m)^###\s+\[([^\]]+)\]\s+(user|assistant)\s*$").unwrap()
    })
}

#[derive(Debug)]
struct ParsedTurn {
    attribution: Attribution,
    timestamp: Option<String>,
    block: String,
}

fn parse_turns(text: &str) -> Vec<ParsedTurn> {
    let re = turn_header_regex();
    let captures: Vec<(usize, String, String)> = re
        .captures_iter(text)
        .map(|c| {
            let start = c.get(0).unwrap().start();
            let ts_raw = c.get(1).unwrap().as_str().to_string();
            let sender = c.get(2).unwrap().as_str().to_string();
            (start, ts_raw, sender)
        })
        .collect();

    if captures.is_empty() {
        return Vec::new();
    }

    let mut turns: Vec<ParsedTurn> = Vec::with_capacity(captures.len());
    for (i, (start, ts_raw, sender)) in captures.iter().enumerate() {
        let block_end = captures
            .get(i + 1)
            .map(|(s, _, _)| *s)
            .unwrap_or(text.len());
        let block = text[*start..block_end].trim_end().to_string();
        let attribution = match sender.as_str() {
            "user" => Attribution::User,
            "assistant" => Attribution::Assistant,
            _ => continue,
        };
        let timestamp = if ts_raw == "unknown-time" {
            None
        } else {
            Some(ts_raw.clone())
        };
        turns.push(ParsedTurn {
            attribution,
            timestamp,
            block,
        });
    }
    turns
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "### [2025-09-04 18:01] user\n\nWhat was our burn rate?\n\n### [2025-09-04 18:02] assistant\n\nAbout $312k last month.\n\n### [2025-09-04 18:10] user\n\nAnd runway?\n\n### [2025-09-04 18:11] assistant\n\n~14 months.";

    #[test]
    fn splits_into_two_pairs() {
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        assert_eq!(chunks.len(), 2);
    }

    #[test]
    fn first_pair_contains_question_and_answer() {
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        let first = &chunks[0].content;
        assert!(first.contains("burn rate"));
        assert!(first.contains("$312k"));
        assert!(first.contains("### [2025-09-04 18:01] user"));
        assert!(first.contains("### [2025-09-04 18:02] assistant"));
    }

    #[test]
    fn preserves_turn_headers_in_chunk_content() {
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        for chunk in &chunks {
            assert!(
                chunk.content.contains("### ["),
                "header missing from chunk: {}",
                chunk.content
            );
        }
    }

    #[test]
    fn dangling_user_emitted_alone() {
        let input = "### [2025-09-04 18:01] user\n\nQuestion with no reply.";
        let chunks = ThreadedTurnsChunker::new().chunk(input);
        assert_eq!(chunks.len(), 1);
        assert!(chunks[0].content.contains("Question with no reply"));
    }

    #[test]
    fn assistant_without_preceding_user_emitted_alone() {
        let input = "### [2025-09-04 18:01] assistant\n\nUnsolicited opener.\n\n### [2025-09-04 18:02] user\n\nQ\n\n### [2025-09-04 18:03] assistant\n\nA";
        let chunks = ThreadedTurnsChunker::new().chunk(input);
        assert_eq!(chunks.len(), 2);
        assert!(chunks[0].content.contains("Unsolicited"));
        assert!(chunks[1].content.contains("Q"));
        assert!(chunks[1].content.contains("A"));
    }

    #[test]
    fn empty_input_yields_no_chunks() {
        let chunks = ThreadedTurnsChunker::new().chunk("");
        assert!(chunks.is_empty());
    }

    #[test]
    fn text_without_turn_headers_degrades_to_single_chunk() {
        let chunks = ThreadedTurnsChunker::new().chunk("Just some prose with no turn markers.");
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].content, "Just some prose with no turn markers.");
    }

    #[test]
    fn indices_increment_sequentially() {
        let chunks = ThreadedTurnsChunker::new().chunk(SAMPLE);
        for (i, c) in chunks.iter().enumerate() {
            assert_eq!(c.index, i);
        }
    }

    // ─── Attribution-surface tests ─────────────────────────────────

    #[test]
    fn attributed_pair_has_two_spans_user_then_assistant() {
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(SAMPLE);
        assert_eq!(chunks.len(), 2);
        assert_eq!(chunks[0].spans.len(), 2);
        assert_eq!(chunks[0].spans[0].attribution, Attribution::User);
        assert_eq!(chunks[0].spans[1].attribution, Attribution::Assistant);
    }

    #[test]
    fn span_byte_ranges_slice_back_to_correct_authorship() {
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(SAMPLE);
        let first = &chunks[0];
        let user_span = &first.spans[0];
        let assistant_span = &first.spans[1];
        let user_text = &first.content[user_span.byte_range.0..user_span.byte_range.1];
        let asst_text =
            &first.content[assistant_span.byte_range.0..assistant_span.byte_range.1];
        assert!(user_text.contains("burn rate"));
        assert!(!user_text.contains("$312k"), "user span leaked assistant text: {}", user_text);
        assert!(asst_text.contains("$312k"));
        assert!(
            !asst_text.contains("burn rate"),
            "assistant span leaked user text: {}",
            asst_text
        );
    }

    #[test]
    fn span_timestamps_parsed() {
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(SAMPLE);
        let first = &chunks[0];
        assert_eq!(first.spans[0].timestamp.as_deref(), Some("2025-09-04 18:01"));
        assert_eq!(first.spans[1].timestamp.as_deref(), Some("2025-09-04 18:02"));
    }

    #[test]
    fn unknown_time_yields_none_timestamp() {
        let input = "### [unknown-time] user\n\nQ\n\n### [unknown-time] assistant\n\nA";
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(input);
        assert_eq!(chunks[0].spans[0].timestamp, None);
        assert_eq!(chunks[0].spans[1].timestamp, None);
    }

    #[test]
    fn dangling_user_span_marked_user() {
        let input = "### [2025-09-04 18:01] user\n\nNo reply here.";
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(input);
        assert_eq!(chunks[0].spans.len(), 1);
        assert_eq!(chunks[0].spans[0].attribution, Attribution::User);
    }

    #[test]
    fn non_marker_text_falls_back_to_unattributed_span() {
        let chunks = ThreadedTurnsChunker::new()
            .chunk_attributed("Free prose with no turn markers.");
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].spans.len(), 1);
        assert_eq!(chunks[0].spans[0].attribution, Attribution::Unattributed);
    }

    #[test]
    fn attribution_slug_round_trips() {
        assert_eq!(Attribution::User.slug(), "user");
        assert_eq!(Attribution::Assistant.slug(), "assistant");
        assert_eq!(Attribution::Unattributed.slug(), "unattributed");
        assert_eq!(Attribution::Pasted.slug(), "pasted");
    }

    #[test]
    fn end_to_end_extractor_to_chunker_with_attribution() {
        use crate::error::Result;
        use crate::extractors::anthropic_export::AnthropicExportExtractor;
        use crate::extractors::Extractor;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("conversations.json");
        let raw = r#"[{
            "uuid": "c1", "name": "Test", "summary": "", "created_at": "2025-09-04T18:00:00Z",
            "chat_messages": [
              {"sender": "human", "created_at": "2025-09-04T18:01:00Z", "content":[{"type":"text","text":"Q1"}]},
              {"sender": "assistant", "created_at": "2025-09-04T18:02:00Z", "content":[{"type":"text","text":"A1"}]},
              {"sender": "human", "created_at": "2025-09-04T18:10:00Z", "content":[{"type":"text","text":"Q2"}]},
              {"sender": "assistant", "created_at": "2025-09-04T18:11:00Z", "content":[{"type":"text","text":"A2"}]}
            ]
        }]"#;
        std::fs::write(&path, raw).unwrap();

        let docs: Vec<_> = AnthropicExportExtractor::new()
            .extract(&path)
            .unwrap()
            .collect::<Result<Vec<_>>>()
            .unwrap();
        let chunks = ThreadedTurnsChunker::new().chunk_attributed(&docs[0].content);
        assert_eq!(chunks.len(), 2);
        for chunk in &chunks {
            assert_eq!(chunk.spans.len(), 2);
            assert_eq!(chunk.spans[0].attribution, Attribution::User);
            assert_eq!(chunk.spans[1].attribution, Attribution::Assistant);
            assert!(chunk.spans[0].timestamp.is_some());
            assert!(chunk.spans[1].timestamp.is_some());
        }
    }
}
