//! `sovereign code` subcommand — Code Intelligence v1 Phase 1.
//!
//! Ships two commands in v1:
//!
//!   sovereign code index <path> [--corpus-id <id>]
//!       Walks a local repository with tree-sitter, produces one chunk per
//!       symbol, and writes a LanceDB index under
//!       `~/.sovereign/indexes/{corpus_id}/`. Uses a zero-vector `EmbedFn`
//!       today — symbol lookup works via metadata filter pushdown (the
//!       P1 primary use case) but semantic search requires Phase 2 tools
//!       that wire in a real embedding model.
//!
//!   sovereign code search <query>
//!       Phase-2 placeholder. Prints a friendly message explaining which
//!       tools land in P2.
//!
//! This command does not load a full inference model — it reuses the same
//! zero-vector strategy as `recipe test` so `sovereign code index` stays
//! lightweight and can run against huge repos without GPU memory.

use std::path::PathBuf;
use std::sync::Arc;

use corpus_engine::{CorpusEngine, CorpusSpec, EmbedFn};

/// Run a `code` subcommand. Returns the exit code.
pub async fn run_code(args: &[String]) -> i32 {
    if args.is_empty() {
        print_usage();
        return 1;
    }

    match args[0].as_str() {
        "index" => cmd_index(&args[1..]).await,
        "search" => cmd_search(&args[1..]).await,
        "help" | "--help" | "-h" => {
            print_usage();
            0
        }
        other => {
            eprintln!("Unknown code subcommand: {other}");
            print_usage();
            1
        }
    }
}

fn print_usage() {
    eprintln!(
        "Usage: sovereign code <command>

Commands:
  index <path>        Index a local repository with tree-sitter (Phase 1)
    --corpus-id <id>  Corpus identifier (default: basename of <path>)
    --data-dir <dir>  Index directory (default: ~/.sovereign/indexes)

  search <query>      Semantic search over indexed code (lands in Phase 2)
  help                Show this help

Code Intelligence v1 is phased:
  P1 (now)  — corpus indexing via this command
  P2 (next) — three tools usable from Sovereign chat
  P3        — filesystem watcher (incremental reindex on save)
  P4        — MCP HTTP server (Claude Code / Cursor integration)"
    );
}

// ─── index ────────────────────────────────────────────────────

async fn cmd_index(args: &[String]) -> i32 {
    let mut path_arg: Option<PathBuf> = None;
    let mut corpus_id: Option<String> = None;
    let mut data_dir: Option<PathBuf> = None;

    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--corpus-id" => {
                i += 1;
                corpus_id = args.get(i).cloned();
                if corpus_id.is_none() {
                    eprintln!("error: --corpus-id requires a value");
                    return 1;
                }
            }
            "--data-dir" => {
                i += 1;
                data_dir = args.get(i).map(PathBuf::from);
                if data_dir.is_none() {
                    eprintln!("error: --data-dir requires a value");
                    return 1;
                }
            }
            flag if flag.starts_with('-') => {
                eprintln!("warning: unknown flag '{flag}' — ignored");
            }
            p => {
                path_arg = Some(PathBuf::from(p));
            }
        }
        i += 1;
    }

    let Some(path) = path_arg else {
        eprintln!("error: missing <path>");
        print_usage();
        return 1;
    };

    let abs_path = match path.canonicalize() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("error: cannot resolve path {}: {e}", path.display());
            return 1;
        }
    };

    let corpus_id = corpus_id.unwrap_or_else(|| {
        abs_path
            .file_name()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_else(|| "codebase".to_string())
    });

    let data_dir = data_dir
        .or_else(|| default_data_dir())
        .unwrap_or_else(|| PathBuf::from("./sovereign-indexes"));

    if let Err(e) = std::fs::create_dir_all(&data_dir) {
        eprintln!("error: cannot create data dir {}: {e}", data_dir.display());
        return 1;
    }

    // Build an ephemeral recipe TOML with the supplied path and corpus_id.
    // This is simpler than adding a programmatic Recipe constructor —
    // ingest already knows how to handle a RecipePath.
    let recipe_toml = format!(
        r#"[corpus]
id = "{corpus_id}"
name = "{corpus_id}"
description = "Local code corpus generated by `sovereign code index`"
license = "private"
mesh_sharing = false
size_compressed_gb = 0
size_indexed_gb = 0

[acquire]
type = "local_file"
path = "{path}"

[extract]
type = "code"
context_lines = 3
max_lines_per_chunk = 150

[chunk]
type = "passthrough"

# Vector ANN is intentionally disabled in P1: we use zero embeddings so
# IVF-PQ training would fail (KMeans cannot find 45 centroids in 0-variance
# data). Phase 2 wires in a real embed model and re-enables this.
# Metadata filter pushdown (symbol_name, file_path, mtime) still works with
# `vector = false` because it's a direct column scan, not an ANN lookup.
[index]
fts = true
vector = false
"#,
        corpus_id = corpus_id,
        path = abs_path.display(),
    );

    let tempdir = match tempfile_dir() {
        Ok(d) => d,
        Err(e) => {
            eprintln!("error: cannot create temp dir: {e}");
            return 1;
        }
    };
    let recipe_path = tempdir.join(format!("{corpus_id}.toml"));
    if let Err(e) = std::fs::write(&recipe_path, recipe_toml) {
        eprintln!("error: cannot write ephemeral recipe: {e}");
        return 1;
    }

    // Zero-vector EmbedFn — sufficient for P1 (symbol lookup via metadata
    // filter pushdown is the primary use case). Phase 2 wires in a real
    // embedding model for semantic search.
    let embed: EmbedFn = Arc::new(|_text: &str| {
        Box::pin(async { Ok::<Vec<f32>, corpus_engine::Error>(vec![0.0; 768]) })
    });
    let recipes_dir = tempdir.clone();
    let engine = CorpusEngine::new(recipes_dir, data_dir.clone(), embed);

    eprintln!("Indexing {} as corpus '{corpus_id}'", abs_path.display());
    eprintln!("Index directory: {}", data_dir.display());
    eprintln!();

    let spec = CorpusSpec::RecipePath(recipe_path);
    match engine.ingest(&spec, None).await {
        Ok(result) => {
            eprintln!();
            eprintln!(
                "✓ Indexed {} chunks in {}s",
                result.chunks_created, result.duration_secs
            );
            eprintln!(
                "  Corpus: {}  ({} KB on disk)",
                result.corpus_id,
                result.index_size_bytes / 1024,
            );
            eprintln!("  Location: {}/{}", data_dir.display(), result.corpus_id);
            0
        }
        Err(e) => {
            eprintln!();
            eprintln!("✗ Indexing failed: {e}");
            1
        }
    }
}

// ─── search (P2 placeholder) ──────────────────────────────────

async fn cmd_search(args: &[String]) -> i32 {
    let query = args.join(" ");
    eprintln!(
        "`sovereign code search` ships in Code Intelligence Phase 2.\n\n\
         Phase 2 adds three Sovereign tools wired to the corpus you indexed:\n\
           symbol_lookup  — exact symbol name → file:line (always correct)\n\
           code_search    — semantic search (approximate, labelled as such)\n\
           recent_changes — files modified within the last N hours\n\n\
         In the meantime, index with `sovereign code index <path>` — the\n\
         on-disk LanceDB table is already populated and queryable from\n\
         tools that open it directly.\n\n\
         Your query: {query}"
    );
    0
}

// ─── helpers ──────────────────────────────────────────────────

fn default_data_dir() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".sovereign").join("indexes"))
}

fn tempfile_dir() -> std::io::Result<PathBuf> {
    // Avoid pulling in the `tempfile` crate — sovereign-cli doesn't
    // already use it, and a one-shot per-run dir is enough. Use the
    // system temp dir plus a pid-derived suffix for uniqueness.
    let base = std::env::temp_dir();
    let suffix = format!("sovereign-code-{}", std::process::id());
    let path = base.join(suffix);
    std::fs::create_dir_all(&path)?;
    Ok(path)
}

