// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by `cargo test -p sovereign-desktop --test command_surface`.
// DO NOT EDIT BY HAND. Regenerate after changing the `#[tauri::command]`
// surface:
//
//   UPDATE_DESKTOP_COMMANDS=1 cargo test -p sovereign-desktop --test command_surface
//
// Argument VALUES are `unknown` on purpose: this pins the command names and
// the argument KEYS, which is what the string-addressed bridge gets wrong.
// Value types would need every DTO mirrored in TS and are a separate job.

export interface CommandArgs {
  ask_document: {
    assetId: unknown;
    question: unknown;
    conversationId: unknown;
  };
  atlas_check_gliner_model: Record<string, never>;
  atlas_download_gliner_model: {
    modelId?: unknown;
  };
  atlas_get_atom_detail: {
    corpusId: unknown;
    atomId: unknown;
  };
  atlas_get_chunk_entity_progress: {
    corpusId: unknown;
  };
  atlas_get_conv_detail: {
    corpusId: unknown;
    convUuid: unknown;
  };
  atlas_get_conv_entities: {
    corpusId: unknown;
    convUuid: unknown;
  };
  atlas_get_entity_aggregate: {
    corpusId: unknown;
    text: unknown;
  };
  atlas_list_atoms: {
    corpusId: unknown;
    filter?: unknown;
    page?: unknown;
  };
  atlas_list_conv_corpora: Record<string, never>;
  atlas_list_conversations: {
    corpusId: unknown;
    filter?: unknown;
    offset?: unknown;
  };
  atlas_list_corpora: Record<string, never>;
  atlas_list_members: {
    corpusId: unknown;
  };
  atlas_subgraph: {
    corpusId: unknown;
    maxNodes?: unknown;
  };
  attach_restart_daemon: Record<string, never>;
  build_corpus_index: {
    corpusId: unknown;
  };
  cancel_stream: {
    conversationId: unknown;
  };
  check_for_update: Record<string, never>;
  clip_insight: {
    clippedText: unknown;
    messageId: unknown;
    paragraphIndex: unknown;
    sourceJson: unknown;
    positionJson?: unknown;
  };
  complete_setup: {
    setup: unknown;
  };
  complete_setup_auto: {
    primaryFile?: unknown;
    primarySource?: unknown;
  };
  corpus_coverage_card: {
    corpusId: unknown;
  };
  corpus_get_recipe_parameters: {
    corpusId: unknown;
  };
  corpus_import_recipe: {
    tomlText: unknown;
  };
  corpus_install_with_parameters: {
    request: unknown;
  };
  create_conversation: {
    surfaceSkillId?: unknown;
  };
  delete_conversation: {
    conversationId: unknown;
  };
  delete_crash_record: {
    id: unknown;
  };
  delete_document_asset: {
    assetId: unknown;
  };
  delete_insight: {
    id: unknown;
  };
  delete_lesson: {
    id: unknown;
  };
  delete_model: {
    path: unknown;
  };
  detect_bootstrap: Record<string, never>;
  detect_hardware: Record<string, never>;
  diagnose_corpus: Record<string, never>;
  download_model: {
    request: unknown;
  };
  dr_abort: {
    jobId: unknown;
  };
  dr_active_runs: Record<string, never>;
  dr_capabilities: Record<string, never>;
  dr_list_runs: Record<string, never>;
  dr_open_report: {
    runId: unknown;
  };
  dr_quit_anyway: Record<string, never>;
  dr_start: {
    question: unknown;
    options: unknown;
  };
  enrich_get_starter_questions: {
    corpusId: unknown;
    limit: unknown;
  };
  enrich_list_corpora: Record<string, never>;
  explore_insights: {
    nodeIds: unknown;
  };
  export_answer: {
    conversationId: unknown;
    messageId: unknown;
    destPath: unknown;
  };
  export_crash_record: {
    id: unknown;
  };
  finalize_inner_work_conversation: {
    conversationId: unknown;
  };
  forget_memory: {
    memoryId: unknown;
  };
  get_activity_recent: {
    limit?: unknown;
  };
  get_activity_summary: {
    windowDays?: unknown;
  };
  get_chat_activity: {
    windowDays?: unknown;
  };
  get_config: Record<string, never>;
  get_contribution_status: Record<string, never>;
  get_conversation: {
    conversationId: unknown;
  };
  get_corpus_health: {
    corpusId: unknown;
  };
  get_corpus_progress: {
    corpusId: unknown;
  };
  get_document_asset: {
    assetId: unknown;
  };
  get_first_mesh_consent: Record<string, never>;
  get_ingest_budget: Record<string, never>;
  get_last_turn_provenance: {
    conversationId: unknown;
  };
  get_mesh_quiesced: Record<string, never>;
  get_mobile_pairing: Record<string, never>;
  get_recent_contributions: {
    limit?: unknown;
  };
  get_runtime_status: Record<string, never>;
  get_setup_context_size: Record<string, never>;
  get_setup_model_slots: Record<string, never>;
  get_setup_report: Record<string, never>;
  get_sink_status: Record<string, never>;
  get_storage_budget: Record<string, never>;
  governance_accept: {
    corpusId: unknown;
    tensionId: unknown;
    rationale: unknown;
  };
  governance_dismiss: {
    corpusId: unknown;
    tensionId: unknown;
    rationale?: unknown;
  };
  governance_export_write: {
    destPath: unknown;
    content: unknown;
  };
  governance_get_view: {
    corpusId: unknown;
  };
  governance_post_build_seed: {
    corpusId: unknown;
  };
  governance_resolve: {
    corpusId: unknown;
    tensionId: unknown;
    keepRuleId: unknown;
    rationale: unknown;
  };
  governance_seed: {
    corpusId: unknown;
  };
  governance_undo_tension: {
    corpusId: unknown;
    tensionId: unknown;
  };
  governance_write_recipe: {
    corpusId: unknown;
    displayName: unknown;
    sourcePath: unknown;
  };
  import_anthropic_zip: {
    request: unknown;
  };
  import_chatgpt_zip: {
    request: unknown;
  };
  import_email_archive: {
    request: unknown;
  };
  ingest_document: {
    filePath: unknown;
  };
  install_corpus: {
    corpusId: unknown;
  };
  install_starter_corpus: Record<string, never>;
  install_update: Record<string, never>;
  is_backend_ready: Record<string, never>;
  is_first_run: Record<string, never>;
  is_setup_complete: Record<string, never>;
  lc_can_expand: {
    corpusId: unknown;
  };
  lc_cancel: {
    corpusId: unknown;
  };
  lc_check_git: {
    corpusId: unknown;
  };
  lc_clean: {
    corpusId: unknown;
  };
  lc_cluster: {
    corpusId: unknown;
    config?: unknown;
  };
  lc_enrich_now: {
    corpusId: unknown;
  };
  lc_enrich_reset: {
    corpusId: unknown;
  };
  lc_enrichment_status: {
    corpusId: unknown;
  };
  lc_expand_corpus: {
    corpusId: unknown;
  };
  lc_get_preview: {
    corpusId: unknown;
    config?: unknown;
  };
  lc_incomplete_jobs: Record<string, never>;
  lc_ingest: {
    corpusId: unknown;
    withOcr?: unknown;
  };
  lc_list: Record<string, never>;
  lc_list_snapshots: {
    corpusId: unknown;
  };
  lc_newsworthy_status: Record<string, never>;
  lc_newsworthy_tick: Record<string, never>;
  lc_ocr_available: Record<string, never>;
  lc_pre_scan: {
    path: unknown;
    sourceType: unknown;
    displayName?: unknown;
  };
  lc_reenrich_note: {
    corpusId: unknown;
    sourceDocId: unknown;
    correctionHint: unknown;
    originalSummary: unknown;
  };
  lc_remove: {
    corpusId: unknown;
  };
  lc_rollback: {
    corpusId: unknown;
    snapshotPath: unknown;
  };
  lc_search: {
    corpusId: unknown;
    query: unknown;
    limit?: unknown;
  };
  lc_start_layered_setup: Record<string, never>;
  lc_validate_path: {
    path: unknown;
  };
  lc_watch_add_root: {
    corpusId: unknown;
    path: unknown;
  };
  lc_watch_confirm_deletion: {
    corpusId: unknown;
  };
  lc_watch_details: {
    corpusId: unknown;
  };
  lc_watch_document: {
    corpusId: unknown;
    docId: unknown;
  };
  lc_watch_enrich_disable: {
    corpusId: unknown;
  };
  lc_watch_enrich_enable: {
    corpusId: unknown;
    pipelineId: unknown;
  };
  lc_watch_enrich_rebuild: {
    corpusId: unknown;
  };
  lc_watch_incomplete_jobs: Record<string, never>;
  lc_watch_list: Record<string, never>;
  lc_watch_pause: {
    corpusId: unknown;
    reason?: unknown;
  };
  lc_watch_register: {
    path: unknown;
    displayName?: unknown;
    config?: unknown;
    syncInitial?: unknown;
  };
  lc_watch_remove: {
    corpusId: unknown;
  };
  lc_watch_remove_root: {
    corpusId: unknown;
    idx: unknown;
  };
  lc_watch_resume: {
    corpusId: unknown;
  };
  lc_watch_state: {
    corpusId: unknown;
  };
  lc_watch_status: {
    corpusId: unknown;
  };
  lc_watch_sync_now: {
    corpusId: unknown;
  };
  lc_write_tags: {
    corpusId: unknown;
    gitCommit?: unknown;
  };
  list_conversations: {
    limit?: unknown;
    offset?: unknown;
    surfaceSkillId?: unknown;
  };
  list_corpora: Record<string, never>;
  list_crash_records: Record<string, never>;
  list_daemon_models: Record<string, never>;
  list_document_assets: Record<string, never>;
  list_insights: {
    limit?: unknown;
  };
  list_legacy_documents: Record<string, never>;
  list_lessons: Record<string, never>;
  list_skills: Record<string, never>;
  mark_first_run_complete: Record<string, never>;
  mcp_add_server: {
    name: unknown;
    url: unknown;
    description?: unknown;
    bearer: unknown;
  };
  mcp_clear_token: {
    name: unknown;
  };
  mcp_list_servers: Record<string, never>;
  mcp_remove_server: {
    name: unknown;
  };
  mcp_set_token: {
    name: unknown;
    token: unknown;
  };
  mcp_test_connection: {
    name: unknown;
    url: unknown;
    bearer: unknown;
    token?: unknown;
  };
  mesh_assist_eligible_peers: {
    corpusId: unknown;
  };
  mesh_assist_revoke: {
    corpusId: unknown;
  };
  mesh_assist_start: {
    corpusId: unknown;
    peerNodeIds: unknown;
    ttlSecs?: unknown;
  };
  mesh_assist_status: {
    handoffId: unknown;
  };
  mesh_clear_peer_preference: {
    nodeId: unknown;
  };
  mesh_create: {
    meshName: unknown;
    encrypt?: unknown;
  };
  mesh_diagnostics: Record<string, never>;
  mesh_forget: {
    mesh: unknown;
  };
  mesh_get_contributions: Record<string, never>;
  mesh_get_placement: Record<string, never>;
  mesh_get_state: Record<string, never>;
  mesh_is_running: Record<string, never>;
  mesh_join: {
    link: unknown;
  };
  mesh_leave: Record<string, never>;
  mesh_list: Record<string, never>;
  mesh_list_peer_preferences: Record<string, never>;
  mesh_preview_join_link: {
    link: unknown;
  };
  mesh_relay_candidates: Record<string, never>;
  mesh_rotate_invite: Record<string, never>;
  mesh_set_peer_preference: {
    nodeId: unknown;
    multiplier: unknown;
    reason?: unknown;
  };
  mesh_switch: {
    mesh: unknown;
  };
  meshapp_capabilities: Record<string, never>;
  meshapp_claims: {
    corpusId: unknown;
    limit?: unknown;
  };
  meshapp_corpus_stats: {
    corpusId: unknown;
  };
  meshapp_document_feed: {
    corpusId: unknown;
    limitDocs?: unknown;
  };
  meshapp_findings: {
    corpusId: unknown;
    pattern?: unknown;
  };
  meshapp_graph: {
    corpusId: unknown;
    nodeType?: unknown;
    limit?: unknown;
  };
  meshapp_installed_apps: Record<string, never>;
  meshapp_list_installs: Record<string, never>;
  meshapp_node: {
    corpusId: unknown;
    id: unknown;
  };
  meshapp_open: {
    appId: unknown;
    entry?: unknown;
  };
  meshapp_open_outer_work: {
    corpusId: unknown;
  };
  meshapp_parcel_analytics: {
    corpusId: unknown;
    businessTaxTarget?: unknown;
  };
  meshapp_questions: {
    corpusId: unknown;
    limit?: unknown;
  };
  meshapp_read_chunk: {
    corpusId: unknown;
    chunkId: unknown;
  };
  meshapp_read_corpus: {
    corpusId: unknown;
    atomIds: unknown;
  };
  meshapp_reconciliation: {
    corpusId: unknown;
  };
  meshapp_record_install: {
    appId: unknown;
    name: unknown;
    granted: unknown;
  };
  meshapp_search_entities: {
    corpusId: unknown;
    query: unknown;
    nodeType?: unknown;
    limit?: unknown;
  };
  meshapp_search_parcels: {
    corpusId: unknown;
    query: unknown;
    limit?: unknown;
  };
  meshapp_stage_corpus_recipe: {
    corpusId: unknown;
    recipeToml: unknown;
  };
  meshapp_subgraph: {
    corpusId: unknown;
    nodeType?: unknown;
    limit?: unknown;
  };
  meshapp_timeline: {
    corpusId: unknown;
  };
  meshapp_uninstall: {
    appId: unknown;
  };
  meshapp_wrapped_artifact: {
    corpusId: unknown;
  };
  model_file_size: {
    path: unknown;
  };
  notebook_conversations: {
    corpusId: unknown;
    limit?: unknown;
    offset?: unknown;
  };
  notebook_list: Record<string, never>;
  open_corpus_explorer: {
    corpusId: unknown;
  };
  pause_contributions: {
    durationSecs: unknown;
  };
  pause_corpus: {
    corpusId: unknown;
  };
  prepare_answer_report: {
    note?: unknown;
    turn: unknown;
  };
  prepare_crash_report: Record<string, never>;
  prepare_diagnostic_report: {
    reason: unknown;
    note?: unknown;
  };
  primary_catalog: {
    profile?: unknown;
  };
  promote_legacy_document: {
    source: unknown;
  };
  read_crash_record: {
    id: unknown;
  };
  read_get_atom_card: {
    corpusId: unknown;
    atomId: unknown;
  };
  read_get_atom_elsewhere: {
    corpusId: unknown;
    atomId: unknown;
  };
  read_get_chunk: {
    corpusId: unknown;
    chunkId: unknown;
  };
  read_get_chunk_neighbors: {
    corpusId: unknown;
    chunkId: unknown;
    radius?: unknown;
  };
  rebuild_document_skeleton: {
    assetId: unknown;
  };
  recipe_author_build_prelude: {
    featureId: unknown;
  };
  recipe_author_dashboard_state: {
    featureId: unknown;
  };
  recipe_author_link_recent_artifact: {
    featureId: unknown;
    sinceUnix: unknown;
  };
  recipe_author_list_projects: Record<string, never>;
  recipe_author_new_project: {
    req: unknown;
  };
  recipe_author_restore_checkpoint: {
    req: unknown;
  };
  recipe_author_save_edited_toml: {
    featureId: unknown;
    editedToml: unknown;
  };
  recipe_run_harness: {
    recipePath: unknown;
    sampleSize: unknown;
    enrich: unknown;
  };
  recipe_test: {
    recipePath: unknown;
    sampleSize: unknown;
    offline: unknown;
  };
  recipe_validate: {
    recipePath: unknown;
    offline: unknown;
  };
  recommended_profile: Record<string, never>;
  record_first_mesh_consent: {
    shareGpu: unknown;
  };
  redirect_turn: {
    sessionId: unknown;
    intentHint: unknown;
  };
  remove_corpus: {
    corpusId: unknown;
  };
  rename_conversation: {
    conversationId: unknown;
    title: unknown;
  };
  resume_contributions: Record<string, never>;
  resume_session: {
    message: unknown;
    conversationId: unknown;
    sessionId: unknown;
    intentHint: unknown;
  };
  retry_enrichment_failures: {
    corpusId: unknown;
  };
  run_health_check: Record<string, never>;
  save_config: {
    config: unknown;
  };
  save_lesson: {
    draft: unknown;
  };
  scan_for_models: Record<string, never>;
  search_insights: {
    query: unknown;
  };
  search_messages: {
    query: unknown;
  };
  search_web: {
    query: unknown;
    conversationId: unknown;
  };
  send_message: {
    message: unknown;
    conversationId: unknown;
    contextChunks?: unknown;
    attachedFiles?: unknown;
  };
  send_message_stream: {
    message: unknown;
    conversationId: unknown;
    contextChunks?: unknown;
    attachedFiles?: unknown;
  };
  set_contribution_ceiling: {
    max?: unknown;
  };
  set_conversation_enabled_corpora: {
    conversationId: unknown;
    enabledCorpora?: unknown;
  };
  set_ingest_budget: {
    throttleFactor: unknown;
  };
  set_lesson_enabled: {
    id: unknown;
    enabled: unknown;
  };
  set_mesh_quiesced: {
    quiesced: unknown;
  };
  set_mobile_access: {
    enabled: unknown;
  };
  set_setup_context_size: {
    newCtx: unknown;
  };
  set_setup_model_slots: {
    slots: unknown;
  };
  set_storage_budget: {
    budgetBytes?: unknown;
  };
  slot_recommendation: {
    kind: unknown;
    profile?: unknown;
  };
  start_default_corpus_install: Record<string, never>;
  submit_approval: {
    key: unknown;
    approved: unknown;
  };
  submit_information_response: {
    key: unknown;
    content?: unknown;
  };
  submit_information_search: {
    key: unknown;
    query: unknown;
    conversationId?: unknown;
  };
  submit_input: {
    key: unknown;
    response: unknown;
  };
  suggest_node_name: Record<string, never>;
  supervisor_active: Record<string, never>;
  supervisor_reconnect: Record<string, never>;
  toggle_skill: {
    skillId: unknown;
    active: unknown;
  };
  upload_document_asset: {
    filePath: unknown;
  };
  warmup_primary_slot: Record<string, never>;
  weaken_memory: {
    memoryId: unknown;
  };
  workflow_capabilities: {
    nameOrPath: unknown;
  };
  workflow_list_runnable: Record<string, never>;
  workflow_run: {
    nameOrPath: unknown;
    params: unknown;
  };
}

export type CommandName = keyof CommandArgs;
