//! ATOS opencode plugin distribution.
//!
//! The plugin source (`sovereign-atos.ts`) is the integration
//! contract between an opencode session and the Commonwealth ATOS
//! pipeline — it injects `X-Feature-Id`, records
//! `record_atos_event` rows, and fetches the notes digest on
//! compaction. If its shape drifts from the daemon's API surface,
//! sessions produce confusing silent failures.
//!
//! So we pin it. The canonical source lives under
//! `sovereign-cli/assets/sovereign-atos.ts` and is `include_str!`'d
//! at build time. `sovereign project init` writes this version
//! into the target repo's `.opencode/plugins/`. `sovereign atos
//! install-plugin` re-syncs. `sovereign atos doctor` verifies the
//! header's CLI version matches the current binary.
//!
//! ## Why embed instead of download
//!
//! - No registry / network dependency at first run
//! - Version is pinned by the CLI binary (upgrade the CLI →
//!   regenerate the plugin)
//! - Works offline / in air-gapped CI
//! - Checked-in plugin file shows up in git history so teams see
//!   plugin bumps alongside code changes
//!
//! ## Overwrite policy
//!
//! `install_plugin` always writes with the generated-by header.
//! Local edits get clobbered — the header explicitly warns about
//! this. Users who need customization fork the upstream file;
//! embedding-and-overwriting is the tradeoff for version safety.

use std::path::{Path, PathBuf};

/// Canonical plugin text, embedded at compile time. When this file
/// is edited in `assets/`, `cargo build` picks up the change; when
/// `install_plugin` runs, the installed copy reflects it.
pub const PLUGIN_SRC: &str = include_str!("../assets/sovereign-atos.ts");

/// Version string the header carries. Tied to the CLI's own
/// version so `cargo install sovereign-cli` bump → plugin bump →
/// `doctor` flags pre-existing installs as stale.
pub const PLUGIN_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Relative path (from repo root) where the installed plugin
/// lands. Stable — opencode reads this path at session start.
pub fn plugin_rel_path() -> &'static str {
    ".opencode/plugins/sovereign-atos.ts"
}

pub fn plugin_abs_path(repo_root: &Path) -> PathBuf {
    repo_root.join(plugin_rel_path())
}

// ─── Installed-file rendering ────────────────────────────────────────────────

/// Generated-by header prepended to every installed copy. Two
/// goals: (1) make it obvious to a reader that this file is
/// tool-managed; (2) carry a machine-parseable version marker
/// `doctor` can read back.
///
/// The marker line is the contract — if you change its shape,
/// also update [`parse_installed_version`].
pub fn render_installed(version: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by sovereign-cli v");
    out.push_str(version);
    out.push_str(
        " — do NOT hand-edit. Regenerate with `sovereign atos install-plugin`.\n\
         // sovereign-atos-version: ",
    );
    out.push_str(version);
    out.push_str("\n\n");
    out.push_str(PLUGIN_SRC);
    out
}

/// Extract the version from an installed file's marker line.
/// Returns `None` when the file is missing the marker (either
/// hand-authored, or produced by a pre-distribution CLI).
pub fn parse_installed_version(file_contents: &str) -> Option<String> {
    for line in file_contents.lines().take(5) {
        let trimmed = line.trim_start_matches("// ").trim();
        if let Some(rest) = trimmed.strip_prefix("sovereign-atos-version:") {
            return Some(rest.trim().to_string());
        }
    }
    None
}

// ─── Installation ────────────────────────────────────────────────────────────

/// Outcome of an install attempt. The CLI surface uses this to
/// report `Installed` / `UpToDate` / `Replaced` distinctly —
/// silent overwrites hide version bumps that teams should see.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InstallOutcome {
    /// No prior file existed; we wrote a fresh copy.
    Installed,
    /// Prior file matched the current version byte-for-byte; no-op.
    UpToDate,
    /// Prior file existed at a different version (or was
    /// unversioned); we overwrote it. `prior_version` carries the
    /// old marker when one was present.
    Replaced { prior_version: Option<String> },
}

/// Write the embedded plugin to `repo_root/.opencode/plugins/
/// sovereign-atos.ts` with the version header. Creates parent
/// directories as needed. Idempotent when the installed version
/// already matches.
pub fn install_plugin(repo_root: &Path) -> std::io::Result<InstallOutcome> {
    let path = plugin_abs_path(repo_root);
    let rendered = render_installed(PLUGIN_VERSION);

    let prior = std::fs::read_to_string(&path).ok();
    let outcome = match prior.as_deref() {
        None => InstallOutcome::Installed,
        Some(existing) if existing == rendered => return Ok(InstallOutcome::UpToDate),
        Some(existing) => InstallOutcome::Replaced {
            prior_version: parse_installed_version(existing),
        },
    };

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, rendered)?;
    Ok(outcome)
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn render_installed_has_a_parseable_version_marker() {
        let out = render_installed("1.2.3");
        let v = parse_installed_version(&out);
        assert_eq!(v.as_deref(), Some("1.2.3"));
    }

    #[test]
    fn parse_returns_none_when_marker_missing() {
        assert!(parse_installed_version("some random text\n").is_none());
        assert!(parse_installed_version(PLUGIN_SRC).is_none());
    }

    #[test]
    fn parse_ignores_version_line_past_the_header_window() {
        // Marker only honored in the first 5 lines — prevents a
        // rogue comment deep in the file from faking a version.
        let body = "line1\nline2\nline3\nline4\nline5\n// sovereign-atos-version: 9.9.9\n".to_string();
        assert!(parse_installed_version(&body).is_none());
    }

    #[test]
    fn install_plugin_on_empty_repo_writes_installed() {
        let tmp = tempdir().unwrap();
        let outcome = install_plugin(tmp.path()).unwrap();
        assert_eq!(outcome, InstallOutcome::Installed);
        let path = plugin_abs_path(tmp.path());
        assert!(path.exists());
        let disk = std::fs::read_to_string(&path).unwrap();
        assert!(
            disk.contains("sovereign-atos-version:"),
            "installed file must carry the version marker"
        );
        assert!(
            disk.contains("do NOT hand-edit"),
            "installed file must carry the don't-hand-edit header"
        );
    }

    #[test]
    fn install_plugin_second_run_is_up_to_date() {
        let tmp = tempdir().unwrap();
        assert_eq!(
            install_plugin(tmp.path()).unwrap(),
            InstallOutcome::Installed
        );
        assert_eq!(
            install_plugin(tmp.path()).unwrap(),
            InstallOutcome::UpToDate
        );
    }

    #[test]
    fn install_plugin_replaces_different_version_and_reports_prior() {
        let tmp = tempdir().unwrap();
        // Plant an "older" version file.
        let old = render_installed("0.0.1");
        let path = plugin_abs_path(tmp.path());
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, old).unwrap();

        match install_plugin(tmp.path()).unwrap() {
            InstallOutcome::Replaced { prior_version } => {
                assert_eq!(prior_version.as_deref(), Some("0.0.1"));
            }
            other => panic!("expected Replaced, got {other:?}"),
        }

        // After replace, disk has the current version.
        let disk = std::fs::read_to_string(&path).unwrap();
        assert_eq!(
            parse_installed_version(&disk).as_deref(),
            Some(PLUGIN_VERSION)
        );
    }

    #[test]
    fn install_plugin_replaces_unversioned_file_with_none_prior() {
        let tmp = tempdir().unwrap();
        // Plant a hand-authored file with no marker.
        let path = plugin_abs_path(tmp.path());
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "// hand-authored plugin, no version\n").unwrap();
        match install_plugin(tmp.path()).unwrap() {
            InstallOutcome::Replaced {
                prior_version: None,
            } => {}
            other => panic!("expected Replaced{{None}}, got {other:?}"),
        }
    }

    #[test]
    fn embedded_plugin_looks_like_the_real_plugin() {
        // Smoke check — if someone drops a wrong file into assets/,
        // this catches it before ship.
        assert!(PLUGIN_SRC.contains("sovereign-atos"));
        assert!(
            PLUGIN_SRC.contains("SOVEREIGN_FEATURE_ID") || PLUGIN_SRC.contains("X-Feature-Id"),
            "plugin must integrate the ATOS session surface"
        );
    }
}
