<script lang="ts">
  // Atlas Inspector — index route.
  //
  // Lists corpora that have an atlas on disk, with per-atom-type
  // counts. Clicking a row delegates to the parent's `onSelect`
  // callback (AtlasSurface), which switches the inner view to
  // `AtlasCorpusView` for that corpus.

  import { onMount } from "svelte";
  import { atlasListCorpora } from "../../api";
  import type { AtlasCorpusSummary, AtomType } from "../../types";

  interface Props {
    /** Optional click handler. When set, rows become buttons that
     *  call this with the corpus id. When omitted, rows render
     *  read-only (useful for the standalone index view in early
     *  Phase 1). */
    onSelect?: (corpusId: string) => void;
  }

  let { onSelect }: Props = $props();

  let summaries: AtlasCorpusSummary[] = $state([]);
  let loading = $state(true);
  let error: string | null = $state(null);

  const ATOM_TYPE_ORDER: AtomType[] = [
    "Entity",
    "Event",
    "State",
    "Relation",
    "Claim",
    "Question",
    "Configuration",
    "ArgumentReconstruction",
  ];

  // Compact glyph per atom type — keeps the per-corpus row scannable
  // without burning horizontal space. Same labels used in Step 3 tabs.
  const ATOM_TYPE_LABEL: Record<AtomType, string> = {
    Entity: "Entity",
    Event: "Event",
    State: "State",
    Relation: "Relation",
    Claim: "Claim",
    Question: "Question",
    Configuration: "Config",
    ArgumentReconstruction: "Argument",
  };

  onMount(async () => {
    try {
      summaries = await atlasListCorpora();
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    } finally {
      loading = false;
    }
  });

  function formatTimestamp(unix: number | undefined): string {
    if (!unix) return "";
    const d = new Date(unix * 1000);
    return d.toLocaleString();
  }

  function nonZeroCounts(s: AtlasCorpusSummary): Array<[AtomType, number]> {
    return ATOM_TYPE_ORDER.flatMap<[AtomType, number]>((t) => {
      const n = s.atom_counts[t] ?? 0;
      return n > 0 ? [[t, n]] : [];
    });
  }

  // Human-friendly section heading for a `display_category` value.
  // Unknown categories fall back to a title-cased rendering so newly-
  // added categories (declared in a recipe `[display]` block) light up
  // without a frontend round-trip.
  const CATEGORY_TITLE: Record<string, string> = {
    conversation: "Conversations",
    reference: "Reference",
    argument: "Argument",
    personal: "Personal",
  };
  const OTHER_GROUP = "__other__";

  function categoryKey(s: AtlasCorpusSummary): string {
    return s.display_category ?? OTHER_GROUP;
  }

  function categoryTitle(key: string): string {
    if (key === OTHER_GROUP) return "Other";
    return (
      CATEGORY_TITLE[key] ??
      key.charAt(0).toUpperCase() + key.slice(1).replace(/[-_]/g, " ")
    );
  }

  // Stable order: known categories first in the order they appear in
  // CATEGORY_TITLE (conversation comes first since it's the
  // newest-feature surface), then any unknown categories alphabetically,
  // then Other last so legacy / untagged corpora don't crowd the top.
  const KNOWN_CATEGORY_ORDER = Object.keys(CATEGORY_TITLE);

  let grouped = $derived.by(() => {
    const buckets = new Map<string, AtlasCorpusSummary[]>();
    for (const s of summaries) {
      const key = categoryKey(s);
      const list = buckets.get(key) ?? [];
      list.push(s);
      buckets.set(key, list);
    }
    const ordered: Array<{ key: string; title: string; rows: AtlasCorpusSummary[] }> = [];
    for (const k of KNOWN_CATEGORY_ORDER) {
      const rows = buckets.get(k);
      if (rows && rows.length > 0) {
        ordered.push({ key: k, title: categoryTitle(k), rows });
        buckets.delete(k);
      }
    }
    const remainingKnown = Array.from(buckets.keys())
      .filter((k) => k !== OTHER_GROUP)
      .sort();
    for (const k of remainingKnown) {
      ordered.push({ key: k, title: categoryTitle(k), rows: buckets.get(k)! });
      buckets.delete(k);
    }
    const other = buckets.get(OTHER_GROUP);
    if (other && other.length > 0) {
      ordered.push({ key: OTHER_GROUP, title: categoryTitle(OTHER_GROUP), rows: other });
    }
    return ordered;
  });
</script>

<div class="atlas-index">
  <header class="atlas-header">
    <h1>Atlas</h1>
    <p class="subtitle">
      Inspect the structured enrichments extracted from each corpus.
      Read-only today; curation is on the roadmap.
    </p>
  </header>

  {#if loading}
    <div class="status">Loading atlases…</div>
  {:else if error}
    <div class="status error" role="alert">
      Failed to load atlases: {error}
    </div>
  {:else if summaries.length === 0}
    <div class="status empty">
      <p>No atlases on disk yet.</p>
      <p class="hint">
        Atlases are generated by the extraction pipeline (Tier-2
        enrichment). Install a corpus and run extraction to populate
        this surface.
      </p>
    </div>
  {:else}
    <div class="category-stack">
      {#each grouped as group (group.key)}
        <section class="category-section" data-testid="atlas-category-section" data-category={group.key}>
          <h2 class="category-heading">{group.title}</h2>
          <ul class="corpus-list">
            {#each group.rows as s (s.corpus_id)}
              <li class="corpus-row" data-testid="atlas-corpus-row">
                <button
                  class="row-button"
                  type="button"
                  disabled={!onSelect}
                  onclick={() => onSelect?.(s.corpus_id)}
                  aria-label={`Open ${s.display_name}`}
                >
                  <div class="row-header">
                    <span class="corpus-id">{s.display_name}</span>
                    <span class="total">{s.total_atoms.toLocaleString()} atoms</span>
                  </div>
                  <div class="counts">
                    {#each nonZeroCounts(s) as [t, n] (t)}
                      <span class="count-chip" title={t}>
                        <span class="count-label">{ATOM_TYPE_LABEL[t]}</span>
                        <span class="count-n">{n.toLocaleString()}</span>
                      </span>
                    {/each}
                  </div>
                  {#if s.last_extracted_unix}
                    <div class="meta">
                      Last extracted: {formatTimestamp(s.last_extracted_unix)}
                    </div>
                  {/if}
                </button>
              </li>
            {/each}
          </ul>
        </section>
      {/each}
    </div>
  {/if}
</div>

<style>
  .atlas-index {
    max-width: 920px;
    margin: 0 auto;
    padding: 40px 32px 80px;
    color: var(--text-primary);
    font-family: var(--font-sans);
  }

  .atlas-header {
    margin-bottom: 32px;
  }

  .atlas-header h1 {
    font-size: 1.6rem;
    font-weight: 600;
    margin: 0 0 6px;
    letter-spacing: -0.01em;
  }

  .subtitle {
    margin: 0;
    color: var(--text-muted);
    font-size: 0.9rem;
    line-height: 1.5;
    max-width: 60ch;
  }

  .status {
    padding: 32px;
    text-align: center;
    color: var(--text-muted);
    font-size: 0.9rem;
  }

  .status.error {
    color: var(--danger, #c33);
  }

  .status.empty .hint {
    margin-top: 8px;
    font-size: 0.85rem;
    color: var(--text-muted);
    max-width: 50ch;
    margin-left: auto;
    margin-right: auto;
    line-height: 1.5;
  }

  .category-stack {
    display: flex;
    flex-direction: column;
    gap: 28px;
  }

  /* `.category-section` has no own styling — the heading + nested
     `.corpus-list` carry the visual weight. Comment retained so a
     future maintainer doesn't add a background here without
     reading why we didn't. */

  .category-heading {
    margin: 0 0 12px;
    font-size: 0.78rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--text-muted);
  }

  .corpus-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .corpus-row {
    list-style: none;
  }

  .row-button {
    width: 100%;
    padding: 16px 18px;
    background: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    transition: border-color 150ms ease, background 150ms ease;
    color: inherit;
    font: inherit;
    text-align: left;
    cursor: pointer;
    display: block;
  }

  .row-button:hover:not(:disabled) {
    border-color: var(--border-mid);
    background: var(--bg-elevated, var(--bg-secondary));
  }

  .row-button:disabled {
    cursor: default;
  }

  .row-button:focus-visible {
    outline: 2px solid var(--accent);
    outline-offset: 2px;
  }

  .row-header {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    margin-bottom: 10px;
  }

  .corpus-id {
    font-weight: 600;
    font-size: 0.98rem;
  }

  .total {
    color: var(--text-muted);
    font-size: 0.82rem;
    font-variant-numeric: tabular-nums;
  }

  .counts {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
  }

  .count-chip {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    padding: 3px 9px;
    background: var(--bg-elevated, var(--bg-primary));
    border: 1px solid var(--border-mid, var(--border));
    border-radius: 10px;
    font-size: 0.76rem;
    color: var(--text-secondary);
  }

  .count-label {
    color: var(--text-muted);
  }

  .count-n {
    font-weight: 500;
    font-variant-numeric: tabular-nums;
  }

  .meta {
    margin-top: 10px;
    font-size: 0.74rem;
    color: var(--text-muted);
    letter-spacing: 0.01em;
  }
</style>
