// SPDX-License-Identifier: AGPL-3.0-or-later
//! Chat-transcript turn detection over raw text.
//!
//! The *detector* half of `corpus_engine::chunkers::threaded_turns`: the
//! `### [ts] sender` header grammar and the [`TurnAuthor`] vocabulary, with no
//! chunking machinery. The `ThreadedTurnsChunker` stays in `corpus-engine`,
//! which re-exports these at `corpus_engine::chunkers::threaded_turns::*`, so
//! read paths (the wrapped meshapp artifact) share the one grammar without
//! linking the engine.

use regex::Regex;
use std::sync::OnceLock;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TurnAuthor {
    User,
    Assistant,
    /// Free-form prose with no explicit sender — reserved for the
    /// inner-work journaling ingest. Not emitted by this chunker.
    Unattributed,
    /// Text the user pasted from a model elsewhere; claimed author
    /// is the user, generated by a model. Reserved for inner-work
    /// journaling ingest. Not emitted by this chunker.
    Pasted,
}

impl TurnAuthor {
    pub fn slug(self) -> &'static str {
        match self {
            TurnAuthor::User => "user",
            TurnAuthor::Assistant => "assistant",
            TurnAuthor::Unattributed => "unattributed",
            TurnAuthor::Pasted => "pasted",
        }
    }
}

fn turn_header_regex() -> &'static Regex {
    static CELL: OnceLock<Regex> = OnceLock::new();
    // Matches `### [YYYY-MM-DD HH:MM] sender` or
    // `### [unknown-time] sender`. Captures: 1 = timestamp content
    // inside the brackets; 2 = sender slug.
    CELL.get_or_init(|| Regex::new(r"(?m)^###\s+\[([^\]]+)\]\s+(user|assistant)\s*$").unwrap())
}

/// One `### [ts] sender` turn block parsed out of rendered conversation
/// text. Public so downstream read paths (e.g. the wrapped meshapp
/// artifact builder) reuse the one header grammar instead of
/// duplicating the regex.
#[derive(Debug)]
pub struct ParsedTurn {
    pub author: TurnAuthor,
    /// `YYYY-MM-DD HH:MM` (UTC, as rendered by the extractor), or
    /// `None` for `[unknown-time]` headers.
    pub timestamp: Option<String>,
    /// The full block, header line included, trailing whitespace trimmed.
    pub block: String,
    /// Byte offset of the block's header within the text that was
    /// parsed. `text[..turns[0].byte_start]` is therefore the text that
    /// precedes every header — for a chunk cut out of the middle of a
    /// long turn, that leading text belongs to the PREVIOUS turn, and a
    /// caller totalling a turn's real extent needs the offset to say so.
    pub byte_start: usize,
}

/// Split rendered conversation text into its turn blocks. Returns an
/// empty vec when the text carries no turn headers.
pub fn parse_turns(text: &str) -> Vec<ParsedTurn> {
    let re = turn_header_regex();
    let captures: Vec<(usize, String, String)> = re
        .captures_iter(text)
        .map(|c| {
            let start = c.get(0).unwrap().start();
            let ts_raw = c.get(1).unwrap().as_str().to_string();
            let sender = c.get(2).unwrap().as_str().to_string();
            (start, ts_raw, sender)
        })
        .collect();

    if captures.is_empty() {
        return Vec::new();
    }

    let mut turns: Vec<ParsedTurn> = Vec::with_capacity(captures.len());
    for (i, (start, ts_raw, sender)) in captures.iter().enumerate() {
        let block_end = captures
            .get(i + 1)
            .map(|(s, _, _)| *s)
            .unwrap_or(text.len());
        let block = text[*start..block_end].trim_end().to_string();
        let author = match sender.as_str() {
            "user" => TurnAuthor::User,
            "assistant" => TurnAuthor::Assistant,
            _ => continue,
        };
        let timestamp = if ts_raw == "unknown-time" {
            None
        } else {
            Some(ts_raw.clone())
        };
        turns.push(ParsedTurn {
            author,
            timestamp,
            block,
            byte_start: *start,
        });
    }
    turns
}
