// SPDX-License-Identifier: AGPL-3.0-or-later
// Global setup for the real-mode suite (playwright.real.config.ts):
// build + launch a REAL sovereign-desktop process with the command
// bridge enabled, under a hermetic scratch profile, and wait until the
// backend signals ready. Specs then drive the Vite-served frontend
// (Chromium) against this process via tauri-shim-real.js.
//
// Hermeticity: HOME + XDG_* point into test-results/real-profile/, so
// config, conversations DB, data dir, and caches are all scratch.
// Models are the one shared resource (multi-GB GGUFs, mmap'd
// read-only) — referenced by absolute path.
//
// Env knobs:
//   SOVEREIGN_REAL_ALLOW_ATTACH=1  — permit a daemon on :9741 (the app
//       will silently Attach to it: knowledge/inference state is then
//       the REAL daemon's, not hermetic. Off by default; the guard
//       hard-fails instead.)
//   SOVEREIGN_REAL_KEEP_PROFILE=1  — don't wipe the scratch profile
//       (inspect state across runs / faster reboots).
//   SOVEREIGN_REAL_XVFB=1          — wrap the app in xvfb-run -a.
//   SOVEREIGN_REAL_CHAT_MODEL / SOVEREIGN_REAL_EMBED_MODEL — override
//       the GGUF paths baked into the scratch desktop.toml.
import { execSync, spawn } from "node:child_process";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CRATE_ROOT = path.resolve(__dirname, "../../..");
const REPO_ROOT = path.resolve(CRATE_ROOT, "../../..");
const RESULTS = path.join(CRATE_ROOT, "test-results");
const PROFILE = path.join(RESULTS, "real-profile");
const HOME = path.join(PROFILE, "home");
const APP_BIN = path.join(REPO_ROOT, "target/debug/sovereign-desktop");
const APP_LOG = path.join(RESULTS, "real-app.log");
const PID_FILE = path.join(RESULTS, "real-app.pid");
export const LEDGER_REAL = path.join(RESULTS, "ledger-real.jsonl");
const BRIDGE = "http://127.0.0.1:9745";

// Fast profile: smallest viable chat model + the standard embedder.
// Phase 3 bench replays override with the production primary so score
// deltas isolate transport, not model.
const DEFAULT_CHAT_MODEL = path.join(REPO_ROOT, "sovereign/models/Qwen3.5-2B.Q6_K.gguf");
const DEFAULT_EMBED_MODEL = path.join(
  REPO_ROOT,
  "sovereign/models/Qwen3-Embedding-0.6B-Q8_0.gguf",
);

function portInUse(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const sock = net.connect({ port, host: "127.0.0.1" });
    const done = (used: boolean) => {
      sock.destroy();
      resolve(used);
    };
    sock.once("connect", () => done(true));
    sock.once("error", () => done(false));
    sock.setTimeout(1500, () => done(false));
  });
}

async function fetchJson(url: string, init?: RequestInit, timeoutMs = 3000) {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch(url, { ...init, signal: ctrl.signal });
    return (await res.json()) as Record<string, unknown>;
  } finally {
    clearTimeout(t);
  }
}

function bakeProfile(): void {
  if (!process.env.SOVEREIGN_REAL_KEEP_PROFILE) {
    fs.rmSync(PROFILE, { recursive: true, force: true });
  }
  const cfgDir = path.join(HOME, ".config/sovereign");
  fs.mkdirSync(cfgDir, { recursive: true });
  fs.mkdirSync(path.join(HOME, ".local/share"), { recursive: true });
  fs.mkdirSync(path.join(HOME, ".cache"), { recursive: true });

  const chatModel = process.env.SOVEREIGN_REAL_CHAT_MODEL ?? DEFAULT_CHAT_MODEL;
  const embedModel = process.env.SOVEREIGN_REAL_EMBED_MODEL ?? DEFAULT_EMBED_MODEL;
  for (const m of [chatModel, embedModel]) {
    if (!fs.existsSync(m)) {
      throw new Error(
        `real-mode setup: model not found: ${m}\n` +
          `Point SOVEREIGN_REAL_CHAT_MODEL / SOVEREIGN_REAL_EMBED_MODEL at real GGUFs.`,
      );
    }
  }

  // Tilde-relative model paths in any daemon-side config resolve under
  // the scratch HOME — keep them valid via a symlink to the real dir.
  const sovDir = path.join(HOME, ".sovereign");
  fs.mkdirSync(sovDir, { recursive: true });
  const modelsLink = path.join(sovDir, "models");
  if (!fs.existsSync(modelsLink)) {
    fs.symlinkSync(path.join(REPO_ROOT, "sovereign/models"), modelsLink);
  }

  const desktopToml = [
    `# Generated by tests/e2e/real/global-setup.ts — hermetic real-mode profile.`,
    `model_path = ${JSON.stringify(chatModel)}`,
    `primary_model_path = ${JSON.stringify(chatModel)}`,
    `embed_model_path = ${JSON.stringify(embedModel)}`,
    `setup_complete = true`,
    `auto_collaborate = false`,
    ``,
  ].join("\n");
  fs.writeFileSync(path.join(cfgDir, "desktop.toml"), desktopToml);
}

export default async function globalSetup(): Promise<void> {
  fs.mkdirSync(RESULTS, { recursive: true });
  fs.rmSync(LEDGER_REAL, { force: true });

  // ── Guard: a daemon on :9741 flips the app into Attach mode against
  // real (non-hermetic) knowledge/inference state. Refuse by default.
  if (await portInUse(9741)) {
    if (process.env.SOVEREIGN_REAL_ALLOW_ATTACH === "1") {
      console.warn(
        "[real-setup] :9741 is occupied — proceeding in ATTACH mode " +
          "(SOVEREIGN_REAL_ALLOW_ATTACH=1). Knowledge/inference state is the " +
          "REAL daemon's; conversations/config remain scratch.",
      );
    } else {
      throw new Error(
        "real-mode setup: a daemon is running on :9741. The app would Attach " +
          "to it and leak non-hermetic state into the run. Stop it " +
          "(`sovereign daemon stop`) or set SOVEREIGN_REAL_ALLOW_ATTACH=1 " +
          "to accept attach-mode semantics.",
      );
    }
  }

  // ── Build: embedded frontend assets + the debug binary ──
  if (!fs.existsSync(path.join(CRATE_ROOT, "dist/index.html"))) {
    console.log("[real-setup] dist/ missing — npm run build");
    execSync("npm run build", { cwd: CRATE_ROOT, stdio: "inherit" });
  }
  console.log("[real-setup] cargo build -p sovereign-desktop (debug)");
  execSync("cargo build -p sovereign-desktop", {
    cwd: REPO_ROOT,
    stdio: "inherit",
    timeout: 15 * 60 * 1000,
  });

  bakeProfile();

  // ── Launch ──
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    HOME,
    XDG_CONFIG_HOME: path.join(HOME, ".config"),
    XDG_DATA_HOME: path.join(HOME, ".local/share"),
    XDG_CACHE_HOME: path.join(HOME, ".cache"),
    SOVEREIGN_COMMAND_BRIDGE: "1",
    SOVEREIGN_COMMAND_BRIDGE_LEDGER: LEDGER_REAL,
    RUST_LOG: process.env.RUST_LOG ?? "sovereign_desktop=info",
  };
  const useXvfb = process.env.SOVEREIGN_REAL_XVFB === "1";
  const cmd = useXvfb ? "xvfb-run" : APP_BIN;
  const args = useXvfb ? ["-a", APP_BIN] : [];

  const log = fs.openSync(APP_LOG, "w");
  const child = spawn(cmd, args, {
    env,
    cwd: os.homedir(), // not the repo — catch accidental cwd-relative writes
    stdio: ["ignore", log, log],
    detached: true,
  });
  child.unref();
  if (!child.pid) throw new Error("real-mode setup: failed to spawn app");
  fs.writeFileSync(PID_FILE, String(child.pid));
  console.log(`[real-setup] app pid=${child.pid}, log=${APP_LOG}`);

  // ── Readiness: bridge up, then backend-ready (sticky replay) ──
  const deadline = Date.now() + 180_000;
  let bridgeUp = false;
  while (Date.now() < deadline) {
    try {
      const h = await fetchJson(`${BRIDGE}/healthz`);
      if (h.ok) {
        bridgeUp = true;
        break;
      }
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  if (!bridgeUp) throw new Error(`real-mode setup: bridge never came up — see ${APP_LOG}`);

  while (Date.now() < deadline) {
    try {
      const r = await fetchJson(`${BRIDGE}/listen`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ event: "backend-ready" }),
      });
      if (r.replayed) {
        console.log("[real-setup] backend-ready ✓");
        return;
      }
      const s = await fetchJson(`${BRIDGE}/listen`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ event: "setup-required" }),
      });
      if (s.replayed) {
        throw new Error(
          "real-mode setup: app routed to the setup wizard — the baked " +
            "desktop.toml didn't satisfy the boot guard (model path? " +
            `setup_complete?). See ${APP_LOG}`,
        );
      }
    } catch (e) {
      if (e instanceof Error && e.message.startsWith("real-mode setup:")) throw e;
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  throw new Error(`real-mode setup: backend-ready never fired within 180s — see ${APP_LOG}`);
}
