// SPDX-License-Identifier: AGPL-3.0-or-later
// Global setup for the real-mode suite (playwright.real.config.ts):
// build + launch a REAL sovereign-desktop process with the command
// bridge enabled, under a hermetic scratch profile, and wait until the
// backend signals ready. Specs then drive the Vite-served frontend
// (Chromium) against this process via tauri-shim-real.js.
//
// Hermeticity: HOME + XDG_* point into test-artifacts/real-profile/, so
// config, conversations DB, data dir, and caches are all scratch.
// (test-artifacts/, not test-results/ — Playwright wipes its outputDir
// at every run start, which would destroy ledgers and the profile.)
// Models are the one shared resource (multi-GB GGUFs, mmap'd
// read-only) — referenced by absolute path.
//
// Mode: MANAGED by default — the harness owns a fixture-scoped daemon on
// :9741 (see MANAGED_DAEMON below). Attach mode is the opt-out.
//
// Env knobs:
//   SOVEREIGN_REAL_ALLOW_ATTACH=1  — attach to an EXISTING daemon on :9741
//       instead of starting our own (the app Attaches to it: knowledge/
//       inference state is then the REAL daemon's, not hermetic). Trades the
//       fixture-scoped determinism for the operator's real model/corpora.
//   SOVEREIGN_REAL_KEEP_PROFILE=1  — don't wipe the scratch profile
//       (inspect state across runs / faster reboots).
//   SOVEREIGN_REAL_XVFB=1          — wrap the app in xvfb-run -a.
//   SOVEREIGN_REAL_CHAT_MODEL / SOVEREIGN_REAL_EMBED_MODEL — override
//       the GGUF paths baked into the scratch desktop.toml.
import { execSync, spawn } from "node:child_process";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CRATE_ROOT = path.resolve(__dirname, "../../..");
const REPO_ROOT = path.resolve(CRATE_ROOT, "../../..");
const RESULTS = path.join(CRATE_ROOT, "test-artifacts");
// Overridable so a sibling suite can own a SEPARATE scratch profile in the
// same artifacts dir. Demo mode (tests/e2e/demo) uses this: sharing
// `real-profile` would carry the real suite's local corpus registrations
// ("E2E Fixture Corpus", "Maple House (E2E)") onto the Library shelf — i.e.
// into frame — even though demo mode skips planting them.
const PROFILE = path.join(RESULTS, process.env.SOVEREIGN_REAL_PROFILE_DIR ?? "real-profile");
const HOME = path.join(PROFILE, "home");
const APP_BIN = path.join(REPO_ROOT, "target/debug/sovereign-desktop");
const APP_LOG = path.join(RESULTS, "real-app.log");
const PID_FILE = path.join(RESULTS, "real-app.pid");
export const LEDGER_REAL = path.join(RESULTS, "ledger-real.jsonl");
/** Specs read this to learn the fixture corpus id + doc paths. */
export const FIXTURE_INFO = path.join(RESULTS, "real-fixture.json");
const FIXTURE_CORPUS_DIR = path.join(__dirname, "fixtures/corpus");
const FIXTURE_ATTACH_DOC = path.join(__dirname, "fixtures/attach/expedition-notes.txt");
const FIXTURE_DISPLAY_NAME = "E2E Fixture Corpus";
// Governance fixture: a tiny house-charter+minutes folder ingested as a REAL
// corpus (so it appears in the Library shelf), with a deterministic, checked-in
// post-build atlas overlaid onto its atlas dir. The atlas is generated by the
// Rust test `governance_real_fixture_is_valid_or_regenerated` (REGEN_GOV_FIXTURE=1)
// so its conflicts are known without running an LLM enrich. `governance.real.spec.ts`
// drives the Conflicts tab against it.
const GOV_CORPUS_DIR = path.join(__dirname, "fixtures/governance-corpus");
const GOV_ATLAS_FIXTURE = path.join(__dirname, "fixtures/governance-atlas");
const GOV_DISPLAY_NAME = "Maple House (E2E)";
/** Specs read this to learn the governance corpus id. */
export const GOV_FIXTURE_INFO = path.join(RESULTS, "real-gov-fixture.json");
const BRIDGE = "http://127.0.0.1:9745";
const DAEMON_BIN = path.join(REPO_ROOT, "target/debug/sovereign-cli-daemon");

// Managed-daemon mode is the DEFAULT for the whole real suite: the harness
// starts its OWN fixture-scoped daemon on the test-profile HOME, so the daemon's
// index dir IS the desktop's read path (`list_corpora`/`read_get_chunk` resolve
// locally) AND retrieval is scoped to the single fixture corpus. It loads a fixed
// local chat/embed pair (a dense, non-MTP primary + the small embedder) so every
// spec — chat, journeys, and the workflow-author loop — runs in one deterministic
// environment. Attach-to-the-dev-daemon is the opt-out (SOVEREIGN_REAL_ALLOW_ATTACH
// =1): it exercises the operator's actual model/corpora but is non-hermetic and
// can't provide the fixture-scoped determinism (many corpora + a different, MTP
// model whose cancellation timing the journeys aren't tuned to). The legacy
// SOVEREIGN_REAL_MANAGED_DAEMON env is no longer read — managed is the default, so
// a script that still sets it lands on managed anyway (a harmless no-op).
const MANAGED_DAEMON = process.env.SOVEREIGN_REAL_ALLOW_ATTACH !== "1";

// Managed profile: the smallest viable chat model + the standard embedder. The 2B
// is deliberate, not just frugal — the streaming/cancel specs are cadence-sensitive
// (they assert `stream tokens > 0` inside a short window and "return to idle after
// cancel"), and a larger model's slower time-to-first-token breaks them (measured:
// the dense 4B regresses real-cancel-stream + cancellation.journey to 0 tokens /
// cancel-hang). The 2B greens 18/19 deterministically; the one exception is the
// agentic workflow-author loop, which needs a capable primary the 2B can't provide
// and is therefore GATED (see real-workflow-author.spec.ts) — run it in attach mode
// against a 9B+ daemon, or via SOVEREIGN_REAL_CHAT_MODEL. Phase 3 bench replays also
// override the model via that env so score deltas isolate transport, not model.
const DEFAULT_CHAT_MODEL = path.join(REPO_ROOT, "sovereign/models/Qwen3.5-2B.Q6_K.gguf");
const DEFAULT_EMBED_MODEL = path.join(
  REPO_ROOT,
  "sovereign/models/Qwen3-Embedding-0.6B-Q8_0.gguf",
);

function portInUse(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const sock = net.connect({ port, host: "127.0.0.1" });
    const done = (used: boolean) => {
      sock.destroy();
      resolve(used);
    };
    sock.once("connect", () => done(true));
    sock.once("error", () => done(false));
    sock.setTimeout(1500, () => done(false));
  });
}

async function fetchJson(url: string, init?: RequestInit, timeoutMs = 3000) {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch(url, { ...init, signal: ctrl.signal });
    return (await res.json()) as Record<string, unknown>;
  } finally {
    clearTimeout(t);
  }
}

async function invoke<T = unknown>(
  cmd: string,
  args: Record<string, unknown> = {},
  timeoutMs = 30_000,
): Promise<T> {
  const body = await fetchJson(
    `${BRIDGE}/invoke`,
    {
      method: "POST",
      headers: { "content-type": "application/json", "x-sovereign-spec": "global-setup" },
      body: JSON.stringify({ cmd, args }),
    },
    timeoutMs,
  );
  if (!body.ok) throw new Error(`setup invoke ${cmd} failed: ${JSON.stringify(body.error)}`);
  return body.result as T;
}

/// Ingest the 3-file fixture corpus through the same lc_* commands the
/// watched-folder UI uses, and verify the DYNAMIC progress channel
/// (`local-corpus://progress/{job_id}`) actually delivers over the
/// bridge's lazy listen_any path — static event registration can't
/// cover per-job channel names, so this doubles as that contract's
/// regression check.
async function ingestFixtureCorpus(): Promise<void> {
  const existing = await invoke<Array<{ corpus_id: string; display_name?: string }>>(
    "lc_list",
  );
  let corpusId = existing.find((c) => c.display_name === FIXTURE_DISPLAY_NAME)?.corpus_id;

  if (!corpusId) {
    const validation = await invoke<{ exists: boolean; is_dir: boolean }>(
      "lc_validate_path",
      { path: FIXTURE_CORPUS_DIR },
    );
    if (!validation.exists || !validation.is_dir) {
      throw new Error(`fixture corpus dir invalid: ${FIXTURE_CORPUS_DIR}`);
    }
    const pre = await invoke<{ corpus_id: string; job_id: string }>(
      "lc_pre_scan",
      { path: FIXTURE_CORPUS_DIR, sourceType: "folder", displayName: FIXTURE_DISPLAY_NAME },
      60_000,
    );
    corpusId = pre.corpus_id;

    const jobId = await invoke<string>("lc_ingest", { corpusId, withOcr: false }, 60_000);
    const channel = `local-corpus://progress/${jobId}`;
    // Register the dynamic channel with the bridge; rows published
    // from here on land in the replay ring (`/events/recent`), so a
    // fast ingest can't outrun a streaming consumer. This is also the
    // regression check for lazy listen_any on per-job channel names.
    await fetchJson(`${BRIDGE}/listen`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ event: channel }),
    });

    // Completion authority: the job's own terminal event
    // (Complete / Error) read from the replay ring.
    const deadline = Date.now() + 180_000;
    for (;;) {
      const recent = await fetchJson(`${BRIDGE}/events/recent`);
      const rows = (recent.rows as Array<{ event: string; payload: unknown }>).filter(
        (r) => r.event === channel,
      );
      const terminal = rows
        .map((r) => JSON.stringify(r.payload))
        .find((p) => /complete|error/i.test(p));
      if (terminal) {
        if (/error/i.test(terminal)) {
          throw new Error(`fixture corpus ingest failed: ${terminal}`);
        }
        break;
      }
      if (Date.now() > deadline) {
        throw new Error(
          rows.length === 0
            ? `fixture ingest emitted nothing on ${channel} within 180s — ` +
              `bridge listen_any regression or stalled job; see ${APP_LOG}`
            : `fixture ingest never reached a terminal event within 180s — see ${APP_LOG}`,
        );
      }
      await new Promise((r) => setTimeout(r, 1000));
    }
    console.log(`[real-setup] fixture corpus ingested ✓ (${corpusId})`);
  } else {
    console.log(`[real-setup] fixture corpus already present (${corpusId})`);
  }

  fs.writeFileSync(
    FIXTURE_INFO,
    JSON.stringify(
      {
        corpus_id: corpusId,
        display_name: FIXTURE_DISPLAY_NAME,
        corpus_dir: FIXTURE_CORPUS_DIR,
        attach_doc: FIXTURE_ATTACH_DOC,
      },
      null,
      2,
    ),
  );
}

/// Wait for a local-corpus ingest job to reach a terminal event on its
/// dynamic progress channel (shared by fixture + governance ingests).
async function waitForIngest(jobId: string, label: string): Promise<void> {
  const channel = `local-corpus://progress/${jobId}`;
  await fetchJson(`${BRIDGE}/listen`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ event: channel }),
  });
  const deadline = Date.now() + 180_000;
  for (;;) {
    const recent = await fetchJson(`${BRIDGE}/events/recent`);
    const rows = (recent.rows as Array<{ event: string; payload: unknown }>).filter(
      (r) => r.event === channel,
    );
    const terminal = rows
      .map((r) => JSON.stringify(r.payload))
      .find((p) => /complete|error/i.test(p));
    if (terminal) {
      if (/error/i.test(terminal)) throw new Error(`${label} ingest failed: ${terminal}`);
      return;
    }
    if (Date.now() > deadline) {
      throw new Error(`${label} ingest never reached a terminal event within 180s — see ${APP_LOG}`);
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
}

/// Ingest the governance folder as a REAL corpus, then overlay the
/// deterministic post-build atlas so it carries KNOWN conflicts without an
/// LLM enrich. After this, `notebook_list` reports `open_conflicts` for it
/// (the shelf chip + Conflicts tab gate) and `governance_get_view` returns
/// the four planted tensions — the surface `governance.real.spec.ts` drives.
async function plantGovernanceCorpus(): Promise<void> {
  const existing = await invoke<Array<{ corpus_id: string; display_name?: string }>>("lc_list");
  let corpusId = existing.find((c) => c.display_name === GOV_DISPLAY_NAME)?.corpus_id;

  if (!corpusId) {
    const validation = await invoke<{ exists: boolean; is_dir: boolean }>("lc_validate_path", {
      path: GOV_CORPUS_DIR,
    });
    if (!validation.exists || !validation.is_dir) {
      throw new Error(`governance corpus dir invalid: ${GOV_CORPUS_DIR}`);
    }
    const pre = await invoke<{ corpus_id: string; job_id: string }>(
      "lc_pre_scan",
      { path: GOV_CORPUS_DIR, sourceType: "folder", displayName: GOV_DISPLAY_NAME },
      60_000,
    );
    corpusId = pre.corpus_id;
    const jobId = await invoke<string>("lc_ingest", { corpusId, withOcr: false }, 60_000);
    await waitForIngest(jobId, "governance corpus");
    console.log(`[real-setup] governance corpus ingested ✓ (${corpusId})`);
  } else {
    console.log(`[real-setup] governance corpus already present (${corpusId})`);
  }

  // Overlay the checked-in post-build atlas. Path mirrors the desktop's
  // `atlas_dir(corpus_id)` = `<data.dir>/indexes/<id>/atlas`, where
  // data.dir is the test HOME's `.sovereign` (see the managed daemon config
  // in bakeProfile). Fail loudly if the ingest didn't land where we expect,
  // rather than silently overlaying into a dir the desktop won't read.
  const indexRoot = path.join(HOME, ".sovereign", "indexes", corpusId);
  if (!fs.existsSync(indexRoot)) {
    const listed = fs.existsSync(path.join(HOME, ".sovereign", "indexes"))
      ? fs.readdirSync(path.join(HOME, ".sovereign", "indexes")).join(", ")
      : "(no indexes dir)";
    throw new Error(
      `governance overlay: expected index root ${indexRoot} after ingest, ` +
        `but it is missing. Indexes present: ${listed}. The daemon's index ` +
        `layout may not be <data.dir>/indexes/<id>.`,
    );
  }
  const atlasDir = path.join(indexRoot, "atlas");
  fs.mkdirSync(atlasDir, { recursive: true });
  for (const f of ["atoms.json", "edges.json", "governance_oplog.jsonl"]) {
    fs.copyFileSync(path.join(GOV_ATLAS_FIXTURE, f), path.join(atlasDir, f));
  }
  fs.writeFileSync(
    GOV_FIXTURE_INFO,
    JSON.stringify({ corpus_id: corpusId, display_name: GOV_DISPLAY_NAME }, null, 2),
  );
  console.log(`[real-setup] governance atlas overlaid ✓ (${atlasDir})`);
}

/** The operator's `[[meshapp_installs]]` blocks, verbatim, from the host
 *  desktop.toml — or "" when there are none / the file is unreadable.
 *
 *  Sliced textually rather than parsed: these blocks are the tail of the
 *  file and TOML round-tripping would need a dependency the harness does
 *  not otherwise have. Anchored on the first `[[meshapp_installs]]` header,
 *  so anything above it (models, consent, window state) stays out. */
function hostMeshAppInstalls(): string {
  const candidates = [
    path.join(os.homedir(), "Library/Application Support/sovereign/desktop.toml"),
    path.join(os.homedir(), "Library/Application Support/svrnmesh/desktop.toml"),
    path.join(os.homedir(), ".config/sovereign/desktop.toml"),
    path.join(os.homedir(), ".config/svrnmesh/desktop.toml"),
  ];
  for (const file of candidates) {
    if (!fs.existsSync(file)) continue;
    let text: string;
    try {
      text = fs.readFileSync(file, "utf8");
    } catch {
      continue;
    }
    const at = text.indexOf("[[meshapp_installs]]");
    if (at < 0) continue;
    const blocks = text.slice(at).trimEnd();
    const ids = [...blocks.matchAll(/^app_id\s*=\s*"([^"]+)"/gm)].map((m) => m[1]);
    console.log(`[real-setup] demo: mirrored mesh-app grants from ${file} — ${ids.join(", ")}`);
    return `${blocks}\n`;
  }
  console.warn(
    "[real-setup] demo: no host [[meshapp_installs]] found — mesh-app beats (B3) " +
      "will deny with `app is not installed`",
  );
  return "";
}

/** System-3 ("tiered") enrichment tables — RAPTOR trees, skeletons, GLiNER
 *  entity mentions, vault themes. Every one is keyed by `corpus_id`, which is
 *  what makes a per-corpus projection possible at all.
 *
 *  A WHITELIST, deliberately. The daemon's `sovereign.db` also holds the
 *  operator's 4k conversations / 12k messages / memories / insights; a
 *  blacklist would leak them into frame the first time a table was added. */
const TIERED_TABLES = [
  "conv_skeletons",
  "conv_raptor_nodes",
  "conv_motifs",
  "conv_content_hash",
  "vault_themes",
  "chunk_entities",
  "chunk_entity_progress",
  "chunk_ner_processed",
] as const;

/** `[data] dir` from the host `~/.sovereign/config.toml` — the directory the
 *  attached daemon actually opens its `sovereign.db` in. Line-scanned for the
 *  same reason `hostModel()` in demo/global-setup.ts is. */
function hostDaemonDataDir(): string {
  const fallback = path.join(os.homedir(), ".sovereign");
  let text: string;
  try {
    text = fs.readFileSync(path.join(fallback, "config.toml"), "utf8");
  } catch {
    return fallback;
  }
  let inData = false;
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (line.startsWith("[")) {
      inData = line === "[data]";
      continue;
    }
    if (!inData || line.startsWith("#")) continue;
    const m = line.match(/^dir\s*=\s*"([^"]+)"/);
    if (m) return m[1].replace(/^~/, os.homedir());
  }
  return fallback;
}

/** Where the DESKTOP opens its store: `DesktopConfig::data_dir`, whose default
 *  is `dirs::data_dir()/sovereign` under the (scratch) HOME. */
function desktopDataDir(): string {
  return process.platform === "darwin"
    ? path.join(HOME, "Library/Application Support/sovereign")
    : path.join(process.env.XDG_DATA_HOME ?? path.join(HOME, ".local/share"), "sovereign");
}

/** Project the daemon's tiered enrichment for the filmed corpora into the
 *  scratch profile's `sovereign.db`.
 *
 *  WHY THIS EXISTS. In attach mode the desktop still opens its OWN store at
 *  `config.data_dir/sovereign.db`, and `data_dir` is only ever pointed at the
 *  CLI's `[data] dir` by `save_setup` — i.e. by walking the setup flow, which
 *  a baked profile never does. (The operator's real install DID walk it: its
 *  desktop.toml carries `data_dir = ~/.sovereign`, which is why the real app
 *  shows the vault's 322 enriched notes and the demo profile shows none.) The
 *  six `atlas_*conv*` commands read that store directly with no attach-mode
 *  branch, and the daemon exposes no atlas route to branch to — so under a
 *  scratch profile the Explore surface for a tiered corpus is structurally
 *  empty no matter how enriched the corpus is.
 *
 *  The obvious shortcut — bake `data_dir = ~/.sovereign` — is rejected: that
 *  file is also the conversation store, so the reel would film the operator's
 *  4,277 real threads AND write its own into them. §1 Posture in DEMO_BEATS.md
 *  is explicit that conversations stay scratch.
 *
 *  So: same idiom as the `indexes/` symlink above (host knowledge, scratch
 *  profile), at the granularity the shared-file conflation forces — table-and-
 *  corpus scoped rows, copied. The DATA is the daemon's real enrichment output,
 *  unmodified; only its location is projected. Retires when the desktop can
 *  read the daemon's tiered map over HTTP in attach mode.
 *
 *  Idempotent (rows are deleted then re-inserted per corpus), and a no-op with
 *  a warning if anything is missing — B4 then skips with its own honest gate
 *  message rather than filming an empty tree. */
function projectHostTieredMap(): void {
  const corpora = (
    process.env.SOVEREIGN_DEMO_TIERED_CORPORA ??
    process.env.SOVEREIGN_DEMO_ATLAS_CORPUS ??
    "obsidian-vault-959ee8a8f330"
  )
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  if (corpora.length === 0) return;

  try {
    execSync("command -v sqlite3", { stdio: "ignore" });
  } catch {
    console.warn("[real-setup] demo: sqlite3 not on PATH — tiered map not projected (B4 will skip)");
    return;
  }

  const hostDb = path.join(hostDaemonDataDir(), "sovereign.db");
  if (!fs.existsSync(hostDb)) {
    console.warn(`[real-setup] demo: daemon store ${hostDb} missing — tiered map not projected`);
    return;
  }
  const targetDir = desktopDataDir();
  fs.mkdirSync(targetDir, { recursive: true });
  const targetDb = path.join(targetDir, "sovereign.db");

  const sq = (db: string, sql: string): string =>
    execSync(`sqlite3 ${JSON.stringify(db)}`, { input: sql, encoding: "utf8" }).trim();
  const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
  const inList = corpora.map(lit).join(",");

  try {
    // Only tables this daemon build actually has — a stale/newer store must
    // degrade to "fewer tables projected", never to a failed transaction.
    const present = new Set(
      sq(hostDb, "SELECT name FROM sqlite_master WHERE type='table';").split("\n").map((s) => s.trim()),
    );
    const tables = TIERED_TABLES.filter((t) => present.has(t));
    if (tables.length === 0) {
      console.warn(`[real-setup] demo: no tiered tables in ${hostDb} — is the corpus enriched?`);
      return;
    }

    // The desktop's own migrations create these on first open, but the profile
    // may be brand new (bake runs before launch). Carry the DDL over, made
    // re-runnable — `.schema` also emits the indexes, which are not.
    // `sql || ';'` so each row is already a terminated statement — the DDL is
    // multi-line, so neither splitting on ';' nor on '\n' would survive it.
    const ddl = sq(
      hostDb,
      tables
        .map((t) => `SELECT sql || ';' FROM sqlite_master WHERE tbl_name=${lit(t)} AND sql IS NOT NULL;`)
        .join("\n"),
    )
      .replace(/^CREATE TABLE (?!IF NOT EXISTS)/gim, "CREATE TABLE IF NOT EXISTS ")
      .replace(/^CREATE (UNIQUE )?INDEX (?!IF NOT EXISTS)/gim, "CREATE $1INDEX IF NOT EXISTS ");
    sq(targetDb, ddl);

    sq(
      targetDb,
      [
        `ATTACH DATABASE ${lit(hostDb)} AS src;`,
        "BEGIN;",
        ...tables.flatMap((t) => [
          `DELETE FROM main.${t} WHERE corpus_id IN (${inList});`,
          `INSERT INTO main.${t} SELECT * FROM src.${t} WHERE corpus_id IN (${inList});`,
        ]),
        "COMMIT;",
      ].join("\n"),
    );

    const counts = sq(
      targetDb,
      tables
        .map((t) => `SELECT ${lit(t)} || '=' || count(*) FROM ${t} WHERE corpus_id IN (${inList});`)
        .join("\n"),
    )
      .split("\n")
      .filter((l) => !l.endsWith("=0"))
      .join(" ");
    console.log(
      `[real-setup] demo: projected daemon tiered map for {${corpora.join(",")}} → ` +
        `${targetDb}\n[real-setup]   ${counts}`,
    );
  } catch (e) {
    console.warn(`[real-setup] demo: tiered-map projection failed (${e}) — B4 will skip`);
  }
}

function bakeProfile(): void {
  if (!process.env.SOVEREIGN_REAL_KEEP_PROFILE) {
    fs.rmSync(PROFILE, { recursive: true, force: true });
  }
  // dirs::config_dir() is platform-specific — XDG (~/.config) on Linux,
  // ~/Library/Application Support on macOS — and the Rust desktop reads
  // desktop.toml from whichever applies (state/config.rs). Bake to both
  // so the hermetic harness works cross-platform; the off-platform copy
  // is harmless scratch under the wiped HOME.
  const configDirs = [
    path.join(HOME, ".config/sovereign"),
    path.join(HOME, "Library/Application Support/sovereign"),
  ];
  for (const d of configDirs) fs.mkdirSync(d, { recursive: true });
  fs.mkdirSync(path.join(HOME, ".local/share"), { recursive: true });
  fs.mkdirSync(path.join(HOME, ".cache"), { recursive: true });

  const chatModel = process.env.SOVEREIGN_REAL_CHAT_MODEL ?? DEFAULT_CHAT_MODEL;
  const embedModel = process.env.SOVEREIGN_REAL_EMBED_MODEL ?? DEFAULT_EMBED_MODEL;
  for (const m of [chatModel, embedModel]) {
    if (!fs.existsSync(m)) {
      throw new Error(
        `real-mode setup: model not found: ${m}\n` +
          `Point SOVEREIGN_REAL_CHAT_MODEL / SOVEREIGN_REAL_EMBED_MODEL at real GGUFs.`,
      );
    }
  }

  // Tilde-relative model paths in any daemon-side config resolve under
  // the scratch HOME — keep them valid via a symlink to the real dir.
  const sovDir = path.join(HOME, ".sovereign");
  fs.mkdirSync(sovDir, { recursive: true });
  const modelsLink = path.join(sovDir, "models");
  if (!fs.existsSync(modelsLink)) {
    fs.symlinkSync(path.join(REPO_ROOT, "sovereign/models"), modelsLink);
  }

  // Demo mode films the OPERATOR'S real shelf, so the Library has to see the
  // operator's real corpora. Attach mode routes every *query* at the live
  // daemon, but the desktop resolves the CorpusEngine's index/recipe dirs from
  // `dirs::home_dir()` (state.rs: `home.join(".sovereign").join("indexes")`) —
  // NOT from config.toml's `[data] dir`. Under the scratch HOME that dir is
  // empty, so `notebook_list` (which spines off `engine.installed_indexes()`)
  // returns nothing and the shelf renders `library-empty`. Symlink the host
  // dirs in so the engine's read path is the real one, exactly as it is in a
  // normal install. Safe because SOVEREIGN_DEMO also skips every fixture
  // plant below — demo mode reads the shelf, it never ingests into it.
  if (process.env.SOVEREIGN_DEMO === "1") {
    const hostSov = path.join(os.homedir(), ".sovereign");
    const linked: string[] = [];
    for (const name of ["indexes", "recipes", "local-corpora"]) {
      const target = path.join(hostSov, name);
      const link = path.join(sovDir, name);
      if (!fs.existsSync(target)) {
        console.warn(`[real-setup] demo: host ${target} missing — shelf may be thin`);
        continue;
      }
      if (!fs.existsSync(link)) fs.symlinkSync(target, link);
      linked.push(name);
    }
    console.log(`[real-setup] demo: linked host ~/.sovereign/{${linked.join(",")}} into scratch HOME`);

    // The symlinks above cover the FILESYSTEM half of the daemon's knowledge
    // (indexes, recipes, corpus registry). The tiered enrichment half lives in
    // SQLite, in the same file as the operator's conversations, so it can't be
    // symlinked wholesale — see projectHostTieredMap().
    projectHostTieredMap();
  }

  // Attach mode has the SAME split-brain, in the write direction: the harness's
  // ingests and the authoring tools' writes are served by the REAL daemon, which
  // resolves its data dir from ITS config (`[data] dir`, the host ~/.sovereign) —
  // while the fixtures and specs assert paths under the scratch HOME. That
  // mismatch is why the attach path could never reach a spec: `plantGovernanceCorpus`
  // died asserting `<scratch>/.sovereign/indexes/<id>` for a corpus the daemon had
  // just written to `<host>/.sovereign/indexes/<id>`, and the workflow-author spec
  // watched a `workflows/` dir nothing would ever write to. Link the two dirs the
  // daemon OWNS (it writes them; the desktop and the specs only read them) so both
  // sides name the same bytes.
  //
  // Deliberately NOT linked: `local-corpora` (the desktop-side registry). Keeping
  // it scratch means an attach run never registers "E2E Fixture Corpus" /
  // "Maple House (E2E)" onto the operator's real Library shelf — the cost is
  // re-ingesting the two tiny fixture folders per run, which is the right trade.
  // Attach mode is already declared non-hermetic for exactly this kind of state.
  if (!MANAGED_DAEMON && process.env.SOVEREIGN_DEMO !== "1") {
    const hostSov = path.join(os.homedir(), ".sovereign");
    const linked: string[] = [];
    for (const name of ["indexes", "workflows"]) {
      const target = path.join(hostSov, name);
      const link = path.join(sovDir, name);
      // `workflows/` may not exist yet on a machine that has never authored one —
      // create it host-side rather than skipping, or the authoring spec's write
      // lands in a dir the harness isn't watching.
      if (!fs.existsSync(target)) fs.mkdirSync(target, { recursive: true });
      if (!fs.existsSync(link)) fs.symlinkSync(target, link);
      linked.push(name);
    }
    console.log(
      `[real-setup] attach: linked host ~/.sovereign/{${linked.join(",")}} into scratch HOME ` +
        `— ingests and authored artifacts land in the REAL daemon's data dir (non-hermetic, by design)`,
    );
  }

  // Attach mode reads `~/.sovereign/config.toml` (SetupConfig) to learn which
  // model ids to route to the running daemon (state/builders/inference.rs). The
  // hermetic profile only bakes desktop.toml (Local-mode config), so attach boot
  // fails without this. Mirror the HOST's real config — same machine, so its
  // model ids match the daemon's loaded slots. Default (non-attach) mode loads
  // its own model from desktop.toml and doesn't need this.
  if (MANAGED_DAEMON) {
    // The harness owns the daemon: this file is BOTH the daemon's config (which
    // models to load, where its data lives) and the desktop's attach SetupConfig.
    // A fixed local model pair + the test HOME's data dir → a fixture-scoped
    // daemon whose index dir is the desktop's read path. The desktop derives its
    // routed model stems from desktop.toml (baked to the SAME chatModel below),
    // so the ids line up with the daemon's loaded slots.
    const daemonConfig = [
      `mcp_servers = []`,
      ``,
      `[models]`,
      `primary = ${JSON.stringify(chatModel)}`,
      `fast = ${JSON.stringify(chatModel)}`,
      `embed = ${JSON.stringify(embedModel)}`,
      `context_size = 32768`,
      ``,
      `[daemon]`,
      `client_port = 9741`,
      `internal_port = 9742`,
      `autostart = false`,
      `client_bind = "127.0.0.1"`,
      ``,
      `[data]`,
      `dir = ${JSON.stringify(sovDir)}`,
      ``,
      `[iroh]`,
      `enabled = false`,
      ``,
    ].join("\n");
    fs.writeFileSync(path.join(sovDir, "config.toml"), daemonConfig);
    console.log("[real-setup] managed-daemon: wrote fixture-scoped daemon config (small models, test HOME)");
  } else if (process.env.SOVEREIGN_REAL_ALLOW_ATTACH === "1") {
    const realConfig = path.join(os.homedir(), ".sovereign", "config.toml");
    if (fs.existsSync(realConfig)) {
      fs.copyFileSync(realConfig, path.join(sovDir, "config.toml"));
      console.log("[real-setup] attach mode: mirrored host ~/.sovereign/config.toml for daemon routing");
    } else {
      console.warn(`[real-setup] attach mode: host ${realConfig} missing — daemon routing may fail`);
    }
  }

  const desktopToml = [
    `# Generated by tests/e2e/real/global-setup.ts — hermetic real-mode profile.`,
    `model_path = ${JSON.stringify(chatModel)}`,
    `primary_model_path = ${JSON.stringify(chatModel)}`,
    `embed_model_path = ${JSON.stringify(embedModel)}`,
    `setup_complete = true`,
    `auto_collaborate = false`,
    ``,
    // Mesh-app grants are per-profile config, and every `meshapp_*` command is
    // fail-closed on them (`authorize`: not-a-mesh-app-window → not-installed →
    // permission-not-granted). A profile without them denies every mesh-app op,
    // which surfaces to a beat as "this corpus has no atlas" — the atlas is
    // fine, the CALLER was never granted read. Carry the operator's grants in
    // for demo mode; the real suite keeps its hermetic empty set.
    ...(process.env.SOVEREIGN_DEMO === "1" ? [hostMeshAppInstalls()] : []),
  ].join("\n");
  for (const d of configDirs) fs.writeFileSync(path.join(d, "desktop.toml"), desktopToml);
}

/** Start the harness-owned daemon (HOME = test profile) and wait until it serves
 *  `/v1/models`. `daemon start` blocks until the daemon reports ready, but we
 *  re-probe the client port so a mis-started daemon fails here, loudly, rather
 *  than as a confusing mid-journey inference error. Stopped in global-teardown. */
async function startManagedDaemon(): Promise<void> {
  console.log("[real-setup] managed-daemon: starting fixture-scoped daemon (HOME=test profile)…");
  const env = {
    ...process.env,
    HOME,
    XDG_CONFIG_HOME: path.join(HOME, ".config"),
    XDG_DATA_HOME: path.join(HOME, ".local/share"),
    XDG_CACHE_HOME: path.join(HOME, ".cache"),
  };
  execSync(`${JSON.stringify(DAEMON_BIN)} daemon start`, {
    env,
    stdio: "inherit",
    timeout: 5 * 60 * 1000,
  });
  const deadline = Date.now() + 60_000;
  while (Date.now() < deadline) {
    try {
      const r = await fetchJson("http://127.0.0.1:9741/v1/models");
      if (Array.isArray((r as { data?: unknown }).data)) {
        console.log("[real-setup] managed-daemon: ready on :9741");
        return;
      }
    } catch {
      /* not up yet */
    }
    await new Promise((res) => setTimeout(res, 1000));
  }
  throw new Error("managed-daemon: not serving /v1/models on :9741 within 60s of `daemon start`");
}

export default async function globalSetup(): Promise<void> {
  fs.mkdirSync(RESULTS, { recursive: true });
  fs.rmSync(LEDGER_REAL, { force: true });

  // ── Guard: managed mode (the default) needs :9741 free to start its own
  // fixture-scoped daemon; attach mode (opt-out) needs a daemon already there.
  if (await portInUse(9741)) {
    if (MANAGED_DAEMON) {
      throw new Error(
        "real-mode setup: managed mode (the default) needs :9741 free to start " +
          "its own fixture-scoped daemon, but something is already listening " +
          "there. Stop it (`sovereign daemon stop`) first, or set " +
          "SOVEREIGN_REAL_ALLOW_ATTACH=1 to attach to it instead (non-hermetic).",
      );
    } else {
      console.warn(
        "[real-setup] :9741 is occupied — proceeding in ATTACH mode " +
          "(SOVEREIGN_REAL_ALLOW_ATTACH=1). Knowledge/inference state is the " +
          "REAL daemon's; conversations/config remain scratch.",
      );
    }
  } else if (!MANAGED_DAEMON) {
    // Attach requested but nothing is listening — fail loudly rather than
    // silently booting an embedded backend that can't ingest (the daemon owns
    // ingest+enrich; see local_corpus_commands.rs).
    throw new Error(
      "real-mode setup: SOVEREIGN_REAL_ALLOW_ATTACH=1 but no daemon is " +
        "listening on :9741. Start one (`sovereign daemon start`) or unset " +
        "the flag to use the default managed daemon.",
    );
  }

  // ── Build: embedded frontend assets + the debug binary ──
  if (!fs.existsSync(path.join(CRATE_ROOT, "dist/index.html"))) {
    console.log("[real-setup] dist/ missing — npm run build");
    execSync("npm run build", { cwd: CRATE_ROOT, stdio: "inherit" });
  }
  // Managed mode ALSO runs `target/debug/sovereign-cli-daemon`, and that
  // process — not the desktop — owns ingest+enrich. Building only the
  // desktop let a stale daemon binary serve the fixture ingests: a fixed
  // engine bug reproduced verbatim on the next run, with the error text
  // pointing at source that no longer existed (2026-07-24). Build both,
  // in one invocation so cargo resolves one feature set for the shared
  // deps instead of thrashing the target dir between two narrow builds.
  const buildPkgs = MANAGED_DAEMON
    ? "-p sovereign-desktop -p sovereign-cli-daemon"
    : "-p sovereign-desktop";
  console.log(`[real-setup] cargo build ${buildPkgs} (debug)`);
  execSync(`cargo build ${buildPkgs}`, {
    cwd: REPO_ROOT,
    stdio: "inherit",
    timeout: 20 * 60 * 1000,
  });

  bakeProfile();

  // ── Managed daemon: start the harness-owned fixture-scoped daemon before the
  // desktop boots, so the app Attaches to it and the fixture ingest lands in the
  // shared (test-HOME) index dir. ──
  if (MANAGED_DAEMON) {
    await startManagedDaemon();
  }

  // ── Launch ──
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    HOME,
    XDG_CONFIG_HOME: path.join(HOME, ".config"),
    XDG_DATA_HOME: path.join(HOME, ".local/share"),
    XDG_CACHE_HOME: path.join(HOME, ".cache"),
    SOVEREIGN_COMMAND_BRIDGE: "1",
    SOVEREIGN_COMMAND_BRIDGE_LEDGER: LEDGER_REAL,
    RUST_LOG: process.env.RUST_LOG ?? "sovereign_desktop=info",
  };
  const useXvfb = process.env.SOVEREIGN_REAL_XVFB === "1";
  const cmd = useXvfb ? "xvfb-run" : APP_BIN;
  const args = useXvfb ? ["-a", APP_BIN] : [];

  const log = fs.openSync(APP_LOG, "w");
  const child = spawn(cmd, args, {
    env,
    cwd: os.homedir(), // not the repo — catch accidental cwd-relative writes
    stdio: ["ignore", log, log],
    detached: true,
  });
  child.unref();
  if (!child.pid) throw new Error("real-mode setup: failed to spawn app");
  fs.writeFileSync(PID_FILE, String(child.pid));
  console.log(`[real-setup] app pid=${child.pid}, log=${APP_LOG}`);

  // ── Readiness: bridge up, then backend-ready (sticky replay) ──
  const deadline = Date.now() + 180_000;
  let bridgeUp = false;
  while (Date.now() < deadline) {
    try {
      const h = await fetchJson(`${BRIDGE}/healthz`);
      if (h.ok) {
        bridgeUp = true;
        break;
      }
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  if (!bridgeUp) throw new Error(`real-mode setup: bridge never came up — see ${APP_LOG}`);

  let ready = false;
  while (Date.now() < deadline) {
    try {
      const r = await fetchJson(`${BRIDGE}/listen`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ event: "backend-ready" }),
      });
      if (r.replayed) {
        console.log("[real-setup] backend-ready ✓");
        ready = true;
        break;
      }
      const s = await fetchJson(`${BRIDGE}/listen`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ event: "setup-required" }),
      });
      if (s.replayed) {
        throw new Error(
          "real-mode setup: app routed to the setup wizard — the baked " +
            "desktop.toml didn't satisfy the boot guard (model path? " +
            `setup_complete?). See ${APP_LOG}`,
        );
      }
    } catch (e) {
      if (e instanceof Error && e.message.startsWith("real-mode setup:")) throw e;
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  if (!ready) {
    throw new Error(
      `real-mode setup: backend-ready never fired within 180s — see ${APP_LOG}`,
    );
  }
  // Demo mode (tests/e2e/demo) attaches to the operator's REAL daemon to
  // film real corpora. Planting the fixture + governance corpora there
  // would both pollute that index and put "E2E Fixture Corpus" / "Maple
  // House (E2E)" on camera in the Library shelf. Skip them; no demo beat
  // reads either fixture.
  if (process.env.SOVEREIGN_DEMO === "1") {
    console.log("[real-setup] SOVEREIGN_DEMO=1 — skipping fixture + governance corpus plants");
    return;
  }
  // Outside the readiness retry loop: an ingest failure is a hard
  // setup error, never silently retried.
  await ingestFixtureCorpus();
  await plantGovernanceCorpus();
}
