//! Build-time copy of bundled filter assets into `OUT_DIR`.
//!
//! Generated data files (Vital Articles L5, future rank lists) live in
//! the sibling `sovereign-recipes` repo alongside the scripts that
//! produce them — single source of truth. corpus-engine consumes them
//! at compile time via `include_bytes!(concat!(env!("OUT_DIR"), …))`,
//! so this build script copies the on-disk files into the per-build
//! `OUT_DIR` Cargo provides.
//!
//! Why not commit the data files in this crate?
//!   - The text file is generated by a Python script in
//!     `sovereign-recipes/wikipedia/scripts/`. Two copies in two repos
//!     drift.
//!   - "Generated artefact tracked under source control" is a smell.
//!   - corpus-engine is always built inside the commonwealth-ai
//!     workspace where `sovereign-recipes` is a sibling, so the
//!     compile-time path is stable.
//!
//! If you need to rebuild offline without the sibling repo (e.g. a
//! standalone clone of corpus-engine), set
//! `CORPUS_ENGINE_DATA_DIR=<path>` to a directory containing the asset
//! filenames listed in `BUNDLED_ASSETS` and the build script will use
//! it as a fallback before the workspace path.

use std::path::PathBuf;

/// Filenames the build script must place into `OUT_DIR`. Any new
/// bundled asset added to `corpus-engine/src/filters/assets.rs` must
/// also appear here, otherwise the `include_bytes!` macro fails at
/// the next build with a missing-file error.
const BUNDLED_ASSETS: &[&str] = &[
    "vital_articles_l1.txt",
    "vital_articles_l2.txt",
    "vital_articles_l3.txt",
    "vital_articles_l4.txt",
    "vital_articles_l5.txt",
];

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // Resolution order:
    //   1. CORPUS_ENGINE_DATA_DIR env override (escape hatch for
    //      airgapped / standalone clones).
    //   2. Workspace-sibling path: `<manifest>/../sovereign-recipes/
    //      wikipedia/data/`. The common case.
    let candidates: Vec<PathBuf> = {
        let mut v = Vec::new();
        if let Ok(env_dir) = std::env::var("CORPUS_ENGINE_DATA_DIR") {
            v.push(PathBuf::from(env_dir));
        }
        v.push(
            manifest_dir
                .parent()
                .expect("corpus-engine manifest must have a parent dir")
                .join("sovereign-recipes")
                .join("wikipedia")
                .join("data"),
        );
        v
    };

    for asset in BUNDLED_ASSETS {
        let src = match find_asset(asset, &candidates) {
            Some(p) => p,
            None => {
                eprintln!(
                    "cargo:warning=corpus-engine build.rs: '{asset}' not found in any of:"
                );
                for c in &candidates {
                    eprintln!("cargo:warning=  - {}", c.join(asset).display());
                }
                eprintln!(
                    "cargo:warning=  Regenerate via sovereign-recipes/wikipedia/scripts/build_vital_articles.py"
                );
                eprintln!(
                    "cargo:warning=  or set CORPUS_ENGINE_DATA_DIR to a directory containing {asset}"
                );
                panic!("required bundled asset '{asset}' missing");
            }
        };
        let dest = out_dir.join(asset);
        std::fs::copy(&src, &dest).unwrap_or_else(|e| {
            panic!(
                "copy {} -> {} failed: {e}",
                src.display(),
                dest.display()
            )
        });
        // Re-run the build script (and recompile dependents) when the
        // source file changes. Without this, regenerating
        // vital_articles_l5.txt in sovereign-recipes wouldn't
        // invalidate the cached corpus-engine build.
        println!("cargo:rerun-if-changed={}", src.display());
    }

    // Trigger a re-run when CORPUS_ENGINE_DATA_DIR changes between
    // builds (e.g. switching between a workspace and a standalone
    // checkout in CI).
    println!("cargo:rerun-if-env-changed=CORPUS_ENGINE_DATA_DIR");
    // The build script itself also needs explicit rerun-if so Cargo
    // doesn't reuse a stale OUT_DIR after editing the script.
    println!("cargo:rerun-if-changed=build.rs");
}

fn find_asset(name: &str, candidates: &[PathBuf]) -> Option<PathBuf> {
    for dir in candidates {
        let p = dir.join(name);
        if p.is_file() {
            return Some(p);
        }
    }
    None
}
