// SPDX-License-Identifier: AGPL-3.0-or-later
//! `max_file_size` structural goal — every source file in the
//! workdir must be ≤ N lines. One template per framework; the
//! template is concrete-language test code that walks the workdir
//! and asserts the line-count budget.
//!
//! Single source of truth per (framework × max_lines) cell. Tasks
//! call [`render`] and write the result; the solver loop's
//! `MaximizePassing` polarity then drives the model toward passing
//! the generated test.

use std::path::PathBuf;

use crate::tasks::framework::Framework;

/// Render the (test_file_path, test_content) pair for the given
/// framework + line budget. The path is workdir-relative; the
/// caller writes the content there.
pub fn render(framework: Framework, max_lines: usize) -> (PathBuf, String) {
    match framework {
        Framework::Pytest => (
            PathBuf::from("tests/test_max_file_size.py"),
            pytest_template(max_lines),
        ),
        Framework::Cargo => (
            PathBuf::from("tests/max_file_size.rs"),
            cargo_template(max_lines),
        ),
        Framework::Vitest => (
            PathBuf::from("tests/max_file_size.test.ts"),
            vitest_template(max_lines),
        ),
        Framework::Jest => (
            PathBuf::from("tests/max_file_size.test.ts"),
            jest_template(max_lines),
        ),
        Framework::GoTest => (
            PathBuf::from("max_file_size_test.go"),
            gotest_template(max_lines),
        ),
    }
}

fn pytest_template(max_lines: usize) -> String {
    format!(
        r#""""Structural assertion — generated by tasks::structural::max_file_size."""

import os


def _source_files():
    root = os.path.dirname(os.path.dirname(__file__))
    out = []
    skip = {{"__pycache__", ".pytest_cache", "tests", "build", "dist", "node_modules", ".git", "target"}}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip and not d.startswith(".")]
        for f in filenames:
            if f.endswith(".py"):
                out.append(os.path.join(dirpath, f))
    return out


def _line_count(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return sum(1 for _ in f)


def test_max_file_size():
    limit = {max_lines}
    over = []
    for f in _source_files():
        n = _line_count(f)
        if n > limit:
            over.append((os.path.relpath(f), n))
    assert not over, f"files over {{limit}} lines: {{over}}"
"#
    )
}

fn cargo_template(max_lines: usize) -> String {
    // Cargo integration test — lives at tests/max_file_size.rs.
    // Walks CARGO_MANIFEST_DIR for .rs files, skips build dirs, and
    // asserts the line-count budget.
    format!(
        r#"//! Structural assertion — generated by tasks::structural::max_file_size.

use std::fs;
use std::path::{{Path, PathBuf}};

const MAX_LINES: usize = {max_lines};

fn walk(dir: &Path, out: &mut Vec<(PathBuf, usize)>) {{
    const SKIP: &[&str] = &["target", "node_modules", ".git", "tests", "build", "dist"];
    let Ok(rd) = fs::read_dir(dir) else {{ return }};
    for entry in rd.flatten() {{
        let name = entry.file_name();
        let s = name.to_string_lossy();
        if SKIP.iter().any(|x| *x == s) || s.starts_with('.') {{
            continue;
        }}
        let p = entry.path();
        let Ok(ft) = entry.file_type() else {{ continue }};
        if ft.is_dir() {{
            walk(&p, out);
        }} else if ft.is_file() && p.extension().and_then(|e| e.to_str()) == Some("rs") {{
            if let Ok(text) = fs::read_to_string(&p) {{
                out.push((p.clone(), text.lines().count()));
            }}
        }}
    }}
}}

#[test]
fn max_file_size() {{
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let mut all: Vec<(PathBuf, usize)> = Vec::new();
    walk(&root, &mut all);
    let over: Vec<_> = all.iter().filter(|(_, n)| *n > MAX_LINES).collect();
    assert!(
        over.is_empty(),
        "files over {{}} lines: {{:?}}",
        MAX_LINES,
        over.iter().map(|(p, n)| (p.display().to_string(), n)).collect::<Vec<_>>()
    );
}}
"#
    )
}

fn vitest_template(max_lines: usize) -> String {
    format!(
        r#"// Structural assertion — generated by tasks::structural::max_file_size.

import {{ test, expect }} from 'vitest';
import {{ readdirSync, statSync, readFileSync }} from 'node:fs';
import {{ join }} from 'node:path';

const MAX_LINES = {max_lines};
const EXTS = new Set(['.ts', '.tsx', '.js', '.jsx']);
const SKIP = new Set(['node_modules', 'tests', 'dist', 'build', '.git', 'target']);

function walk(dir, out) {{
  for (const name of readdirSync(dir)) {{
    if (SKIP.has(name) || name.startsWith('.')) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else if (st.isFile()) {{
      const dot = name.lastIndexOf('.');
      const ext = dot >= 0 ? name.slice(dot) : '';
      if (EXTS.has(ext)) {{
        const n = readFileSync(p, 'utf8').split('\n').length;
        out.push([p, n]);
      }}
    }}
  }}
}}

test('max_file_size', () => {{
  const all = [];
  walk(process.cwd(), all);
  const over = all.filter(([, n]) => n > MAX_LINES);
  expect(over).toEqual([]);
}});
"#
    )
}

fn jest_template(max_lines: usize) -> String {
    // Jest's API differs only at the import line vs vitest. Same
    // body underneath. Template kept separate so future per-runner
    // adjustments (jest.config quirks, etc) don't fork from one
    // file.
    format!(
        r#"// Structural assertion — generated by tasks::structural::max_file_size.

import {{ readdirSync, statSync, readFileSync }} from 'fs';
import {{ join }} from 'path';

const MAX_LINES = {max_lines};
const EXTS = new Set(['.ts', '.tsx', '.js', '.jsx']);
const SKIP = new Set(['node_modules', 'tests', 'dist', 'build', '.git', 'target']);

function walk(dir, out) {{
  for (const name of readdirSync(dir)) {{
    if (SKIP.has(name) || name.startsWith('.')) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else if (st.isFile()) {{
      const dot = name.lastIndexOf('.');
      const ext = dot >= 0 ? name.slice(dot) : '';
      if (EXTS.has(ext)) {{
        const n = readFileSync(p, 'utf8').split('\n').length;
        out.push([p, n]);
      }}
    }}
  }}
}}

test('max_file_size', () => {{
  const all = [];
  walk(process.cwd(), all);
  const over = all.filter(([, n]) => n > MAX_LINES);
  expect(over).toEqual([]);
}});
"#
    )
}

fn gotest_template(max_lines: usize) -> String {
    // Go convention: foo_test.go alongside source; uses
    // testing.T. Walks via filepath.Walk.
    format!(
        r#"// Structural assertion — generated by tasks::structural::max_file_size.

package main

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const maxLines = {max_lines}

func TestMaxFileSize(t *testing.T) {{
	root, err := os.Getwd()
	if err != nil {{ t.Fatal(err) }}
	skip := map[string]bool{{"target": true, "node_modules": true, "tests": true, "build": true, "dist": true, ".git": true}}
	var over []string
	err = filepath.Walk(root, func(p string, info os.FileInfo, err error) error {{
		if err != nil {{ return nil }}
		name := info.Name()
		if info.IsDir() {{
			if skip[name] || strings.HasPrefix(name, ".") {{ return filepath.SkipDir }}
			return nil
		}}
		if !strings.HasSuffix(name, ".go") {{ return nil }}
		body, err := ioutil.ReadFile(p)
		if err != nil {{ return nil }}
		n := strings.Count(string(body), "\n") + 1
		if n > maxLines {{ over = append(over, p) }}
		return nil
	}})
	if err != nil {{ t.Fatal(err) }}
	if len(over) > 0 {{ t.Errorf("files over %d lines: %v", maxLines, over) }}
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pytest_template_bakes_max_lines() {
        let (path, content) = render(Framework::Pytest, 30);
        assert_eq!(path, PathBuf::from("tests/test_max_file_size.py"));
        assert!(content.contains("limit = 30"));
        assert!(content.contains("def test_max_file_size"));
    }

    #[test]
    fn cargo_template_bakes_max_lines() {
        let (path, content) = render(Framework::Cargo, 50);
        assert_eq!(path, PathBuf::from("tests/max_file_size.rs"));
        assert!(content.contains("MAX_LINES: usize = 50"));
        assert!(content.contains("#[test]"));
        assert!(content.contains("fn max_file_size"));
    }

    #[test]
    fn vitest_template_uses_vitest_imports() {
        let (path, content) = render(Framework::Vitest, 100);
        assert_eq!(path, PathBuf::from("tests/max_file_size.test.ts"));
        assert!(content.contains("from 'vitest'"));
        assert!(content.contains("MAX_LINES = 100"));
    }

    #[test]
    fn jest_template_uses_node_imports() {
        let (_path, content) = render(Framework::Jest, 80);
        assert!(content.contains("from 'fs'"));
        assert!(!content.contains("from 'node:fs'"));
        assert!(content.contains("MAX_LINES = 80"));
    }

    #[test]
    fn gotest_template_uses_go_test_convention() {
        let (path, content) = render(Framework::GoTest, 200);
        assert_eq!(path, PathBuf::from("max_file_size_test.go"));
        assert!(content.contains("func TestMaxFileSize"));
        assert!(content.contains("maxLines = 200"));
    }
}
