// SPDX-License-Identifier: AGPL-3.0-or-later
//! `max_file_size` structural goal — every source file in the
//! workdir must be ≤ N lines. One template per framework; the
//! template is concrete-language test code that walks the workdir
//! and asserts the line-count budget.
//!
//! LADDER (ported from the agent-bench generalization work,
//! 2026-07-07): a single threshold makes a refactor a CLIFF — every
//! extraction that shrinks the largest file but doesn't reach the
//! final budget scores as a tie under `MaximizePassing` and is
//! discarded (proven on 3.3-calc-split: real progress thrown away
//! 14 times, then reproduced and fixed via rung tests; the ladder
//! class scored 8/9 first-try on held-out material). `render_ladder`
//! therefore emits one test per RUNG — intermediate thresholds
//! descending to the target — so each extraction step flips a rung
//! and is promoted.
//!
//! Single source of truth per (framework × rungs) cell. Tasks call
//! [`render_ladder`] (or single-rung [`render`]) and write the
//! result; the solver loop's `MaximizePassing` polarity then climbs
//! the generated tests.

use std::path::PathBuf;

use crate::tasks::framework::Framework;

/// Intermediate thresholds from the CURRENT worst file size down to
/// the target: up to three evenly-spaced rungs plus the target
/// itself, descending. `current_worst <= target` degenerates to just
/// the target (nothing to climb).
pub fn ladder_rungs(target: usize, current_worst: usize) -> Vec<usize> {
    if current_worst <= target {
        return vec![target];
    }
    let span = current_worst - target;
    let mut rungs: Vec<usize> = (1..=3)
        .rev()
        .map(|k| target + span * k / 4)
        .filter(|r| *r < current_worst && *r > target)
        .collect();
    rungs.push(target);
    rungs.dedup();
    rungs
}

/// Render the (test_file_path, test_content) pair for the given
/// framework + single line budget. Kept for callers with no ladder
/// context; equivalent to `render_ladder(framework, &[max_lines])`.
pub fn render(framework: Framework, max_lines: usize) -> (PathBuf, String) {
    render_ladder(framework, &[max_lines])
}

/// Render the ladder version: one generated test per rung, shared
/// walker. Rungs should be descending; the final entry is the goal.
pub fn render_ladder(framework: Framework, rungs: &[usize]) -> (PathBuf, String) {
    match framework {
        Framework::Pytest => (
            PathBuf::from("tests/test_max_file_size.py"),
            pytest_template(rungs),
        ),
        Framework::Cargo => (
            PathBuf::from("tests/max_file_size.rs"),
            cargo_template(rungs),
        ),
        Framework::Vitest => (
            PathBuf::from("tests/max_file_size.test.ts"),
            js_template(rungs, "import { test, expect } from 'vitest';\nimport { readdirSync, statSync, readFileSync } from 'node:fs';\nimport { join } from 'node:path';"),
        ),
        Framework::Jest => (
            PathBuf::from("tests/max_file_size.test.ts"),
            js_template(rungs, "import { readdirSync, statSync, readFileSync } from 'fs';\nimport { join } from 'path';"),
        ),
        Framework::GoTest => (
            PathBuf::from("max_file_size_test.go"),
            gotest_template(rungs),
        ),
    }
}

fn pytest_template(rungs: &[usize]) -> String {
    let tests: String = rungs
        .iter()
        .map(|r| {
            format!(
                "\n\ndef test_max_file_size_within_{r}():\n    over = _over({r})\n    assert not over, f\"files over {r} lines: {{over}}\"\n"
            )
        })
        .collect();
    format!(
        r#""""Structural assertion ladder — generated by tasks::structural::max_file_size."""

import os


def _source_files():
    root = os.path.dirname(os.path.dirname(__file__))
    out = []
    skip = {{"__pycache__", ".pytest_cache", "tests", "build", "dist", "node_modules", ".git", "target"}}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip and not d.startswith(".")]
        for f in filenames:
            if f.endswith(".py"):
                out.append(os.path.join(dirpath, f))
    return out


def _line_count(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return sum(1 for _ in f)


def _over(limit):
    return [(os.path.relpath(f), n) for f in _source_files() if (n := _line_count(f)) > limit]
{tests}"#
    )
}

fn cargo_template(rungs: &[usize]) -> String {
    let tests: String = rungs
        .iter()
        .map(|r| {
            format!(
                "\n#[test]\nfn max_file_size_within_{r}() {{\n    let over = over({r});\n    assert!(over.is_empty(), \"files over {r} lines: {{over:?}}\");\n}}\n"
            )
        })
        .collect();
    format!(
        r#"//! Structural assertion ladder — generated by tasks::structural::max_file_size.

use std::fs;
use std::path::{{Path, PathBuf}};

fn walk(dir: &Path, out: &mut Vec<(PathBuf, usize)>) {{
    const SKIP: &[&str] = &["target", "node_modules", ".git", "tests", "build", "dist"];
    let Ok(rd) = fs::read_dir(dir) else {{ return }};
    for entry in rd.flatten() {{
        let name = entry.file_name();
        let s = name.to_string_lossy();
        if SKIP.iter().any(|x| *x == s) || s.starts_with('.') {{
            continue;
        }}
        let p = entry.path();
        let Ok(ft) = entry.file_type() else {{ continue }};
        if ft.is_dir() {{
            walk(&p, out);
        }} else if ft.is_file() && p.extension().and_then(|e| e.to_str()) == Some("rs") {{
            if let Ok(text) = fs::read_to_string(&p) {{
                out.push((p.clone(), text.lines().count()));
            }}
        }}
    }}
}}

fn over(max_lines: usize) -> Vec<(String, usize)> {{
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let mut all: Vec<(PathBuf, usize)> = Vec::new();
    walk(&root, &mut all);
    all.into_iter()
        .filter(|(_, n)| *n > max_lines)
        .map(|(p, n)| (p.display().to_string(), n))
        .collect()
}}
{tests}"#
    )
}

fn js_template(rungs: &[usize], imports: &str) -> String {
    let tests: String = rungs
        .iter()
        .map(|r| {
            format!(
                "\ntest('max_file_size_within_{r}', () => {{\n  expect(over({r})).toEqual([]);\n}});\n"
            )
        })
        .collect();
    format!(
        r#"// Structural assertion ladder — generated by tasks::structural::max_file_size.

{imports}

const EXTS = new Set(['.ts', '.tsx', '.js', '.jsx']);
const SKIP = new Set(['node_modules', 'tests', 'dist', 'build', '.git', 'target']);

function walk(dir, out) {{
  for (const name of readdirSync(dir)) {{
    if (SKIP.has(name) || name.startsWith('.')) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else if (st.isFile()) {{
      const dot = name.lastIndexOf('.');
      const ext = dot >= 0 ? name.slice(dot) : '';
      if (EXTS.has(ext)) {{
        const n = readFileSync(p, 'utf8').split('\n').length;
        out.push([p, n]);
      }}
    }}
  }}
}}

function over(limit) {{
  const all = [];
  walk(process.cwd(), all);
  return all.filter(([, n]) => n > limit);
}}
{tests}"#
    )
}

fn gotest_template(rungs: &[usize]) -> String {
    let tests: String = rungs
        .iter()
        .map(|r| {
            format!(
                "\nfunc TestMaxFileSizeWithin{r}(t *testing.T) {{\n\tif over := over(t, {r}); len(over) > 0 {{\n\t\tt.Errorf(\"files over {r} lines: %v\", over)\n\t}}\n}}\n"
            )
        })
        .collect();
    format!(
        r#"// Structural assertion ladder — generated by tasks::structural::max_file_size.

package main

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func over(t *testing.T, maxLines int) []string {{
	root, err := os.Getwd()
	if err != nil {{ t.Fatal(err) }}
	skip := map[string]bool{{"target": true, "node_modules": true, "tests": true, "build": true, "dist": true, ".git": true}}
	var out []string
	err = filepath.Walk(root, func(p string, info os.FileInfo, err error) error {{
		if err != nil {{ return nil }}
		name := info.Name()
		if info.IsDir() {{
			if skip[name] || strings.HasPrefix(name, ".") {{ return filepath.SkipDir }}
			return nil
		}}
		if !strings.HasSuffix(name, ".go") {{ return nil }}
		body, err := ioutil.ReadFile(p)
		if err != nil {{ return nil }}
		n := strings.Count(string(body), "\n") + 1
		if n > maxLines {{ out = append(out, p) }}
		return nil
	}})
	if err != nil {{ t.Fatal(err) }}
	return out
}}
{tests}"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ladder_rungs_interpolate_and_end_at_target() {
        // The bench-validated shape: 97-line file, 30-line goal.
        assert_eq!(ladder_rungs(30, 97), vec![80, 63, 46, 30]);
        // Already within budget → single rung.
        assert_eq!(ladder_rungs(30, 25), vec![30]);
        // Tiny span → dedup keeps it monotone.
        let r = ladder_rungs(30, 33);
        assert_eq!(*r.last().unwrap(), 30);
        assert!(r.windows(2).all(|w| w[0] > w[1]));
    }

    #[test]
    fn pytest_template_emits_one_test_per_rung() {
        let (path, content) = render_ladder(Framework::Pytest, &[80, 63, 46, 30]);
        assert_eq!(path, PathBuf::from("tests/test_max_file_size.py"));
        for r in [80, 63, 46, 30] {
            assert!(content.contains(&format!("def test_max_file_size_within_{r}")));
        }
        assert!(content.contains("def _over"));
    }

    #[test]
    fn single_rung_render_is_back_compatible() {
        let (path, content) = render(Framework::Pytest, 30);
        assert_eq!(path, PathBuf::from("tests/test_max_file_size.py"));
        assert!(content.contains("def test_max_file_size_within_30"));
    }

    #[test]
    fn cargo_template_emits_rung_tests() {
        let (path, content) = render_ladder(Framework::Cargo, &[50, 40]);
        assert_eq!(path, PathBuf::from("tests/max_file_size.rs"));
        assert!(content.contains("fn max_file_size_within_50"));
        assert!(content.contains("fn max_file_size_within_40"));
        assert!(content.contains("fn over(max_lines: usize)"));
    }

    #[test]
    fn vitest_template_uses_vitest_imports() {
        let (path, content) = render_ladder(Framework::Vitest, &[100]);
        assert_eq!(path, PathBuf::from("tests/max_file_size.test.ts"));
        assert!(content.contains("from 'vitest'"));
        assert!(content.contains("max_file_size_within_100"));
    }

    #[test]
    fn jest_template_uses_node_imports() {
        let (_path, content) = render_ladder(Framework::Jest, &[80]);
        assert!(content.contains("from 'fs'"));
        assert!(!content.contains("from 'node:fs'"));
        assert!(content.contains("max_file_size_within_80"));
    }

    #[test]
    fn gotest_template_uses_go_test_convention() {
        let (path, content) = render_ladder(Framework::GoTest, &[200, 150]);
        assert_eq!(path, PathBuf::from("max_file_size_test.go"));
        assert!(content.contains("func TestMaxFileSizeWithin200"));
        assert!(content.contains("func TestMaxFileSizeWithin150"));
    }
}
