//! Split-file task — translates a structural goal ("every source
//! file ≤ N lines") into a runtime test + a Trial.
//!
//! This is the canonical example of the collapsed architecture:
//! a "task" is just a function that materializes a structural
//! goal as an executable test and supplies move-shape guidance in
//! the prompt. The solver loop runs unchanged.

use std::path::{Path, PathBuf};

use crate::tasks::framework::detect_framework;
use crate::types::{Polarity, Trial, TrialConfig};
use crate::workdir::Workdir;

pub struct SplitFileArgs {
    pub workdir: Workdir,
    pub model: String,
    /// File the user is focused on. Surfaces in the prompt so the
    /// model knows where to look first. The structural test
    /// considers ALL source files, not just this one.
    pub path: PathBuf,
    pub max_lines: usize,
    pub test_command: Option<String>,
    pub config: Option<TrialConfig>,
}

/// Generated test file name. The wrapper writes this test into the
/// workdir's test directory and the trial's fitness signal then
/// includes it. The user may keep or delete it after the trial
/// completes — see `cleanup_structural_test` below.
pub const STRUCTURAL_TEST_FILENAME: &str = "test_max_file_size.py";

pub fn split_file(args: SplitFileArgs) -> Trial {
    let workdir_path = args.workdir.path();
    let test_command = args
        .test_command
        .unwrap_or_else(|| detect_framework(workdir_path).default_test_command().to_string());

    // Materialize the structural goal as a pytest test the loop's
    // fitness signal picks up. "Test passes" ↔ "every source file
    // is ≤ max_lines."
    write_structural_test(workdir_path, args.max_lines);

    let prompt = format!(
        "Goal: split `{}` until every source file is ≤ {} lines.\n\nThe test `test_max_file_size` (in tests/) enforces this. Make it pass without breaking the others. Each turn, emit ONE EditAction — extract a function to a new file, inline a redundant helper, or rewrite the target file more compactly. The aggregate fitness is the test-pass count; you don't need to plan the whole refactor up front.",
        args.path.display(),
        args.max_lines,
    );

    Trial {
        workdir: args.workdir,
        model: args.model,
        prompt,
        test_command,
        polarity: Polarity::MaximizePassing,
        config: args.config.unwrap_or_default(),
        syntax_validator: None,
    }
}

/// Write the structural-test asset into the workdir's test
/// directory. Idempotent — overwrites if the file already exists
/// (lets the caller re-target max_lines between trials).
pub fn write_structural_test(workdir: &Path, max_lines: usize) {
    let tests_dir = workdir.join("tests");
    let _ = std::fs::create_dir_all(&tests_dir);
    let content = format!(
        r#""""Structural assertion — generated by `tasks::split_file`.

Fails when any source file in the workdir exceeds the per-file line
budget. The TDD loop's `MaximizePassing` polarity treats this as a
gate: any refactor that doesn't bring the max file size under the
limit (or breaks an existing test) is rejected. Delete this file
once the refactor is done if you don't want a permanent guard.
"""

import glob
import os


def _source_files():
    root = os.path.dirname(os.path.dirname(__file__))
    exts = (".py",)
    out = []
    skip = {{"__pycache__", ".pytest_cache", "tests", "build", "dist", "node_modules"}}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip and not d.startswith(".")]
        for f in filenames:
            if f.endswith(exts):
                out.append(os.path.join(dirpath, f))
    return out


def _line_count(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return sum(1 for _ in f)


def test_max_file_size():
    limit = {max_lines}
    over = []
    for f in _source_files():
        n = _line_count(f)
        if n > limit:
            over.append((os.path.relpath(f), n))
    assert not over, f"files over {{limit}} lines: {{over}}"
"#,
        max_lines = max_lines
    );
    let _ = std::fs::write(tests_dir.join(STRUCTURAL_TEST_FILENAME), content);
}

/// Remove the generated structural test from the workdir. Optional
/// callers run this after `run_trial` returns `Reached` to leave
/// the workdir clean of solver scaffolding. No-op if the file
/// doesn't exist.
pub fn cleanup_structural_test(workdir: &Path) {
    let p = workdir.join("tests").join(STRUCTURAL_TEST_FILENAME);
    let _ = std::fs::remove_file(p);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn write_structural_test_creates_tests_dir_if_missing() {
        let tmp = tempfile::tempdir().unwrap();
        write_structural_test(tmp.path(), 30);
        let p = tmp.path().join("tests").join(STRUCTURAL_TEST_FILENAME);
        let body = std::fs::read_to_string(&p).expect("test file written");
        assert!(body.contains("test_max_file_size"));
        assert!(body.contains("limit = 30"));
    }

    #[test]
    fn cleanup_structural_test_is_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        // No-op when file doesn't exist.
        cleanup_structural_test(tmp.path());
        // Write then clean — file is gone.
        write_structural_test(tmp.path(), 100);
        cleanup_structural_test(tmp.path());
        let p = tmp.path().join("tests").join(STRUCTURAL_TEST_FILENAME);
        assert!(!p.exists());
    }
}
