#!/usr/bin/env python3
"""Generate the retrieval head-to-head bank from mined bridge candidates.

WHY THIS EXISTS: the shipped eval scorer `score_sources`
(`eval_cmd/score.rs:43-54`) compares `ScoredChunk.title` and NOTHING ELSE —
never `source_doc_id`. A bank keyed on conversation UUIDs is therefore
unscoreable. This joins UUID -> title from the Lance index so the harness can
score conversations at all.

WHAT THE BANK IS FOR: crowning a champion among retrieval arms (baseline /
PPR off / PPR up / dedup-only / cross-encoder). Each question names an entity
that appears in EXACTLY TWO conversations; both are legitimately relevant, so
`expected_sources` carries both titles. Two phrasings per candidate, because
the sizing gate measured 48% bucket instability from wording alone — a single
phrasing would let the question wording, not the arm, decide the winner.

The harness's own `source_score` is coarse here (0 / 0.5 / 1.0 with two
sources). The real endpoint is RANK, recovered by
`bridge-arms-analyze.py` from the per-question `retrieved` array, which the
harness emits in rank order with titles (`eval_cmd/runner.rs:61,201-215`).

PRIVACY: emits real conversation titles from a personal archive. Write it to
scratchpad, NEVER into the repo. (`.gitignore` does not untrack an
already-tracked file — that lesson cost a history rewrite on
`bench/conversation-private/`.)

Usage:
  python3 scripts/bridge-bank-gen.py <sample.tsv> <out.toml> <out-sidecar.json>
"""

import json
import sys

import lance

INDEX = "/Users/alexsbryan/.sovereign/indexes/conversations-anthropic/chunks.lance"
CORPUS = "conversations-anthropic"

# Same two phrasings the sizing gate used, so its rank distribution and this
# run's are directly comparable.
VARIANTS = {
    "bare": lambda e: e,
    "nat": lambda e: f"What did we discuss about {e}?",
}


def toml_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(2)
    sample_path, out_toml, out_sidecar = sys.argv[1], sys.argv[2], sys.argv[3]

    ds = lance.dataset(INDEX)
    t = ds.to_table(columns=["source_doc_id", "title"])
    uuid_to_title = {}
    for s, ti in zip(
        t.column("source_doc_id").to_pylist(), t.column("title").to_pylist()
    ):
        if s and ti:
            uuid_to_title[s] = ti

    # A title shared by two conversations cannot identify one of them, so a
    # question keyed on it is unscoreable. Drop rather than silently mis-score.
    title_counts = {}
    for ti in uuid_to_title.values():
        title_counts[ti] = title_counts.get(ti, 0) + 1
    ambiguous = {ti for ti, c in title_counts.items() if c > 1}

    cands, dropped_ambiguous, dropped_missing = [], 0, 0
    with open(sample_path) as fh:
        for line in fh:
            p = line.rstrip("\n").split("\t")
            if len(p) < 6:
                continue
            entity, label, conv_a, m_a, conv_b, m_b = p[0], p[1], p[2], p[3], p[4], p[5]
            ta, tb = uuid_to_title.get(conv_a), uuid_to_title.get(conv_b)
            if not ta or not tb:
                dropped_missing += 1
                continue
            if ta in ambiguous or tb in ambiguous or ta == tb:
                dropped_ambiguous += 1
                continue
            cands.append(
                {
                    "entity": entity,
                    "label": label,
                    "conv_a": conv_a,
                    "conv_b": conv_b,
                    "title_a": ta,
                    "title_b": tb,
                    "m_a": int(m_a),
                    "m_b": int(m_b),
                }
            )

    out = [
        "# GENERATED by scripts/bridge-bank-gen.py — do not hand-edit.",
        "# Contains real conversation titles. Keep out of the repo.",
        "",
        "[bank]",
        f'name = "conversation-bridge-headtohead"',
        f'corpus = "{CORPUS}"',
        'description = """',
        "Retrieval head-to-head bank. Each question names an entity appearing in",
        "exactly two conversations; expected_sources carries both titles. Scored",
        "for RANK by scripts/bridge-arms-analyze.py, not by source_score alone.",
        '"""',
        "",
    ]
    sidecar = {}
    n = 0
    for c in cands:
        for vname, vfn in VARIANTS.items():
            qid = f"bridge_{vname}_{n:04d}"
            q = vfn(c["entity"])
            out += [
                "[[questions]]",
                f'id = "{qid}"',
                f'category = "entity_bridge_{vname}"',
                'subject = "conversations"',
                'attribution_mode = "both"',
                f'question = "{toml_escape(q)}"',
                f'expected_facts = ["{toml_escape(c["entity"])}"]',
                f'expected_sources = ["{toml_escape(c["title_a"])}", "{toml_escape(c["title_b"])}"]',
                f'notes = "{c["label"]}; mentions {c["m_a"]}/{c["m_b"]}"',
                "",
            ]
            sidecar[qid] = {
                "entity": c["entity"],
                "label": c["label"],
                "variant": vname,
                "conv_a": c["conv_a"],
                "conv_b": c["conv_b"],
                "title_a": c["title_a"],
                "title_b": c["title_b"],
                "m_a": c["m_a"],
                "m_b": c["m_b"],
            }
        n += 1

    with open(out_toml, "w") as fh:
        fh.write("\n".join(out))
    with open(out_sidecar, "w") as fh:
        json.dump(sidecar, fh, indent=1)

    print(
        f"bank: {len(sidecar)} questions from {len(cands)} candidates "
        f"({len(VARIANTS)} phrasings each)",
        file=sys.stderr,
    )
    print(
        f"dropped: {dropped_ambiguous} ambiguous/duplicate-title, "
        f"{dropped_missing} missing-title",
        file=sys.stderr,
    )
    print(f"wrote {out_toml} + {out_sidecar}", file=sys.stderr)


if __name__ == "__main__":
    main()
