#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
ralph/DECISIONS.md is GENERATED. One decision, one file, so two campaigns
running in parallel never edit the same lines.

WHY THIS EXISTS. On 2026-09-21 a merge of `origin` into `main` conflicted on
ralph/DECISIONS.md, and the conflict was not a disagreement: two campaigns
(ring-room/threat-gaps on main, e7/ontology on the branch) had each appended
their own entries to the end of one file, and each had minted A35-A41 from the
same global counter. Both sides were right; the file could only hold one.
Resolving it by hand cost a session and renumbered seven published entries.

The fix is structural, not remembered (ARCH 10):

  * ONE FILE PER DECISION, under ralph/decisions/. Two campaigns adding
    entries add different files, and git merges disjoint files with no
    conflict at all.
  * IDS ARE CAMPAIGN-SCOPED — `<campaign>-<n>`, e.g. `threat-gaps-3`. A
    global counter collides the moment two branches mint at once; a campaign
    slug cannot, because two campaigns never share one. The legacy `A<n>`
    series (A1-A75) is FROZEN in _archive-ledger.md / _archive-appendices.md
    and is never renumbered — published ids are cited from
    quality/campaigns/*.toml, research/, and commit bodies.
  * ralph/DECISIONS.md IS RENDERED from those parts, so it stays the one path
    to read and every existing citation of it still resolves. It carries a
    generated banner; a merge conflict in it is resolved by regenerating, not
    by editing (see .gitattributes).

USAGE

    scripts/ralph-decisions.py new threat-gaps    # mint the next id, print the path
    scripts/ralph-decisions.py --write            # re-render ralph/DECISIONS.md
    scripts/ralph-decisions.py --check            # exit 1 if the render is stale
    scripts/ralph-decisions.py list               # ids, dates, subjects
    scripts/ralph-decisions.py --self-test        # round-trip + validator tests

ENTRY FILE FORMAT (ralph/decisions/<campaign>-<n>.md)

    <!-- ledger -->

    **<id> · <YYYY-MM-DD> · <unit or subject> · <who>** — <commit>
    - Needed: what forced the decision
    - Chose: what was chosen
    - Because: why

    <!-- appendix -->

    ## <id> · <YYYY-MM-DD> — <title>

    <details>
    the reasoning in full, the evidence, the worker's package
    </details>

The ledger block is required; the appendix block is optional. The id in both
blocks must match the filename — checked, because a copy-pasted entry that
kept the id it was copied from is the one error this format invites.
"""

from __future__ import annotations

import argparse
import difflib
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
ENTRY_DIR = REPO / "ralph" / "decisions"
RENDERED = REPO / "ralph" / "DECISIONS.md"

BANNER = (
    "<!-- GENERATED by scripts/ralph-decisions.py from ralph/decisions/. DO NOT EDIT.\n"
    "     One decision, one file: `scripts/ralph-decisions.py new <campaign>`.\n"
    "     Re-render after editing an entry: `scripts/ralph-decisions.py --write`. -->"
)

LEDGER_MARK = "<!-- ledger -->"
APPENDIX_MARK = "<!-- appendix -->"

# `<campaign>-<n>`: a lowercase slug of one or more dash-joined words, then a
# number. The slug is the campaign, which is what makes the id collision-free
# across branches; the number only has to be unique within it.
ID_RE = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*-(\d+)$")
DATE_RE = re.compile(r"\b(\d{4}-\d{2}-\d{2})\b")


class EntryError(Exception):
    """A malformed entry file. Carries the path so the message can name it."""


class Entry:
    def __init__(self, path: pathlib.Path):
        self.path = path
        self.id = path.stem
        m = ID_RE.match(self.id)
        if not m:
            raise EntryError(
                f"{path}: id '{self.id}' is not `<campaign>-<n>` "
                f"(lowercase campaign slug, dash, number). Legacy A<n> ids are "
                f"frozen in _archive-ledger.md and are not minted any more."
            )
        self.campaign = self.id[: self.id.rindex("-")]
        self.number = int(m.group(1))
        self.ledger, self.appendix = self._parse(path.read_text())
        self.date = self._date()

    def _parse(self, text: str) -> tuple[str, str]:
        if LEDGER_MARK not in text:
            raise EntryError(f"{self.path}: no `{LEDGER_MARK}` block — the ledger row is required")
        _, rest = text.split(LEDGER_MARK, 1)
        if APPENDIX_MARK in rest:
            ledger, appendix = rest.split(APPENDIX_MARK, 1)
        else:
            ledger, appendix = rest, ""
        ledger, appendix = ledger.strip("\n"), appendix.strip("\n")
        if not ledger:
            raise EntryError(f"{self.path}: the ledger block is empty")
        head = ledger.split("\n", 1)[0]
        if not head.startswith(f"**{self.id} ·"):
            raise EntryError(
                f"{self.path}: ledger row opens with {head[:60]!r} but the file "
                f"is named {self.id}.md — the id must match (a copied entry that "
                f"kept its source's id is the error this checks for)."
            )
        if appendix:
            ahead = appendix.split("\n", 1)[0]
            if not ahead.startswith(f"## {self.id} ·"):
                raise EntryError(
                    f"{self.path}: appendix heading opens with {ahead[:60]!r}, "
                    f"expected `## {self.id} · …`"
                )
        return ledger, appendix

    def _date(self) -> str:
        m = DATE_RE.search(self.ledger.split("\n", 1)[0])
        if not m:
            raise EntryError(
                f"{self.path}: no YYYY-MM-DD in the ledger row — the render is "
                f"ordered by date, so an entry without one has no place in it"
            )
        return m.group(1)

    @property
    def sort_key(self) -> tuple[str, str, int]:
        return (self.date, self.campaign, self.number)


def _part(name: str) -> str:
    p = ENTRY_DIR / name
    if not p.exists():
        raise SystemExit(f"ralph-decisions: missing {p} — the archive is one of this render's parts")
    return p.read_text().strip("\n")


def load_entries() -> list[Entry]:
    if not ENTRY_DIR.is_dir():
        raise SystemExit(f"ralph-decisions: {ENTRY_DIR} does not exist")
    entries = [
        Entry(p)
        for p in sorted(ENTRY_DIR.glob("*.md"))
        if not p.name.startswith("_")
    ]
    return sorted(entries, key=lambda e: e.sort_key)


def render(entries: list[Entry] | None = None) -> str:
    entries = load_entries() if entries is None else entries
    out = [BANNER, "", _part("_header.md"), "", "## Ledger", ""]
    out.append(_part("_archive-ledger.md"))
    for e in entries:
        out += ["", e.ledger]
    out += ["", "## Flags for the operator", "", _part("_flags.md")]
    out += ["", "## Appendices", "", _part("_archive-appendices.md")]
    for e in entries:
        if e.appendix:
            out += ["", e.appendix]
    return "\n".join(out).rstrip("\n") + "\n"


def cmd_write() -> int:
    text = render()
    existing = RENDERED.read_text() if RENDERED.exists() else ""
    if text == existing:
        print(f"ralph-decisions: {RENDERED.relative_to(REPO)} already current")
        return 0
    RENDERED.write_text(text)
    print(f"ralph-decisions: wrote {RENDERED.relative_to(REPO)} ({len(text.splitlines())} lines)")
    return 0


def cmd_check() -> int:
    want = render()
    have = RENDERED.read_text() if RENDERED.exists() else ""
    if want == have:
        print(f"ralph-decisions: {RENDERED.relative_to(REPO)} is current")
        return 0
    diff = list(
        difflib.unified_diff(
            have.splitlines(), want.splitlines(), "committed", "rendered", lineterm="", n=1
        )
    )
    sys.stderr.write(
        f"ralph-decisions: {RENDERED.relative_to(REPO)} is STALE "
        f"({sum(1 for d in diff if d.startswith(('+', '-')) and not d.startswith(('+++', '---')))} lines differ).\n"
        "  It is generated — edit the entry under ralph/decisions/, not the rendered file.\n"
        "  Fix: scripts/ralph-decisions.py --write\n\n"
    )
    sys.stderr.write("\n".join(diff[:60]) + "\n")
    return 1


def cmd_new(campaign: str, subject: str, who: str, title: str, date: str) -> int:
    if not re.fullmatch(r"[a-z][a-z0-9]*(?:-[a-z0-9]+)*", campaign):
        raise SystemExit(
            f"ralph-decisions: campaign '{campaign}' must be a lowercase slug "
            f"(letters, digits, dashes) — it is what keeps ids from colliding "
            f"between branches, so it names the campaign, not the row"
        )
    taken = [e.number for e in load_entries() if e.campaign == campaign]
    n = max(taken, default=0) + 1
    entry_id = f"{campaign}-{n}"
    path = ENTRY_DIR / f"{entry_id}.md"
    if path.exists():  # unreachable via max()+1, kept so a hand-made file is never clobbered
        raise SystemExit(f"ralph-decisions: {path} already exists")
    path.write_text(
        f"""{LEDGER_MARK}

**{entry_id} · {date} · {subject} · {who}** — this commit
- Needed:
- Chose:
- Because:

{APPENDIX_MARK}

## {entry_id} · {date} — {title}

<details><summary>reasoning, evidence, package</summary>

</details>
"""
    )
    print(path.relative_to(REPO))
    return 0


def cmd_list() -> int:
    entries = load_entries()
    if not entries:
        print("ralph-decisions: no entries yet (the A1-A75 series is archived, not listed)")
        return 0
    width = max(len(e.id) for e in entries)
    for e in entries:
        head = e.ledger.split("\n", 1)[0]
        subject = head.split(" · ")[2] if head.count(" · ") >= 2 else ""
        print(f"{e.id:<{width}}  {e.date}  {subject}")
    return 0


def self_test() -> int:
    import tempfile

    failures = []

    def check(name, cond, detail=""):
        if cond:
            print(f"  ok   {name}")
        else:
            print(f"  FAIL {name} {detail}")
            failures.append(name)

    with tempfile.TemporaryDirectory() as td:
        d = pathlib.Path(td)
        good = d / "demo-2.md"
        good.write_text(
            f"{LEDGER_MARK}\n\n**demo-2 · 2026-01-02 · a-row · director** — abc123\n"
            f"- Needed: x\n- Chose: y\n- Because: z\n\n{APPENDIX_MARK}\n\n"
            f"## demo-2 · 2026-01-02 — a title\n\n<details>\nbody\n</details>\n"
        )
        e = Entry(good)
        check("id parses", e.id == "demo-2" and e.campaign == "demo" and e.number == 2)
        check("date parses", e.date == "2026-01-02", e.date)
        check("appendix captured", e.appendix.startswith("## demo-2 ·"))
        check("sort key", e.sort_key == ("2026-01-02", "demo", 2))

        bad_id = d / "Demo-3.md"
        bad_id.write_text(f"{LEDGER_MARK}\n\n**Demo-3 · 2026-01-02 · r · w** — c\n")
        try:
            Entry(bad_id)
            check("uppercase id refused", False)
        except EntryError:
            check("uppercase id refused", True)

        legacy = d / "A76.md"
        legacy.write_text(f"{LEDGER_MARK}\n\n**A76 · 2026-01-02 · r · w** — c\n")
        try:
            Entry(legacy)
            check("legacy A<n> id refused", False)
        except EntryError:
            check("legacy A<n> id refused", True)

        mismatch = d / "demo-4.md"
        mismatch.write_text(f"{LEDGER_MARK}\n\n**demo-2 · 2026-01-02 · r · w** — c\n")
        try:
            Entry(mismatch)
            check("id/filename mismatch refused", False)
        except EntryError:
            check("id/filename mismatch refused", True)

        nodate = d / "demo-5.md"
        nodate.write_text(f"{LEDGER_MARK}\n\n**demo-5 · someday · r · w** — c\n")
        try:
            Entry(nodate)
            check("undated entry refused", False)
        except EntryError:
            check("undated entry refused", True)

        noledger = d / "demo-6.md"
        noledger.write_text(f"{APPENDIX_MARK}\n\n## demo-6 · 2026-01-02 — t\n")
        try:
            Entry(noledger)
            check("entry with no ledger row refused", False)
        except EntryError:
            check("entry with no ledger row refused", True)

        appx_mismatch = d / "demo-7.md"
        appx_mismatch.write_text(
            f"{LEDGER_MARK}\n\n**demo-7 · 2026-01-02 · r · w** — c\n\n"
            f"{APPENDIX_MARK}\n\n## demo-2 · 2026-01-02 — t\n"
        )
        try:
            Entry(appx_mismatch)
            check("appendix id mismatch refused", False)
        except EntryError:
            check("appendix id mismatch refused", True)

    # The render must be a pure function of the parts: same inputs, same bytes.
    check("render is deterministic", render() == render())
    check("render carries the banner", render().startswith(BANNER))
    check("render is current", render() == RENDERED.read_text(),
          "run scripts/ralph-decisions.py --write")

    print(f"\n{len(failures)} failure(s)")
    return 1 if failures else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[1])
    ap.add_argument("--write", action="store_true", help="re-render ralph/DECISIONS.md")
    ap.add_argument("--check", action="store_true", help="exit 1 if the render is stale")
    ap.add_argument("--self-test", action="store_true", help="validator + round-trip tests")
    sub = ap.add_subparsers(dest="cmd")
    n = sub.add_parser("new", help="mint the next entry file for a campaign")
    n.add_argument("campaign")
    n.add_argument("--subject", default="<unit or REVIEW row>")
    n.add_argument("--who", default="director")
    n.add_argument("--title", default="<one line: what was decided>")
    n.add_argument("--date", default=None)
    sub.add_parser("list", help="list the entries under ralph/decisions/")
    args = ap.parse_args()

    if args.self_test:
        return self_test()
    if args.cmd == "new":
        import datetime

        return cmd_new(
            args.campaign, args.subject, args.who, args.title,
            args.date or datetime.date.today().isoformat(),
        )
    if args.cmd == "list":
        return cmd_list()
    if args.write:
        return cmd_write()
    if args.check:
        return cmd_check()
    sys.stdout.write(render())
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except EntryError as exc:
        sys.stderr.write(f"ralph-decisions: {exc}\n")
        sys.exit(2)
