#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# tailnet-sshd-run.sh — LaunchAgent entrypoint for the user-level sshd channels
# (ops :2222, shell :2223). Shared by both setup scripts; not run by hand.
#
#   tailnet-sshd-run.sh <dir>     # <dir>/sshd_config, <dir>/listen.conf, <dir>/sshd.log
#
# WHY THIS EXISTS. sshd binds the ListenAddresses it can and KEEPS RUNNING when
# one of them is absent. So a boot race with Tailscale leaves a loopback-only
# listener that every check downstream calls healthy: the process is up, launchd
# reports running, lsof shows a listener on the port. Observed on this host
# 2026-08-25 — boot 14:51:31, Tailscale 14:52:27, sshd 14:53:05, and
# ~/.svrn-ops/sshd.log recorded
#
#     Bind to port 2222 on 100.104.36.28 failed: Can't assign requested address.
#     Server listening on 127.0.0.1 port 2222.
#
# leaving the ops channel unreachable from every peer until someone noticed by
# hand. KeepAlive cannot heal it because sshd never exits.
#
# So: wait for a tailnet address before starting, render the one line of config
# that names it, then WATCH it. If the address changes or disappears, kill sshd
# and exit 0 — launchd restarts us and we re-render against the new address.
# The setup scripts' "re-run this script if the tailnet address changed" note is
# now the machine's job, not the operator's.
set -uo pipefail

DIR="${1:?usage: tailnet-sshd-run.sh <channel-dir>}"
CONF="$DIR/sshd_config"
LISTEN_CONF="$DIR/listen.conf"
LOG="$DIR/sshd.log"
WAIT_SECS="${TAILNET_SSHD_WAIT_SECS:-300}"
POLL_SECS="${TAILNET_SSHD_POLL_SECS:-30}"

say() { printf '%s tailnet-sshd-run[%s]: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(basename "$DIR")" "$*"; }

[ -f "$CONF" ] || { say "FATAL: no $CONF — run the channel setup script"; exit 78; }

# ONE override, ONE name, and it lives in a FILE rather than the environment.
# Two reasons. A launchd job inherits none of the operator's shell env — the
# job's environment is {OSLogRateLimit, XPC_SERVICE_NAME} plus SSH_AUTH_SOCK —
# so an env-var escape hatch here can never fire, it just reads like one. And
# this wrapper is shared by both channels, so a per-channel knob has to be
# per-channel STATE: $DIR/listen.override, written by that channel's setup
# script. A name that steered both channels at once would be the same bug in a
# different costume.
tailnet_addr() {
  local ts ip
  if [ -s "$DIR/listen.override" ]; then
    ip="$(tr -d '[:space:]' < "$DIR/listen.override")"
    [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }
  fi
  for ts in tailscale /usr/local/bin/tailscale \
            /Applications/Tailscale.app/Contents/MacOS/Tailscale; do
    if command -v "$ts" >/dev/null 2>&1; then
      ip="$("$ts" ip -4 2>/dev/null | head -1)"
      [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }
    fi
  done
  ip="$(ifconfig 2>/dev/null | awk '/inet 100\./{print $2; exit}')"
  [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }
  return 1
}

# --- wait for the tailnet, rather than racing it -------------------------
ADDR=""
deadline=$(( SECONDS + WAIT_SECS ))
while [ -z "$ADDR" ]; do
  ADDR="$(tailnet_addr || true)"
  [ -n "$ADDR" ] && break
  if [ "$SECONDS" -ge "$deadline" ]; then
    say "no tailnet address after ${WAIT_SECS}s — exiting so launchd retries"
    exit 75   # EX_TEMPFAIL: transient, KeepAlive brings us back
  fi
  sleep 2
done
say "tailnet address $ADDR — rendering $LISTEN_CONF"

umask 077
printf '# generated by tailnet-sshd-run.sh — do not edit\nListenAddress %s\nListenAddress 127.0.0.1\n' \
  "$ADDR" > "$LISTEN_CONF"

if ! /usr/sbin/sshd -t -f "$CONF"; then
  say "FATAL: $CONF failed sshd -t"
  exit 78   # EX_CONFIG: a restart loop will not fix a bad config
fi

# --- run sshd as a child so we can keep watching the address -------------
/usr/sbin/sshd -D -f "$CONF" -E "$LOG" &
CHILD=$!
trap 'kill "$CHILD" 2>/dev/null; wait "$CHILD" 2>/dev/null; exit 0' TERM INT
say "sshd started (pid $CHILD), watching $ADDR every ${POLL_SECS}s"

while kill -0 "$CHILD" 2>/dev/null; do
  sleep "$POLL_SECS"
  CUR="$(tailnet_addr || true)"
  if [ "$CUR" != "$ADDR" ]; then
    say "tailnet address changed: $ADDR -> ${CUR:-none} — restarting to rebind"
    kill "$CHILD" 2>/dev/null
    wait "$CHILD" 2>/dev/null
    exit 0    # KeepAlive restarts us; we re-render against the new address
  fi
done

wait "$CHILD"
rc=$?
say "sshd exited rc=$rc"
exit "$rc"
