repository = "6e6f9dbec3bd6782589b86b5c387f626"
commons = ["d734dd5da1a6d3c4297b84b6e4373e3c"]

[contracts]
oicp = ["shared/crates/oicp-types/", "shared/crates/oicp-client/", "cmnwlth/crates/oicp-conformance/", "cmnwlth/docs/oicp-v0.4.md", "svrn/crates/sovereign-daemon/src/routes_oicp.rs", "svrn/crates/sovereign-daemon/src/routes_oicp_ingest.rs"]
