use std::path::PathBuf;

/// Minimal fallback manifest used when the workspace `data/corpora.toml`
/// cannot be located (e.g., the crate was copied out of the workspace).
/// This keeps the build green and the app functional without knowledge bases.
const FALLBACK_CORPORA_TOML: &str = r#"# Fallback corpus manifest (generated by build.rs)
# The workspace data/corpora.toml was not found at build time.
# Users can add their own corpora.toml to their data directory.
"#;

fn main() {
    // Locate the workspace's data/corpora.toml by walking up from CARGO_MANIFEST_DIR.
    // src-tauri is at: <workspace>/crates/sovereign-desktop/src-tauri
    // The corpora file is at: <workspace>/data/corpora.toml
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let candidates = [
        // Standard workspace layout.
        manifest_dir.join("../../../data/corpora.toml"),
        // Alternative if the crate is nested differently.
        manifest_dir.join("../../data/corpora.toml"),
        manifest_dir.join("../data/corpora.toml"),
        // Env var override for non-standard builds.
        PathBuf::from(std::env::var("SOVEREIGN_CORPORA_TOML").unwrap_or_default()),
    ];

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("corpora.toml");

    let mut found = false;
    for candidate in &candidates {
        if candidate.exists() {
            let content = std::fs::read_to_string(candidate)
                .expect("Failed to read corpora.toml");
            std::fs::write(&dest, content).expect("Failed to write corpora.toml to OUT_DIR");
            println!("cargo:rerun-if-changed={}", candidate.display());
            println!(
                "cargo:warning=Bundled corpora.toml from {}",
                candidate.display()
            );
            found = true;
            break;
        }
    }

    if !found {
        // Write the fallback so include_str! in commands.rs still compiles.
        std::fs::write(&dest, FALLBACK_CORPORA_TOML)
            .expect("Failed to write fallback corpora.toml");
        println!(
            "cargo:warning=data/corpora.toml not found — using empty fallback. \
             Knowledge base features will be unavailable until a corpora.toml is \
             placed in the user's data directory."
        );
    }

    println!("cargo:rerun-if-env-changed=SOVEREIGN_CORPORA_TOML");

    tauri_build::build();
}
