// SPDX-License-Identifier: AGPL-3.0-or-later
//! The descriptor-grammar gate — the recipe-author tool's JSON Schema checked
//! BOTH directions against the descriptor `corpus-engine` generates from the
//! recipe AST.
//!
//! These tests moved here from `sovereign-recipe-author` when the descriptor
//! became INJECTED: that package may not name `corpus-engine`, and a
//! checked-in fixture would defeat the drift gate (a fixture cannot notice a
//! new `ExtractorConfig` variant). `sovereign-tools` links both the grammar and
//! the descriptor, so it asserts against the REAL generated bytes.

use serde_json::Value;
use sovereign_tools::recipe_author::recipe_json_schema;

/// The real generated descriptor, injected exactly the way the bundle injects
/// it (`RecipeAuthoringTools::new`).
const DESCRIPTOR: &str = corpus_engine::recipe_schema::RECIPE_SCHEMA_DESCRIPTOR_JSON;

fn schema() -> Value {
    recipe_json_schema(DESCRIPTOR)
}

fn descriptor() -> Value {
    serde_json::from_str(DESCRIPTOR).expect("the injected descriptor must parse")
}

fn variant_consts(section_oneof: &Value) -> Vec<String> {
    section_oneof
        .as_array()
        .expect("oneOf array")
        .iter()
        .filter_map(|arm| {
            arm["properties"]["type"]["const"]
                .as_str()
                .map(String::from)
        })
        .collect()
}

/// Property names of a JSON-schema object node, sorted.
fn props(node: &Value) -> Vec<String> {
    let mut v: Vec<String> = node["properties"]
        .as_object()
        .unwrap_or_else(|| panic!("node has no properties: {node}"))
        .keys()
        .cloned()
        .collect();
    v.sort();
    v
}

/// The descriptor list `ontology.<key>` as sorted strings.
fn desc_strings(desc: &Value, key: &str) -> Vec<String> {
    let mut v: Vec<String> = desc["ontology"][key]
        .as_array()
        .unwrap_or_else(|| panic!("descriptor.ontology.{key} must be an array"))
        .iter()
        .map(|x| x.as_str().expect("string").to_string())
        .collect();
    v.sort();
    v
}

#[test]
fn schema_is_valid_json_object() {
    let s = schema();
    assert_eq!(s["type"], "object");
    let required: Vec<&str> = s["required"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|v| v.as_str())
        .collect();
    for k in ["corpus", "acquire", "extract", "chunk"] {
        assert!(required.contains(&k), "root must require {k}");
    }
}

#[test]
fn extract_covers_all_generated_variants() {
    // The whole point of the generated descriptor: every ExtractorConfig
    // variant in recipe.rs must surface as an arm. Pre-generation this was
    // 4 of 22 (email/jsonl/csv/markdown were unauthorable).
    let s = schema();
    let arms = variant_consts(&s["properties"]["extract"]["oneOf"]);
    for v in [
        "jsonl",
        "csv",
        "email",
        "markdown",
        "code",
        "parquet",
        "html",
        "html_sections",
    ] {
        assert!(
            arms.iter().any(|x| x == v),
            "missing extractor arm `{v}`; got {arms:?}"
        );
    }
    assert!(
        arms.len() >= 20,
        "expected the full extractor catalog, got {}",
        arms.len()
    );
}

#[test]
fn acquire_covers_all_generated_variants() {
    let s = schema();
    let arms = variant_consts(&s["properties"]["acquire"]["oneOf"]);
    for v in [
        "bulk_download",
        "http_api",
        "huggingface_dataset",
        "local_file",
        "web_crawl",
    ] {
        assert!(
            arms.iter().any(|x| x == v),
            "missing acquire arm `{v}`; got {arms:?}"
        );
    }
}

#[test]
fn http_api_arm_requires_requests_not_base_url() {
    // base_url is `#[serde(default)]` in recipe.rs, so it is NOT required
    // (the old hand-schema wrongly required it); `requests` IS required.
    let s = schema();
    let arms = s["properties"]["acquire"]["oneOf"].as_array().unwrap();
    let http_api = arms
        .iter()
        .find(|a| a["properties"]["type"]["const"] == "http_api")
        .expect("http_api arm");
    let required: Vec<&str> = http_api["required"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|v| v.as_str())
        .collect();
    assert!(
        required.contains(&"requests"),
        "http_api must require requests"
    );
    assert!(
        !required.contains(&"base_url"),
        "base_url is defaulted, must not be required"
    );
}

/// The ontology grammar is a hand copy of the recipe AST, gated here in
/// BOTH directions through the descriptor corpus-engine generates from
/// that AST: every field the AST has, the tool offers (an agent can emit
/// it); every field the tool offers, the AST has (nothing phantom). A
/// June note records the grammar silently blocking `ontology` when it
/// lagged; this is what makes that impossible to repeat.
#[test]
fn tool_schema_matches_recipe_ast() {
    let desc = descriptor();
    let tool = schema()["properties"]["enrichment"]["properties"]["ontology"].clone();

    // Block-level keys: `version` plus every version-1 key.
    let mut ast_block = desc_strings(&desc, "block");
    ast_block.extend(desc_strings(&desc, "v1"));
    ast_block.sort();
    assert_eq!(props(&tool), ast_block, "[enrichment.ontology] keys");

    // Nested version-1 structs.
    for (prop, key) in [
        ("vocabulary", "vocabulary"),
        ("voices", "voices"),
        ("change", "change"),
        ("tension", "tension"),
        ("derive", "derive"),
    ] {
        assert_eq!(
            props(&tool["properties"][prop]),
            desc_strings(&desc, key),
            "[enrichment.ontology.{prop}] keys"
        );
    }

    // Type declarations and their nested `source`.
    let type_node = &tool["properties"]["types"]["items"];
    assert_eq!(
        props(type_node),
        desc_strings(&desc, "type"),
        "[[types]] keys"
    );
    assert_eq!(
        props(&type_node["properties"]["source"]),
        desc_strings(&desc, "source"),
        "types.source keys"
    );

    // Attributes: the shared fields plus every family's own keys plus `type`.
    let mut ast_attr = desc_strings(&desc, "attribute");
    ast_attr.push("type".to_string());
    for fam in desc["ontology"]["attribute_families"]
        .as_array()
        .expect("attribute_families")
    {
        for f in fam["fields"].as_array().expect("fields") {
            ast_attr.push(f.as_str().expect("string").to_string());
        }
    }
    ast_attr.sort();
    ast_attr.dedup();
    assert_eq!(
        props(&type_node["properties"]["attributes"]["items"]),
        ast_attr,
        "attribute keys"
    );

    // Closed enums are read straight from the descriptor.
    let enum_of = |node: &Value| -> Vec<String> {
        let mut v: Vec<String> = node["enum"]
            .as_array()
            .expect("enum")
            .iter()
            .map(|x| x.as_str().expect("string").to_string())
            .collect();
        v.sort();
        v
    };
    assert_eq!(
        enum_of(&type_node["properties"]["kind"]),
        desc_strings(&desc, "kind")
    );
    assert_eq!(
        enum_of(&type_node["properties"]["force"]),
        desc_strings(&desc, "force")
    );
    assert_eq!(
        enum_of(&type_node["properties"]["deontic"]["items"]),
        desc_strings(&desc, "deontic")
    );
    assert_eq!(
        enum_of(&type_node["properties"]["scope"]),
        desc_strings(&desc, "claim_scope")
    );
    assert_eq!(
        enum_of(&tool["properties"]["change"]["properties"]["clock"]),
        desc_strings(&desc, "clock")
    );
    assert_eq!(
        enum_of(&type_node["properties"]["attributes"]["items"]["properties"]["type"]),
        desc_strings(&desc, "attribute_family")
    );

    // The grammar block no longer hard-requires prose (a types-only block
    // is a valid recipe), and the version enum is the registry's.
    assert!(
        tool.get("required").is_none(),
        "ontology must not require `guidance`"
    );
    let versions = tool["properties"]["version"]["enum"]
        .as_array()
        .expect("versions");
    assert!(versions.iter().any(|v| v == 1), "version 1 must be offered");
}

#[test]
fn chunk_and_filter_and_pattern_enums_are_generated() {
    let s = schema();
    let chunk: Vec<&str> = s["properties"]["chunk"]["properties"]["type"]["enum"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|v| v.as_str())
        .collect();
    assert!(
        chunk.contains(&"threaded_turns"),
        "chunk enum should include threaded_turns; got {chunk:?}"
    );
    let pats: Vec<&str> = s["properties"]["enrichment"]["properties"]["patterns"]["items"]
        ["properties"]["type"]["enum"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|v| v.as_str())
        .collect();
    assert!(pats.contains(&"role_overlap"));
}
